// Generated by gencpp from file radar_msgs/FloatVecType.msg
// DO NOT EDIT!


#ifndef RADAR_MSGS_MESSAGE_FLOATVECTYPE_H
#define RADAR_MSGS_MESSAGE_FLOATVECTYPE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace radar_msgs
{
template <class ContainerAllocator>
struct FloatVecType_
{
  typedef FloatVecType_<ContainerAllocator> Type;

  FloatVecType_()
    : header()
    , width(0)
    , height(0)
    , frameID(0)
    , cfarCount(0)
    , cfarObj()
    , data()  {
    }
  FloatVecType_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , width(0)
    , height(0)
    , frameID(0)
    , cfarCount(0)
    , cfarObj(_alloc)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _width_type;
  _width_type width;

   typedef uint32_t _height_type;
  _height_type height;

   typedef uint32_t _frameID_type;
  _frameID_type frameID;

   typedef uint32_t _cfarCount_type;
  _cfarCount_type cfarCount;

   typedef std::vector<uint16_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint16_t>> _cfarObj_type;
  _cfarObj_type cfarObj;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::radar_msgs::FloatVecType_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::radar_msgs::FloatVecType_<ContainerAllocator> const> ConstPtr;

}; // struct FloatVecType_

typedef ::radar_msgs::FloatVecType_<std::allocator<void> > FloatVecType;

typedef boost::shared_ptr< ::radar_msgs::FloatVecType > FloatVecTypePtr;
typedef boost::shared_ptr< ::radar_msgs::FloatVecType const> FloatVecTypeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::radar_msgs::FloatVecType_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::radar_msgs::FloatVecType_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::radar_msgs::FloatVecType_<ContainerAllocator1> & lhs, const ::radar_msgs::FloatVecType_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.width == rhs.width &&
    lhs.height == rhs.height &&
    lhs.frameID == rhs.frameID &&
    lhs.cfarCount == rhs.cfarCount &&
    lhs.cfarObj == rhs.cfarObj &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::radar_msgs::FloatVecType_<ContainerAllocator1> & lhs, const ::radar_msgs::FloatVecType_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace radar_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::radar_msgs::FloatVecType_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::radar_msgs::FloatVecType_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::radar_msgs::FloatVecType_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::radar_msgs::FloatVecType_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::radar_msgs::FloatVecType_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::radar_msgs::FloatVecType_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::radar_msgs::FloatVecType_<ContainerAllocator> >
{
  static const char* value()
  {
    return "158c8739358cbaf79a1f129713cd7329";
  }

  static const char* value(const ::radar_msgs::FloatVecType_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x158c8739358cbaf7ULL;
  static const uint64_t static_value2 = 0x9a1f129713cd7329ULL;
};

template<class ContainerAllocator>
struct DataType< ::radar_msgs::FloatVecType_<ContainerAllocator> >
{
  static const char* value()
  {
    return "radar_msgs/FloatVecType";
  }

  static const char* value(const ::radar_msgs::FloatVecType_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::radar_msgs::FloatVecType_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header           # Includes measurement timestamp and coordinate frame.\n"
"uint32 width\n"
"uint32 height\n"
"uint32 frameID\n"
"uint32 cfarCount\n"
"uint16[] cfarObj\n"
"float32[] data           # target snr\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::radar_msgs::FloatVecType_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::radar_msgs::FloatVecType_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.width);
      stream.next(m.height);
      stream.next(m.frameID);
      stream.next(m.cfarCount);
      stream.next(m.cfarObj);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FloatVecType_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::radar_msgs::FloatVecType_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::radar_msgs::FloatVecType_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "width: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.width);
    s << indent << "height: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.height);
    s << indent << "frameID: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.frameID);
    s << indent << "cfarCount: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.cfarCount);
    s << indent << "cfarObj[]" << std::endl;
    for (size_t i = 0; i < v.cfarObj.size(); ++i)
    {
      s << indent << "  cfarObj[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.cfarObj[i]);
    }
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // RADAR_MSGS_MESSAGE_FLOATVECTYPE_H
