// Generated by gencpp from file radar_msgs/OdArray.msg
// DO NOT EDIT!


#ifndef RADAR_MSGS_MESSAGE_ODARRAY_H
#define RADAR_MSGS_MESSAGE_ODARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <radar_msgs/Od.h>

namespace radar_msgs
{
template <class ContainerAllocator>
struct OdArray_
{
  typedef OdArray_<ContainerAllocator> Type;

  OdArray_()
    : header()
    , radarID(0)
    , frameCnt(0)
    , objNum(0)
    , odArray()  {
    }
  OdArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , radarID(0)
    , frameCnt(0)
    , objNum(0)
    , odArray(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _radarID_type;
  _radarID_type radarID;

   typedef uint32_t _frameCnt_type;
  _frameCnt_type frameCnt;

   typedef uint32_t _objNum_type;
  _objNum_type objNum;

   typedef std::vector< ::radar_msgs::Od_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::radar_msgs::Od_<ContainerAllocator> >> _odArray_type;
  _odArray_type odArray;





  typedef boost::shared_ptr< ::radar_msgs::OdArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::radar_msgs::OdArray_<ContainerAllocator> const> ConstPtr;

}; // struct OdArray_

typedef ::radar_msgs::OdArray_<std::allocator<void> > OdArray;

typedef boost::shared_ptr< ::radar_msgs::OdArray > OdArrayPtr;
typedef boost::shared_ptr< ::radar_msgs::OdArray const> OdArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::radar_msgs::OdArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::radar_msgs::OdArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::radar_msgs::OdArray_<ContainerAllocator1> & lhs, const ::radar_msgs::OdArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.radarID == rhs.radarID &&
    lhs.frameCnt == rhs.frameCnt &&
    lhs.objNum == rhs.objNum &&
    lhs.odArray == rhs.odArray;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::radar_msgs::OdArray_<ContainerAllocator1> & lhs, const ::radar_msgs::OdArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace radar_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::radar_msgs::OdArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::radar_msgs::OdArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::radar_msgs::OdArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::radar_msgs::OdArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::radar_msgs::OdArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::radar_msgs::OdArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::radar_msgs::OdArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "efbe1652c996ab4b9be091c4010e6a53";
  }

  static const char* value(const ::radar_msgs::OdArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xefbe1652c996ab4bULL;
  static const uint64_t static_value2 = 0x9be091c4010e6a53ULL;
};

template<class ContainerAllocator>
struct DataType< ::radar_msgs::OdArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "radar_msgs/OdArray";
  }

  static const char* value(const ::radar_msgs::OdArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::radar_msgs::OdArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header    header               # Includes measurement timestamp and coordinate frame.\n"
"uint32    radarID              # radar ID\n"
"uint32    frameCnt             # frame cnt in radar\n"
"uint32    objNum               # object number of this frame\n"
"Od[]      odArray              # array of tracking objects\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: radar_msgs/Od\n"
"# Header    header               # Includes measurement timestamp and coordinate frame.\n"
"uint32    object_ID            # object ID\n"
"uint16    age                  # total frames from the object occurs\n"
"uint8     measurement_status   # track status (0: measured; 1: new; 2: predicted)\n"
"uint8     motion_state         # movement state ( 0: static; 1: dynamic)\n"
"uint8     existance_confidence # existance confidence\n"
"geometry_msgs/Pose              pose #central position x, y, z; roll=0, pitch=0, yaw to quaternion\n"
"geometry_msgs/Vector3           dimensions #length, width, height\n"
"geometry_msgs/Twist             velocity\n"
"geometry_msgs/Twist             acceleration\n"
"geometry_msgs/Twist             v2ground #velocity towards ground of x, y, z orientation\n"
"geometry_msgs/Pose              pose_nearest #NearestPts x, y, z\n"
"uint8     type                 # object type (（0: car 小型汽车; 1: bike 两轮车; 2: pedestrian 行人; 3: truck 大车; 4: signboard 高空物; 5: ground 地面; 6: obstacle 静态障碍物)\n"
"uint8     car_confidence       # car confidence\n"
"uint8     bike_confidence      # bike confidence\n"
"uint8     ped_confidence       # pedestrian confidence\n"
"uint8     truck_confidence     # truck confidence\n"
"uint8     signboard_confidence # signboard confidence\n"
"uint8     ground_confidence    # ground confidence\n"
"uint8     obstacle_confidence  # obstacle confidence\n"
"float32   EnrollPtsNum         # EnrollPtsNum\n"
"float32   NearestPtsX          # NearestPtsX           \n"
"float32   NearestPtsY          # NearestPtsY\n"
"float32   NearestPtsZ          # NearestPtsZ\n"
"float32   Reserved_D  \n"
"uint32    Reserved_E          \n"
"uint32    Reserved_F           \n"
"int32     Reserved_G           \n"
"int32     Reserved_H    \n"
"uint16    Reserved_I   \n"
"uint16    Reserved_J    \n"
"int16     Reserved_K   \n"
"int16     Reserved_L \n"
"uint8     Reserved_M  \n"
"uint8     Reserved_N    \n"
"string    Reserved_O\n"
"string    Reserved_P\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: geometry_msgs/Twist\n"
"# This expresses velocity in free space broken into its linear and angular parts.\n"
"Vector3  linear\n"
"Vector3  angular\n"
;
  }

  static const char* value(const ::radar_msgs::OdArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::radar_msgs::OdArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.radarID);
      stream.next(m.frameCnt);
      stream.next(m.objNum);
      stream.next(m.odArray);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OdArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::radar_msgs::OdArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::radar_msgs::OdArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "radarID: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.radarID);
    s << indent << "frameCnt: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.frameCnt);
    s << indent << "objNum: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.objNum);
    s << indent << "odArray[]" << std::endl;
    for (size_t i = 0; i < v.odArray.size(); ++i)
    {
      s << indent << "  odArray[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::radar_msgs::Od_<ContainerAllocator> >::stream(s, indent + "    ", v.odArray[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // RADAR_MSGS_MESSAGE_ODARRAY_H
