// Generated by gencpp from file radar_msgs/RadarFeature.msg
// DO NOT EDIT!


#ifndef RADAR_MSGS_MESSAGE_RADARFEATURE_H
#define RADAR_MSGS_MESSAGE_RADARFEATURE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace radar_msgs
{
template <class ContainerAllocator>
struct RadarFeature_
{
  typedef RadarFeature_<ContainerAllocator> Type;

  RadarFeature_()
    : header()
    , targetNum(0)
    , d()
    , v()
    , azimuth()  {
    }
  RadarFeature_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , targetNum(0)
    , d(_alloc)
    , v(_alloc)
    , azimuth(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _targetNum_type;
  _targetNum_type targetNum;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _d_type;
  _d_type d;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _v_type;
  _v_type v;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _azimuth_type;
  _azimuth_type azimuth;





  typedef boost::shared_ptr< ::radar_msgs::RadarFeature_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::radar_msgs::RadarFeature_<ContainerAllocator> const> ConstPtr;

}; // struct RadarFeature_

typedef ::radar_msgs::RadarFeature_<std::allocator<void> > RadarFeature;

typedef boost::shared_ptr< ::radar_msgs::RadarFeature > RadarFeaturePtr;
typedef boost::shared_ptr< ::radar_msgs::RadarFeature const> RadarFeatureConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::radar_msgs::RadarFeature_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::radar_msgs::RadarFeature_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::radar_msgs::RadarFeature_<ContainerAllocator1> & lhs, const ::radar_msgs::RadarFeature_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.targetNum == rhs.targetNum &&
    lhs.d == rhs.d &&
    lhs.v == rhs.v &&
    lhs.azimuth == rhs.azimuth;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::radar_msgs::RadarFeature_<ContainerAllocator1> & lhs, const ::radar_msgs::RadarFeature_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace radar_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::radar_msgs::RadarFeature_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::radar_msgs::RadarFeature_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::radar_msgs::RadarFeature_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::radar_msgs::RadarFeature_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::radar_msgs::RadarFeature_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::radar_msgs::RadarFeature_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::radar_msgs::RadarFeature_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f7ad55b5738dc6964897be14d4580716";
  }

  static const char* value(const ::radar_msgs::RadarFeature_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf7ad55b5738dc696ULL;
  static const uint64_t static_value2 = 0x4897be14d4580716ULL;
};

template<class ContainerAllocator>
struct DataType< ::radar_msgs::RadarFeature_<ContainerAllocator> >
{
  static const char* value()
  {
    return "radar_msgs/RadarFeature";
  }

  static const char* value(const ::radar_msgs::RadarFeature_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::radar_msgs::RadarFeature_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header           # Includes measurement timestamp and coordinate frame.\n"
"uint32 targetNum        # targets Num\n"
"float32[] d             # distance\n"
"float32[] v             # target velocity\n"
"float32[] azimuth            # target azimuth\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::radar_msgs::RadarFeature_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::radar_msgs::RadarFeature_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.targetNum);
      stream.next(m.d);
      stream.next(m.v);
      stream.next(m.azimuth);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RadarFeature_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::radar_msgs::RadarFeature_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::radar_msgs::RadarFeature_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "targetNum: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.targetNum);
    s << indent << "d[]" << std::endl;
    for (size_t i = 0; i < v.d.size(); ++i)
    {
      s << indent << "  d[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.d[i]);
    }
    s << indent << "v[]" << std::endl;
    for (size_t i = 0; i < v.v.size(); ++i)
    {
      s << indent << "  v[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.v[i]);
    }
    s << indent << "azimuth[]" << std::endl;
    for (size_t i = 0; i < v.azimuth.size(); ++i)
    {
      s << indent << "  azimuth[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.azimuth[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // RADAR_MSGS_MESSAGE_RADARFEATURE_H
