// Generated by gencpp from file radar_msgs/RadarTarget.msg
// DO NOT EDIT!


#ifndef RADAR_MSGS_MESSAGE_RADARTARGET_H
#define RADAR_MSGS_MESSAGE_RADARTARGET_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace radar_msgs
{
template <class ContainerAllocator>
struct RadarTarget_
{
  typedef RadarTarget_<ContainerAllocator> Type;

  RadarTarget_()
    : header()
    , radarID(0)
    , frameCnt(0)
    , type(0)
    , targetNum(0)
    , polarState(0)
    , x()
    , y()
    , z()
    , v()
    , azimuth()
    , elevation()
    , snr()
    , power()
    , valid_flg()
    , existance_probability()
    , motion_state()
    , detection_class()
    , reset_cnt()
    , odTimeoutCnt()
    , reserved_a()
    , reserved_b()
    , reserved_c()
    , reserved_d()
    , reserved_e()
    , reserved_f()
    , reserved_g()
    , reserved_h()
    , reserved_i()
    , reserved_j()
    , reserved_k()
    , reserved_l()
    , reserved_m()
    , reserved_n()
    , reserved_o()  {
    }
  RadarTarget_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , radarID(0)
    , frameCnt(0)
    , type(0)
    , targetNum(0)
    , polarState(0)
    , x(_alloc)
    , y(_alloc)
    , z(_alloc)
    , v(_alloc)
    , azimuth(_alloc)
    , elevation(_alloc)
    , snr(_alloc)
    , power(_alloc)
    , valid_flg(_alloc)
    , existance_probability(_alloc)
    , motion_state(_alloc)
    , detection_class(_alloc)
    , reset_cnt(_alloc)
    , odTimeoutCnt(_alloc)
    , reserved_a(_alloc)
    , reserved_b(_alloc)
    , reserved_c(_alloc)
    , reserved_d(_alloc)
    , reserved_e(_alloc)
    , reserved_f(_alloc)
    , reserved_g(_alloc)
    , reserved_h(_alloc)
    , reserved_i(_alloc)
    , reserved_j(_alloc)
    , reserved_k(_alloc)
    , reserved_l(_alloc)
    , reserved_m(_alloc)
    , reserved_n(_alloc)
    , reserved_o(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _radarID_type;
  _radarID_type radarID;

   typedef uint32_t _frameCnt_type;
  _frameCnt_type frameCnt;

   typedef uint32_t _type_type;
  _type_type type;

   typedef uint32_t _targetNum_type;
  _targetNum_type targetNum;

   typedef uint32_t _polarState_type;
  _polarState_type polarState;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _x_type;
  _x_type x;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _y_type;
  _y_type y;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _z_type;
  _z_type z;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _v_type;
  _v_type v;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _azimuth_type;
  _azimuth_type azimuth;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _elevation_type;
  _elevation_type elevation;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _snr_type;
  _snr_type snr;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _power_type;
  _power_type power;

   typedef std::vector<uint16_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint16_t>> _valid_flg_type;
  _valid_flg_type valid_flg;

   typedef std::vector<uint16_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint16_t>> _existance_probability_type;
  _existance_probability_type existance_probability;

   typedef std::vector<uint16_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint16_t>> _motion_state_type;
  _motion_state_type motion_state;

   typedef std::vector<uint16_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint16_t>> _detection_class_type;
  _detection_class_type detection_class;

   typedef std::vector<uint16_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint16_t>> _reset_cnt_type;
  _reset_cnt_type reset_cnt;

   typedef std::vector<int16_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int16_t>> _odTimeoutCnt_type;
  _odTimeoutCnt_type odTimeoutCnt;

   typedef std::vector<uint16_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint16_t>> _reserved_a_type;
  _reserved_a_type reserved_a;

   typedef std::vector<uint16_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint16_t>> _reserved_b_type;
  _reserved_b_type reserved_b;

   typedef std::vector<uint16_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint16_t>> _reserved_c_type;
  _reserved_c_type reserved_c;

   typedef std::vector<uint16_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint16_t>> _reserved_d_type;
  _reserved_d_type reserved_d;

   typedef std::vector<uint16_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint16_t>> _reserved_e_type;
  _reserved_e_type reserved_e;

   typedef std::vector<int16_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int16_t>> _reserved_f_type;
  _reserved_f_type reserved_f;

   typedef std::vector<int16_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int16_t>> _reserved_g_type;
  _reserved_g_type reserved_g;

   typedef std::vector<int16_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int16_t>> _reserved_h_type;
  _reserved_h_type reserved_h;

   typedef std::vector<int16_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int16_t>> _reserved_i_type;
  _reserved_i_type reserved_i;

   typedef std::vector<int16_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int16_t>> _reserved_j_type;
  _reserved_j_type reserved_j;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _reserved_k_type;
  _reserved_k_type reserved_k;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _reserved_l_type;
  _reserved_l_type reserved_l;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _reserved_m_type;
  _reserved_m_type reserved_m;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _reserved_n_type;
  _reserved_n_type reserved_n;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _reserved_o_type;
  _reserved_o_type reserved_o;





  typedef boost::shared_ptr< ::radar_msgs::RadarTarget_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::radar_msgs::RadarTarget_<ContainerAllocator> const> ConstPtr;

}; // struct RadarTarget_

typedef ::radar_msgs::RadarTarget_<std::allocator<void> > RadarTarget;

typedef boost::shared_ptr< ::radar_msgs::RadarTarget > RadarTargetPtr;
typedef boost::shared_ptr< ::radar_msgs::RadarTarget const> RadarTargetConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::radar_msgs::RadarTarget_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::radar_msgs::RadarTarget_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::radar_msgs::RadarTarget_<ContainerAllocator1> & lhs, const ::radar_msgs::RadarTarget_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.radarID == rhs.radarID &&
    lhs.frameCnt == rhs.frameCnt &&
    lhs.type == rhs.type &&
    lhs.targetNum == rhs.targetNum &&
    lhs.polarState == rhs.polarState &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.v == rhs.v &&
    lhs.azimuth == rhs.azimuth &&
    lhs.elevation == rhs.elevation &&
    lhs.snr == rhs.snr &&
    lhs.power == rhs.power &&
    lhs.valid_flg == rhs.valid_flg &&
    lhs.existance_probability == rhs.existance_probability &&
    lhs.motion_state == rhs.motion_state &&
    lhs.detection_class == rhs.detection_class &&
    lhs.reset_cnt == rhs.reset_cnt &&
    lhs.odTimeoutCnt == rhs.odTimeoutCnt &&
    lhs.reserved_a == rhs.reserved_a &&
    lhs.reserved_b == rhs.reserved_b &&
    lhs.reserved_c == rhs.reserved_c &&
    lhs.reserved_d == rhs.reserved_d &&
    lhs.reserved_e == rhs.reserved_e &&
    lhs.reserved_f == rhs.reserved_f &&
    lhs.reserved_g == rhs.reserved_g &&
    lhs.reserved_h == rhs.reserved_h &&
    lhs.reserved_i == rhs.reserved_i &&
    lhs.reserved_j == rhs.reserved_j &&
    lhs.reserved_k == rhs.reserved_k &&
    lhs.reserved_l == rhs.reserved_l &&
    lhs.reserved_m == rhs.reserved_m &&
    lhs.reserved_n == rhs.reserved_n &&
    lhs.reserved_o == rhs.reserved_o;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::radar_msgs::RadarTarget_<ContainerAllocator1> & lhs, const ::radar_msgs::RadarTarget_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace radar_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::radar_msgs::RadarTarget_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::radar_msgs::RadarTarget_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::radar_msgs::RadarTarget_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::radar_msgs::RadarTarget_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::radar_msgs::RadarTarget_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::radar_msgs::RadarTarget_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::radar_msgs::RadarTarget_<ContainerAllocator> >
{
  static const char* value()
  {
    return "39cd070d450863c20128f17e660772a8";
  }

  static const char* value(const ::radar_msgs::RadarTarget_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x39cd070d450863c2ULL;
  static const uint64_t static_value2 = 0x0128f17e660772a8ULL;
};

template<class ContainerAllocator>
struct DataType< ::radar_msgs::RadarTarget_<ContainerAllocator> >
{
  static const char* value()
  {
    return "radar_msgs/RadarTarget";
  }

  static const char* value(const ::radar_msgs::RadarTarget_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::radar_msgs::RadarTarget_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header                   # Includes measurement timestamp and coordinate frame.\n"
"uint32 radarID                  # radar ID\n"
"uint32 frameCnt                 # frame cnt in radar\n"
"uint32 type                     # default type = 1\n"
"uint32 targetNum                # targets Num\n"
"uint32 polarState               # true---数据是以极坐标方式提供,false---数据是以笛卡尔坐标系\n"
"float32[] x                     # Position x, unit: m\n"
"float32[] y                     # Position y, unit: m\n"
"float32[] z                     # Position z, unit: m\n"
"float32[] v                     # target velocity, unit: m/s\n"
"float32[] azimuth               # target azimuth, unit: degree\n"
"float32[] elevation             # target elevation, unit: degree\n"
"float32[] snr                   # target snr, unit: dB\n"
"float32[] power                 # target power, unit: dB\n"
"uint16[] valid_flg              # target valid=0, target invalid=tbd\n"
"uint16[] existance_probability  # 0 ~ 100\n"
"uint16[] motion_state           # 0:static, 1:dynamic\n"
"uint16[] detection_class        # 0 = NoClassification, 1 = Noise, 2 = Ground, 3 = TraversableUnder, 4 = Obstacle, 255 = Invalid\n"
"uint16[] reset_cnt              # counter of radar reset times\n"
"int16[] odTimeoutCnt            # counter of od process timeout\n"
"uint16[] reserved_a             # temporarily set as frame lost cnt\n"
"uint16[] reserved_b             \n"
"uint16[] reserved_c             # temporarily set as pcl with extreme value and azimuth/elevation flag\n"
"uint16[] reserved_d             \n"
"uint16[] reserved_e             \n"
"int16[] reserved_f              # temporarily set as before adc error cnt\n"
"int16[] reserved_g              # temporarily set as after adc error cnt\n"
"int16[] reserved_h              # temporarily set as extreme point flag\n"
"int16[] reserved_i              # temporarily set as extreme value number\n"
"int16[] reserved_j              # temporarily set as profile 0/1 flag\n"
"float32[] reserved_k\n"
"float32[] reserved_l\n"
"float32[] reserved_m\n"
"float32[] reserved_n\n"
"float32[] reserved_o\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::radar_msgs::RadarTarget_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::radar_msgs::RadarTarget_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.radarID);
      stream.next(m.frameCnt);
      stream.next(m.type);
      stream.next(m.targetNum);
      stream.next(m.polarState);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.v);
      stream.next(m.azimuth);
      stream.next(m.elevation);
      stream.next(m.snr);
      stream.next(m.power);
      stream.next(m.valid_flg);
      stream.next(m.existance_probability);
      stream.next(m.motion_state);
      stream.next(m.detection_class);
      stream.next(m.reset_cnt);
      stream.next(m.odTimeoutCnt);
      stream.next(m.reserved_a);
      stream.next(m.reserved_b);
      stream.next(m.reserved_c);
      stream.next(m.reserved_d);
      stream.next(m.reserved_e);
      stream.next(m.reserved_f);
      stream.next(m.reserved_g);
      stream.next(m.reserved_h);
      stream.next(m.reserved_i);
      stream.next(m.reserved_j);
      stream.next(m.reserved_k);
      stream.next(m.reserved_l);
      stream.next(m.reserved_m);
      stream.next(m.reserved_n);
      stream.next(m.reserved_o);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RadarTarget_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::radar_msgs::RadarTarget_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::radar_msgs::RadarTarget_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "radarID: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.radarID);
    s << indent << "frameCnt: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.frameCnt);
    s << indent << "type: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.type);
    s << indent << "targetNum: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.targetNum);
    s << indent << "polarState: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.polarState);
    s << indent << "x[]" << std::endl;
    for (size_t i = 0; i < v.x.size(); ++i)
    {
      s << indent << "  x[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.x[i]);
    }
    s << indent << "y[]" << std::endl;
    for (size_t i = 0; i < v.y.size(); ++i)
    {
      s << indent << "  y[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.y[i]);
    }
    s << indent << "z[]" << std::endl;
    for (size_t i = 0; i < v.z.size(); ++i)
    {
      s << indent << "  z[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.z[i]);
    }
    s << indent << "v[]" << std::endl;
    for (size_t i = 0; i < v.v.size(); ++i)
    {
      s << indent << "  v[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.v[i]);
    }
    s << indent << "azimuth[]" << std::endl;
    for (size_t i = 0; i < v.azimuth.size(); ++i)
    {
      s << indent << "  azimuth[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.azimuth[i]);
    }
    s << indent << "elevation[]" << std::endl;
    for (size_t i = 0; i < v.elevation.size(); ++i)
    {
      s << indent << "  elevation[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.elevation[i]);
    }
    s << indent << "snr[]" << std::endl;
    for (size_t i = 0; i < v.snr.size(); ++i)
    {
      s << indent << "  snr[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.snr[i]);
    }
    s << indent << "power[]" << std::endl;
    for (size_t i = 0; i < v.power.size(); ++i)
    {
      s << indent << "  power[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.power[i]);
    }
    s << indent << "valid_flg[]" << std::endl;
    for (size_t i = 0; i < v.valid_flg.size(); ++i)
    {
      s << indent << "  valid_flg[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.valid_flg[i]);
    }
    s << indent << "existance_probability[]" << std::endl;
    for (size_t i = 0; i < v.existance_probability.size(); ++i)
    {
      s << indent << "  existance_probability[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.existance_probability[i]);
    }
    s << indent << "motion_state[]" << std::endl;
    for (size_t i = 0; i < v.motion_state.size(); ++i)
    {
      s << indent << "  motion_state[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.motion_state[i]);
    }
    s << indent << "detection_class[]" << std::endl;
    for (size_t i = 0; i < v.detection_class.size(); ++i)
    {
      s << indent << "  detection_class[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.detection_class[i]);
    }
    s << indent << "reset_cnt[]" << std::endl;
    for (size_t i = 0; i < v.reset_cnt.size(); ++i)
    {
      s << indent << "  reset_cnt[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.reset_cnt[i]);
    }
    s << indent << "odTimeoutCnt[]" << std::endl;
    for (size_t i = 0; i < v.odTimeoutCnt.size(); ++i)
    {
      s << indent << "  odTimeoutCnt[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.odTimeoutCnt[i]);
    }
    s << indent << "reserved_a[]" << std::endl;
    for (size_t i = 0; i < v.reserved_a.size(); ++i)
    {
      s << indent << "  reserved_a[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.reserved_a[i]);
    }
    s << indent << "reserved_b[]" << std::endl;
    for (size_t i = 0; i < v.reserved_b.size(); ++i)
    {
      s << indent << "  reserved_b[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.reserved_b[i]);
    }
    s << indent << "reserved_c[]" << std::endl;
    for (size_t i = 0; i < v.reserved_c.size(); ++i)
    {
      s << indent << "  reserved_c[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.reserved_c[i]);
    }
    s << indent << "reserved_d[]" << std::endl;
    for (size_t i = 0; i < v.reserved_d.size(); ++i)
    {
      s << indent << "  reserved_d[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.reserved_d[i]);
    }
    s << indent << "reserved_e[]" << std::endl;
    for (size_t i = 0; i < v.reserved_e.size(); ++i)
    {
      s << indent << "  reserved_e[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.reserved_e[i]);
    }
    s << indent << "reserved_f[]" << std::endl;
    for (size_t i = 0; i < v.reserved_f.size(); ++i)
    {
      s << indent << "  reserved_f[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.reserved_f[i]);
    }
    s << indent << "reserved_g[]" << std::endl;
    for (size_t i = 0; i < v.reserved_g.size(); ++i)
    {
      s << indent << "  reserved_g[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.reserved_g[i]);
    }
    s << indent << "reserved_h[]" << std::endl;
    for (size_t i = 0; i < v.reserved_h.size(); ++i)
    {
      s << indent << "  reserved_h[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.reserved_h[i]);
    }
    s << indent << "reserved_i[]" << std::endl;
    for (size_t i = 0; i < v.reserved_i.size(); ++i)
    {
      s << indent << "  reserved_i[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.reserved_i[i]);
    }
    s << indent << "reserved_j[]" << std::endl;
    for (size_t i = 0; i < v.reserved_j.size(); ++i)
    {
      s << indent << "  reserved_j[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.reserved_j[i]);
    }
    s << indent << "reserved_k[]" << std::endl;
    for (size_t i = 0; i < v.reserved_k.size(); ++i)
    {
      s << indent << "  reserved_k[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.reserved_k[i]);
    }
    s << indent << "reserved_l[]" << std::endl;
    for (size_t i = 0; i < v.reserved_l.size(); ++i)
    {
      s << indent << "  reserved_l[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.reserved_l[i]);
    }
    s << indent << "reserved_m[]" << std::endl;
    for (size_t i = 0; i < v.reserved_m.size(); ++i)
    {
      s << indent << "  reserved_m[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.reserved_m[i]);
    }
    s << indent << "reserved_n[]" << std::endl;
    for (size_t i = 0; i < v.reserved_n.size(); ++i)
    {
      s << indent << "  reserved_n[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.reserved_n[i]);
    }
    s << indent << "reserved_o[]" << std::endl;
    for (size_t i = 0; i < v.reserved_o.size(); ++i)
    {
      s << indent << "  reserved_o[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.reserved_o[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // RADAR_MSGS_MESSAGE_RADARTARGET_H
