// Generated by gencpp from file radar_msgs/RfStatus.msg
// DO NOT EDIT!


#ifndef RADAR_MSGS_MESSAGE_RFSTATUS_H
#define RADAR_MSGS_MESSAGE_RFSTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <radar_msgs/RlDigLatentFaultReportData.h>
#include <radar_msgs/RlMonReportHdrData.h>
#include <radar_msgs/RlMonTempReportData.h>
#include <radar_msgs/RlDigPeriodicReportData.h>
#include <radar_msgs/RlMonRxGainPhRep.h>
#include <radar_msgs/RlMonRxNoiseFigRep.h>
#include <radar_msgs/RlMonRxIfStageRep.h>
#include <radar_msgs/RlMonRxIntAnaSigRep.h>
#include <radar_msgs/RlMonPmclkloIntAnaSigRep.h>
#include <radar_msgs/RlMonGpadcIntAnaSigRep.h>
#include <radar_msgs/RlMonPllConVoltRep.h>
#include <radar_msgs/RlMonDccClkFreqRep.h>
#include <radar_msgs/RlMonSynthFreqNonLiveRep.h>
#include <radar_msgs/RlMonRxMixrInPwrRep.h>
#include <radar_msgs/RlMonTxIntAnaSigRep.h>
#include <radar_msgs/RlMonExtAnaSigRep.h>
#include <radar_msgs/RlMonSynthFreqRep.h>
#include <radar_msgs/RlMonTxPhShiftRep.h>
#include <radar_msgs/RlMonTxGainPhaMisRep.h>
#include <radar_msgs/RlMonTxBallBreakRep.h>
#include <radar_msgs/RlMonTxPowRep.h>
#include <radar_msgs/RlRecvdGpAdcData.h>
#include <radar_msgs/RlAnalogFaultReportData.h>
#include <radar_msgs/RlCalMonTimingErrorReportData.h>

namespace radar_msgs
{
template <class ContainerAllocator>
struct RfStatus_
{
  typedef RfStatus_<ContainerAllocator> Type;

  RfStatus_()
    : header()
    , radarID(0)
    , frameCnt(0)
    , digLatentFaultData()
    , reportHeaderData()
    , reportTempData()
    , digPeriodicReportData()
    , reportRxGainPhData()
    , reportRxNoiseFigData()
    , reportRxIfStageData()
    , reportRxIntAnaSigData()
    , reportPmclkloIntAnaSigData()
    , reportGpadcIntAnaSigData()
    , reportPllConVoltData()
    , reportDccClkFreqData()
    , reportSynthFreqNonLiveData()
    , reportRxMixrInPwrData()
    , reportTxIntAnaSigData()
    , reportExtAnaSigData()
    , reportSynthFreqData()
    , reportTxPhShiftData()
    , reportTxGainPhaMisData()
    , reportTxBallBreakData()
    , reportTxPowData()
    , reportRecvdGpAdcData()
    , reportAnalogFaultData()
    , reportTimingErrorData()  {
    }
  RfStatus_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , radarID(0)
    , frameCnt(0)
    , digLatentFaultData(_alloc)
    , reportHeaderData(_alloc)
    , reportTempData(_alloc)
    , digPeriodicReportData(_alloc)
    , reportRxGainPhData()
    , reportRxNoiseFigData()
    , reportRxIfStageData()
    , reportRxIntAnaSigData()
    , reportPmclkloIntAnaSigData()
    , reportGpadcIntAnaSigData(_alloc)
    , reportPllConVoltData(_alloc)
    , reportDccClkFreqData(_alloc)
    , reportSynthFreqNonLiveData(_alloc)
    , reportRxMixrInPwrData()
    , reportTxIntAnaSigData()
    , reportExtAnaSigData(_alloc)
    , reportSynthFreqData()
    , reportTxPhShiftData()
    , reportTxGainPhaMisData()
    , reportTxBallBreakData(_alloc)
    , reportTxPowData()
    , reportRecvdGpAdcData(_alloc)
    , reportAnalogFaultData(_alloc)
    , reportTimingErrorData(_alloc)  {
  (void)_alloc;
      reportRxGainPhData.assign( ::radar_msgs::RlMonRxGainPhRep_<ContainerAllocator> (_alloc));

      reportRxNoiseFigData.assign( ::radar_msgs::RlMonRxNoiseFigRep_<ContainerAllocator> (_alloc));

      reportRxIfStageData.assign( ::radar_msgs::RlMonRxIfStageRep_<ContainerAllocator> (_alloc));

      reportRxIntAnaSigData.assign( ::radar_msgs::RlMonRxIntAnaSigRep_<ContainerAllocator> (_alloc));

      reportPmclkloIntAnaSigData.assign( ::radar_msgs::RlMonPmclkloIntAnaSigRep_<ContainerAllocator> (_alloc));

      reportRxMixrInPwrData.assign( ::radar_msgs::RlMonRxMixrInPwrRep_<ContainerAllocator> (_alloc));

      reportTxIntAnaSigData.assign( ::radar_msgs::RlMonTxIntAnaSigRep_<ContainerAllocator> (_alloc));

      reportSynthFreqData.assign( ::radar_msgs::RlMonSynthFreqRep_<ContainerAllocator> (_alloc));

      reportTxPhShiftData.assign( ::radar_msgs::RlMonTxPhShiftRep_<ContainerAllocator> (_alloc));

      reportTxGainPhaMisData.assign( ::radar_msgs::RlMonTxGainPhaMisRep_<ContainerAllocator> (_alloc));

      reportTxPowData.assign( ::radar_msgs::RlMonTxPowRep_<ContainerAllocator> (_alloc));
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _radarID_type;
  _radarID_type radarID;

   typedef uint32_t _frameCnt_type;
  _frameCnt_type frameCnt;

   typedef  ::radar_msgs::RlDigLatentFaultReportData_<ContainerAllocator>  _digLatentFaultData_type;
  _digLatentFaultData_type digLatentFaultData;

   typedef  ::radar_msgs::RlMonReportHdrData_<ContainerAllocator>  _reportHeaderData_type;
  _reportHeaderData_type reportHeaderData;

   typedef  ::radar_msgs::RlMonTempReportData_<ContainerAllocator>  _reportTempData_type;
  _reportTempData_type reportTempData;

   typedef  ::radar_msgs::RlDigPeriodicReportData_<ContainerAllocator>  _digPeriodicReportData_type;
  _digPeriodicReportData_type digPeriodicReportData;

   typedef boost::array< ::radar_msgs::RlMonRxGainPhRep_<ContainerAllocator> , 2>  _reportRxGainPhData_type;
  _reportRxGainPhData_type reportRxGainPhData;

   typedef boost::array< ::radar_msgs::RlMonRxNoiseFigRep_<ContainerAllocator> , 2>  _reportRxNoiseFigData_type;
  _reportRxNoiseFigData_type reportRxNoiseFigData;

   typedef boost::array< ::radar_msgs::RlMonRxIfStageRep_<ContainerAllocator> , 2>  _reportRxIfStageData_type;
  _reportRxIfStageData_type reportRxIfStageData;

   typedef boost::array< ::radar_msgs::RlMonRxIntAnaSigRep_<ContainerAllocator> , 2>  _reportRxIntAnaSigData_type;
  _reportRxIntAnaSigData_type reportRxIntAnaSigData;

   typedef boost::array< ::radar_msgs::RlMonPmclkloIntAnaSigRep_<ContainerAllocator> , 2>  _reportPmclkloIntAnaSigData_type;
  _reportPmclkloIntAnaSigData_type reportPmclkloIntAnaSigData;

   typedef  ::radar_msgs::RlMonGpadcIntAnaSigRep_<ContainerAllocator>  _reportGpadcIntAnaSigData_type;
  _reportGpadcIntAnaSigData_type reportGpadcIntAnaSigData;

   typedef  ::radar_msgs::RlMonPllConVoltRep_<ContainerAllocator>  _reportPllConVoltData_type;
  _reportPllConVoltData_type reportPllConVoltData;

   typedef  ::radar_msgs::RlMonDccClkFreqRep_<ContainerAllocator>  _reportDccClkFreqData_type;
  _reportDccClkFreqData_type reportDccClkFreqData;

   typedef  ::radar_msgs::RlMonSynthFreqNonLiveRep_<ContainerAllocator>  _reportSynthFreqNonLiveData_type;
  _reportSynthFreqNonLiveData_type reportSynthFreqNonLiveData;

   typedef boost::array< ::radar_msgs::RlMonRxMixrInPwrRep_<ContainerAllocator> , 2>  _reportRxMixrInPwrData_type;
  _reportRxMixrInPwrData_type reportRxMixrInPwrData;

   typedef boost::array< ::radar_msgs::RlMonTxIntAnaSigRep_<ContainerAllocator> , 2>  _reportTxIntAnaSigData_type;
  _reportTxIntAnaSigData_type reportTxIntAnaSigData;

   typedef  ::radar_msgs::RlMonExtAnaSigRep_<ContainerAllocator>  _reportExtAnaSigData_type;
  _reportExtAnaSigData_type reportExtAnaSigData;

   typedef boost::array< ::radar_msgs::RlMonSynthFreqRep_<ContainerAllocator> , 2>  _reportSynthFreqData_type;
  _reportSynthFreqData_type reportSynthFreqData;

   typedef boost::array< ::radar_msgs::RlMonTxPhShiftRep_<ContainerAllocator> , 2>  _reportTxPhShiftData_type;
  _reportTxPhShiftData_type reportTxPhShiftData;

   typedef boost::array< ::radar_msgs::RlMonTxGainPhaMisRep_<ContainerAllocator> , 2>  _reportTxGainPhaMisData_type;
  _reportTxGainPhaMisData_type reportTxGainPhaMisData;

   typedef  ::radar_msgs::RlMonTxBallBreakRep_<ContainerAllocator>  _reportTxBallBreakData_type;
  _reportTxBallBreakData_type reportTxBallBreakData;

   typedef boost::array< ::radar_msgs::RlMonTxPowRep_<ContainerAllocator> , 2>  _reportTxPowData_type;
  _reportTxPowData_type reportTxPowData;

   typedef  ::radar_msgs::RlRecvdGpAdcData_<ContainerAllocator>  _reportRecvdGpAdcData_type;
  _reportRecvdGpAdcData_type reportRecvdGpAdcData;

   typedef  ::radar_msgs::RlAnalogFaultReportData_<ContainerAllocator>  _reportAnalogFaultData_type;
  _reportAnalogFaultData_type reportAnalogFaultData;

   typedef  ::radar_msgs::RlCalMonTimingErrorReportData_<ContainerAllocator>  _reportTimingErrorData_type;
  _reportTimingErrorData_type reportTimingErrorData;





  typedef boost::shared_ptr< ::radar_msgs::RfStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::radar_msgs::RfStatus_<ContainerAllocator> const> ConstPtr;

}; // struct RfStatus_

typedef ::radar_msgs::RfStatus_<std::allocator<void> > RfStatus;

typedef boost::shared_ptr< ::radar_msgs::RfStatus > RfStatusPtr;
typedef boost::shared_ptr< ::radar_msgs::RfStatus const> RfStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::radar_msgs::RfStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::radar_msgs::RfStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::radar_msgs::RfStatus_<ContainerAllocator1> & lhs, const ::radar_msgs::RfStatus_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.radarID == rhs.radarID &&
    lhs.frameCnt == rhs.frameCnt &&
    lhs.digLatentFaultData == rhs.digLatentFaultData &&
    lhs.reportHeaderData == rhs.reportHeaderData &&
    lhs.reportTempData == rhs.reportTempData &&
    lhs.digPeriodicReportData == rhs.digPeriodicReportData &&
    lhs.reportRxGainPhData == rhs.reportRxGainPhData &&
    lhs.reportRxNoiseFigData == rhs.reportRxNoiseFigData &&
    lhs.reportRxIfStageData == rhs.reportRxIfStageData &&
    lhs.reportRxIntAnaSigData == rhs.reportRxIntAnaSigData &&
    lhs.reportPmclkloIntAnaSigData == rhs.reportPmclkloIntAnaSigData &&
    lhs.reportGpadcIntAnaSigData == rhs.reportGpadcIntAnaSigData &&
    lhs.reportPllConVoltData == rhs.reportPllConVoltData &&
    lhs.reportDccClkFreqData == rhs.reportDccClkFreqData &&
    lhs.reportSynthFreqNonLiveData == rhs.reportSynthFreqNonLiveData &&
    lhs.reportRxMixrInPwrData == rhs.reportRxMixrInPwrData &&
    lhs.reportTxIntAnaSigData == rhs.reportTxIntAnaSigData &&
    lhs.reportExtAnaSigData == rhs.reportExtAnaSigData &&
    lhs.reportSynthFreqData == rhs.reportSynthFreqData &&
    lhs.reportTxPhShiftData == rhs.reportTxPhShiftData &&
    lhs.reportTxGainPhaMisData == rhs.reportTxGainPhaMisData &&
    lhs.reportTxBallBreakData == rhs.reportTxBallBreakData &&
    lhs.reportTxPowData == rhs.reportTxPowData &&
    lhs.reportRecvdGpAdcData == rhs.reportRecvdGpAdcData &&
    lhs.reportAnalogFaultData == rhs.reportAnalogFaultData &&
    lhs.reportTimingErrorData == rhs.reportTimingErrorData;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::radar_msgs::RfStatus_<ContainerAllocator1> & lhs, const ::radar_msgs::RfStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace radar_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::radar_msgs::RfStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::radar_msgs::RfStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::radar_msgs::RfStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::radar_msgs::RfStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::radar_msgs::RfStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::radar_msgs::RfStatus_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::radar_msgs::RfStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6fa249dd965cece786013e1f923eed7a";
  }

  static const char* value(const ::radar_msgs::RfStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6fa249dd965cece7ULL;
  static const uint64_t static_value2 = 0x86013e1f923eed7aULL;
};

template<class ContainerAllocator>
struct DataType< ::radar_msgs::RfStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "radar_msgs/RfStatus";
  }

  static const char* value(const ::radar_msgs::RfStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::radar_msgs::RfStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header                          header  # Includes measurement timestamp and coordinate frame.\n"
"uint32                          radarID # radar ID\n"
"uint32                          frameCnt # frame cnt in radar\n"
"RlDigLatentFaultReportData      digLatentFaultData\n"
"RlMonReportHdrData              reportHeaderData\n"
"RlMonTempReportData             reportTempData\n"
"RlDigPeriodicReportData         digPeriodicReportData\n"
"RlMonRxGainPhRep[2]             reportRxGainPhData\n"
"RlMonRxNoiseFigRep[2]           reportRxNoiseFigData\n"
"RlMonRxIfStageRep[2]            reportRxIfStageData\n"
"RlMonRxIntAnaSigRep[2]          reportRxIntAnaSigData\n"
"RlMonPmclkloIntAnaSigRep[2]     reportPmclkloIntAnaSigData\n"
"RlMonGpadcIntAnaSigRep          reportGpadcIntAnaSigData\n"
"RlMonPllConVoltRep              reportPllConVoltData\n"
"RlMonDccClkFreqRep              reportDccClkFreqData\n"
"RlMonSynthFreqNonLiveRep        reportSynthFreqNonLiveData\n"
"RlMonRxMixrInPwrRep[2]          reportRxMixrInPwrData\n"
"RlMonTxIntAnaSigRep[2]          reportTxIntAnaSigData\n"
"RlMonExtAnaSigRep               reportExtAnaSigData\n"
"RlMonSynthFreqRep[2]            reportSynthFreqData\n"
"RlMonTxPhShiftRep[2]            reportTxPhShiftData\n"
"RlMonTxGainPhaMisRep[2]         reportTxGainPhaMisData\n"
"RlMonTxBallBreakRep             reportTxBallBreakData\n"
"RlMonTxPowRep[2]                reportTxPowData\n"
"RlRecvdGpAdcData                reportRecvdGpAdcData\n"
"RlAnalogFaultReportData         reportAnalogFaultData\n"
"RlCalMonTimingErrorReportData   reportTimingErrorData\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: radar_msgs/RlDigLatentFaultReportData\n"
"uint32  digMonLatentFault\n"
"================================================================================\n"
"MSG: radar_msgs/RlMonReportHdrData\n"
"uint32  fttiCount\n"
"uint16  avgTemp\n"
"uint16  reserved0\n"
"uint32  reserved1\n"
"================================================================================\n"
"MSG: radar_msgs/RlMonTempReportData\n"
"uint16      statusFlags\n"
"uint16      errorCode\n"
"int16[10]   tempValues\n"
"uint32      reserved\n"
"uint32      timeStamp\n"
"================================================================================\n"
"MSG: radar_msgs/RlDigPeriodicReportData\n"
"uint32 digMonPeriodicStatus\n"
"uint32 timeStamp\n"
"================================================================================\n"
"MSG: radar_msgs/RlMonRxGainPhRep\n"
"uint16      statusFlags\n"
"uint16      errorCode\n"
"uint8       profIndex\n"
"uint8       loopbackPowerRF1\n"
"uint8       loopbackPowerRF2\n"
"uint8       loopbackPowerRF3\n"
"uint16[12]  rxGainVal\n"
"uint16[12]  rxPhaseVal\n"
"uint32      rxNoisePower1\n"
"uint32      rxNoisePower2\n"
"uint32      timeStamp\n"
"================================================================================\n"
"MSG: radar_msgs/RlMonRxNoiseFigRep\n"
"uint16      statusFlags\n"
"uint16      errorCode\n"
"uint8       profIndex\n"
"uint8       reserved0\n"
"uint16      reserved1\n"
"uint16[12]  rxNoiseFigVal\n"
"uint32      reserved2\n"
"uint32      reserved3\n"
"uint32      reserved4\n"
"uint32      timeStamp\n"
"================================================================================\n"
"MSG: radar_msgs/RlMonRxIfStageRep\n"
"uint16      statusFlags\n"
"uint16      errorCode\n"
"uint8       profIndex\n"
"uint8       reserved0\n"
"int16       lpfCutOffBandEdgeDroopValRx0\n"
"int8[8]     hpfCutOffFreqEr\n"
"int8[8]     lpfCutOffStopBandAtten\n"
"int8[8]     rxIfaGainErVal\n"
"int8        ifGainExp\n"
"uint8       reserved2\n"
"int8[6]     lpfCutOffBandEdgeDroopValRx\n"
"uint32      timeStamp\n"
"================================================================================\n"
"MSG: radar_msgs/RlMonRxIntAnaSigRep\n"
"uint16 statusFlags\n"
"uint16 errorCode\n"
"uint8 profIndex\n"
"uint8 reserved0\n"
"uint16 reserved1\n"
"uint32 timeStamp\n"
"================================================================================\n"
"MSG: radar_msgs/RlMonPmclkloIntAnaSigRep\n"
"uint16 statusFlags\n"
"uint16 errorCode\n"
"uint8 profIndex\n"
"int8 sync20GPower\n"
"uint16 reserved\n"
"uint32 timeStamp\n"
"================================================================================\n"
"MSG: radar_msgs/RlMonGpadcIntAnaSigRep\n"
"uint16 statusFlags\n"
"uint16 errorCode\n"
"int16 gpadcRef1Val\n"
"uint16 gpadcRef2Val\n"
"uint32 reserved\n"
"uint32 timeStamp\n"
"================================================================================\n"
"MSG: radar_msgs/RlMonPllConVoltRep\n"
"uint16      statusFlags\n"
"uint16      errorCode\n"
"int16[8]    pllContVoltVal\n"
"uint32      reserved\n"
"uint32      timeStamp\n"
"================================================================================\n"
"MSG: radar_msgs/RlMonDccClkFreqRep\n"
"uint16      statusFlags\n"
"uint16      errorCode\n"
"uint16[8]   freqMeasVal\n"
"uint32      reserved\n"
"uint32      timeStamp\n"
"================================================================================\n"
"MSG: radar_msgs/RlMonSynthFreqNonLiveRep\n"
"uint16 statusFlags\n"
"uint16 errorCode\n"
"uint8 profIndex0\n"
"uint8 reserved0\n"
"uint16 reserved1\n"
"int32 maxFreqErVal0\n"
"uint32 freqFailCnt0\n"
"uint32 maxFreqFailTime0\n"
"uint32 reserved2\n"
"uint8 profIndex1\n"
"uint8 reserved3\n"
"uint16 reserved4\n"
"int32 maxFreqErVal1\n"
"uint32 freqFailCnt1\n"
"uint32 maxFreqFailTime1\n"
"uint32 reserved5\n"
"uint32 timeStamp\n"
"================================================================================\n"
"MSG: radar_msgs/RlMonRxMixrInPwrRep\n"
"uint16 statusFlags\n"
"uint16 errorCode\n"
"uint8 profIndex\n"
"uint8 reserved0\n"
"uint16 reserved1\n"
"uint32 rxMixInVolt\n"
"uint32 reserved2\n"
"uint32 timeStamp\n"
"================================================================================\n"
"MSG: radar_msgs/RlMonTxIntAnaSigRep\n"
"uint16 statusFlags\n"
"uint16 errorCode\n"
"uint8 profIndex\n"
"uint8 reserved0\n"
"uint8 phShiftDacIdeltaMin\n"
"uint8 phShiftDacQdeltaMin\n"
"uint32 timeStamp\n"
"================================================================================\n"
"MSG: radar_msgs/RlMonExtAnaSigRep\n"
"uint16      statusFlags\n"
"uint16      errorCode\n"
"int16[6]    extAnaSigVal\n"
"uint32      reserved\n"
"uint32      timeStamp\n"
"================================================================================\n"
"MSG: radar_msgs/RlMonSynthFreqRep\n"
"uint16 statusFlags\n"
"uint16 errorCode\n"
"uint8 profIndex\n"
"uint8 reserved0\n"
"uint16 reserved1\n"
"int32 maxFreqErVal\n"
"uint32 freqFailCnt\n"
"uint32 reserved2\n"
"uint32 reserved3\n"
"uint32 timeStamp\n"
"================================================================================\n"
"MSG: radar_msgs/RlMonTxPhShiftRep\n"
"uint16 statusFlags\n"
"uint16 errorCode\n"
"uint8 profIndex\n"
"uint8 reserved0\n"
"uint16 reserved1\n"
"uint16 phaseShifterMonVal1\n"
"uint16 phaseShifterMonVal2\n"
"uint16 phaseShifterMonVal3\n"
"uint16 phaseShifterMonVal4\n"
"int16 txPsAmplitudeVal1\n"
"int16 txPsAmplitudeVal2\n"
"int16 txPsAmplitudeVal3\n"
"int16 txPsAmplitudeVal4\n"
"int8 txPsNoiseVal1\n"
"int8 txPsNoiseVal2\n"
"int8 txPsNoiseVal3\n"
"int8 txPsNoiseVal4\n"
"uint32 timeStamp\n"
"uint32 reserved2\n"
"uint32 reserved3\n"
"================================================================================\n"
"MSG: radar_msgs/RlMonTxGainPhaMisRep\n"
"uint16      statusFlags\n"
"uint16      errorCode\n"
"uint8       profIndex\n"
"uint8       noisePower00\n"
"uint8       noisePower01\n"
"uint8       noisePower02\n"
"int16[9]    txGainVal\n"
"uint16[9]   txPhaVal\n"
"uint8       noisePower10\n"
"uint8       noisePower11\n"
"uint8       noisePower12\n"
"uint8       noisePower20\n"
"uint8       noisePower21\n"
"uint8       noisePower22\n"
"uint8       reserved0\n"
"uint8       reserved1\n"
"uint32      timeStamp\n"
"================================================================================\n"
"MSG: radar_msgs/RlMonTxBallBreakRep\n"
"uint16 statusFlags\n"
"uint16 errorCode\n"
"int16 txReflCoefVal\n"
"uint16 reserved0\n"
"uint32 reserved1\n"
"uint32 timeStamp\n"
"================================================================================\n"
"MSG: radar_msgs/RlMonTxPowRep\n"
"uint16   statusFlags\n"
"uint16   errorCode\n"
"uint8    profIndex\n"
"uint8    reserved0\n"
"uint16   reserved1\n"
"int16[3] txPowVal\n"
"uint16   reserved2\n"
"uint32   timeStamp\n"
"================================================================================\n"
"MSG: radar_msgs/RlRecvdGpAdcData\n"
"RlGpAdcData[6]  sensor\n"
"uint16[4]       reserved0\n"
"uint32[7]       reserved1\n"
"================================================================================\n"
"MSG: radar_msgs/RlGpAdcData\n"
"uint16 min\n"
"uint16 max\n"
"uint16 avg\n"
"================================================================================\n"
"MSG: radar_msgs/RlAnalogFaultReportData\n"
"uint8   faultType\n"
"uint8   reserved0\n"
"uint16  reserved1\n"
"uint32  faultSig\n"
"uint32  reserved2\n"
"================================================================================\n"
"MSG: radar_msgs/RlCalMonTimingErrorReportData\n"
"uint16 timingFailCode\n"
"uint16 reserved\n"
;
  }

  static const char* value(const ::radar_msgs::RfStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::radar_msgs::RfStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.radarID);
      stream.next(m.frameCnt);
      stream.next(m.digLatentFaultData);
      stream.next(m.reportHeaderData);
      stream.next(m.reportTempData);
      stream.next(m.digPeriodicReportData);
      stream.next(m.reportRxGainPhData);
      stream.next(m.reportRxNoiseFigData);
      stream.next(m.reportRxIfStageData);
      stream.next(m.reportRxIntAnaSigData);
      stream.next(m.reportPmclkloIntAnaSigData);
      stream.next(m.reportGpadcIntAnaSigData);
      stream.next(m.reportPllConVoltData);
      stream.next(m.reportDccClkFreqData);
      stream.next(m.reportSynthFreqNonLiveData);
      stream.next(m.reportRxMixrInPwrData);
      stream.next(m.reportTxIntAnaSigData);
      stream.next(m.reportExtAnaSigData);
      stream.next(m.reportSynthFreqData);
      stream.next(m.reportTxPhShiftData);
      stream.next(m.reportTxGainPhaMisData);
      stream.next(m.reportTxBallBreakData);
      stream.next(m.reportTxPowData);
      stream.next(m.reportRecvdGpAdcData);
      stream.next(m.reportAnalogFaultData);
      stream.next(m.reportTimingErrorData);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RfStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::radar_msgs::RfStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::radar_msgs::RfStatus_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "radarID: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.radarID);
    s << indent << "frameCnt: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.frameCnt);
    s << indent << "digLatentFaultData: ";
    s << std::endl;
    Printer< ::radar_msgs::RlDigLatentFaultReportData_<ContainerAllocator> >::stream(s, indent + "  ", v.digLatentFaultData);
    s << indent << "reportHeaderData: ";
    s << std::endl;
    Printer< ::radar_msgs::RlMonReportHdrData_<ContainerAllocator> >::stream(s, indent + "  ", v.reportHeaderData);
    s << indent << "reportTempData: ";
    s << std::endl;
    Printer< ::radar_msgs::RlMonTempReportData_<ContainerAllocator> >::stream(s, indent + "  ", v.reportTempData);
    s << indent << "digPeriodicReportData: ";
    s << std::endl;
    Printer< ::radar_msgs::RlDigPeriodicReportData_<ContainerAllocator> >::stream(s, indent + "  ", v.digPeriodicReportData);
    s << indent << "reportRxGainPhData[]" << std::endl;
    for (size_t i = 0; i < v.reportRxGainPhData.size(); ++i)
    {
      s << indent << "  reportRxGainPhData[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::radar_msgs::RlMonRxGainPhRep_<ContainerAllocator> >::stream(s, indent + "    ", v.reportRxGainPhData[i]);
    }
    s << indent << "reportRxNoiseFigData[]" << std::endl;
    for (size_t i = 0; i < v.reportRxNoiseFigData.size(); ++i)
    {
      s << indent << "  reportRxNoiseFigData[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::radar_msgs::RlMonRxNoiseFigRep_<ContainerAllocator> >::stream(s, indent + "    ", v.reportRxNoiseFigData[i]);
    }
    s << indent << "reportRxIfStageData[]" << std::endl;
    for (size_t i = 0; i < v.reportRxIfStageData.size(); ++i)
    {
      s << indent << "  reportRxIfStageData[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::radar_msgs::RlMonRxIfStageRep_<ContainerAllocator> >::stream(s, indent + "    ", v.reportRxIfStageData[i]);
    }
    s << indent << "reportRxIntAnaSigData[]" << std::endl;
    for (size_t i = 0; i < v.reportRxIntAnaSigData.size(); ++i)
    {
      s << indent << "  reportRxIntAnaSigData[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::radar_msgs::RlMonRxIntAnaSigRep_<ContainerAllocator> >::stream(s, indent + "    ", v.reportRxIntAnaSigData[i]);
    }
    s << indent << "reportPmclkloIntAnaSigData[]" << std::endl;
    for (size_t i = 0; i < v.reportPmclkloIntAnaSigData.size(); ++i)
    {
      s << indent << "  reportPmclkloIntAnaSigData[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::radar_msgs::RlMonPmclkloIntAnaSigRep_<ContainerAllocator> >::stream(s, indent + "    ", v.reportPmclkloIntAnaSigData[i]);
    }
    s << indent << "reportGpadcIntAnaSigData: ";
    s << std::endl;
    Printer< ::radar_msgs::RlMonGpadcIntAnaSigRep_<ContainerAllocator> >::stream(s, indent + "  ", v.reportGpadcIntAnaSigData);
    s << indent << "reportPllConVoltData: ";
    s << std::endl;
    Printer< ::radar_msgs::RlMonPllConVoltRep_<ContainerAllocator> >::stream(s, indent + "  ", v.reportPllConVoltData);
    s << indent << "reportDccClkFreqData: ";
    s << std::endl;
    Printer< ::radar_msgs::RlMonDccClkFreqRep_<ContainerAllocator> >::stream(s, indent + "  ", v.reportDccClkFreqData);
    s << indent << "reportSynthFreqNonLiveData: ";
    s << std::endl;
    Printer< ::radar_msgs::RlMonSynthFreqNonLiveRep_<ContainerAllocator> >::stream(s, indent + "  ", v.reportSynthFreqNonLiveData);
    s << indent << "reportRxMixrInPwrData[]" << std::endl;
    for (size_t i = 0; i < v.reportRxMixrInPwrData.size(); ++i)
    {
      s << indent << "  reportRxMixrInPwrData[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::radar_msgs::RlMonRxMixrInPwrRep_<ContainerAllocator> >::stream(s, indent + "    ", v.reportRxMixrInPwrData[i]);
    }
    s << indent << "reportTxIntAnaSigData[]" << std::endl;
    for (size_t i = 0; i < v.reportTxIntAnaSigData.size(); ++i)
    {
      s << indent << "  reportTxIntAnaSigData[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::radar_msgs::RlMonTxIntAnaSigRep_<ContainerAllocator> >::stream(s, indent + "    ", v.reportTxIntAnaSigData[i]);
    }
    s << indent << "reportExtAnaSigData: ";
    s << std::endl;
    Printer< ::radar_msgs::RlMonExtAnaSigRep_<ContainerAllocator> >::stream(s, indent + "  ", v.reportExtAnaSigData);
    s << indent << "reportSynthFreqData[]" << std::endl;
    for (size_t i = 0; i < v.reportSynthFreqData.size(); ++i)
    {
      s << indent << "  reportSynthFreqData[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::radar_msgs::RlMonSynthFreqRep_<ContainerAllocator> >::stream(s, indent + "    ", v.reportSynthFreqData[i]);
    }
    s << indent << "reportTxPhShiftData[]" << std::endl;
    for (size_t i = 0; i < v.reportTxPhShiftData.size(); ++i)
    {
      s << indent << "  reportTxPhShiftData[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::radar_msgs::RlMonTxPhShiftRep_<ContainerAllocator> >::stream(s, indent + "    ", v.reportTxPhShiftData[i]);
    }
    s << indent << "reportTxGainPhaMisData[]" << std::endl;
    for (size_t i = 0; i < v.reportTxGainPhaMisData.size(); ++i)
    {
      s << indent << "  reportTxGainPhaMisData[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::radar_msgs::RlMonTxGainPhaMisRep_<ContainerAllocator> >::stream(s, indent + "    ", v.reportTxGainPhaMisData[i]);
    }
    s << indent << "reportTxBallBreakData: ";
    s << std::endl;
    Printer< ::radar_msgs::RlMonTxBallBreakRep_<ContainerAllocator> >::stream(s, indent + "  ", v.reportTxBallBreakData);
    s << indent << "reportTxPowData[]" << std::endl;
    for (size_t i = 0; i < v.reportTxPowData.size(); ++i)
    {
      s << indent << "  reportTxPowData[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::radar_msgs::RlMonTxPowRep_<ContainerAllocator> >::stream(s, indent + "    ", v.reportTxPowData[i]);
    }
    s << indent << "reportRecvdGpAdcData: ";
    s << std::endl;
    Printer< ::radar_msgs::RlRecvdGpAdcData_<ContainerAllocator> >::stream(s, indent + "  ", v.reportRecvdGpAdcData);
    s << indent << "reportAnalogFaultData: ";
    s << std::endl;
    Printer< ::radar_msgs::RlAnalogFaultReportData_<ContainerAllocator> >::stream(s, indent + "  ", v.reportAnalogFaultData);
    s << indent << "reportTimingErrorData: ";
    s << std::endl;
    Printer< ::radar_msgs::RlCalMonTimingErrorReportData_<ContainerAllocator> >::stream(s, indent + "  ", v.reportTimingErrorData);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RADAR_MSGS_MESSAGE_RFSTATUS_H
