// Generated by gencpp from file radar_msgs/RlCalMonTimingErrorReportData.msg
// DO NOT EDIT!


#ifndef RADAR_MSGS_MESSAGE_RLCALMONTIMINGERRORREPORTDATA_H
#define RADAR_MSGS_MESSAGE_RLCALMONTIMINGERRORREPORTDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace radar_msgs
{
template <class ContainerAllocator>
struct RlCalMonTimingErrorReportData_
{
  typedef RlCalMonTimingErrorReportData_<ContainerAllocator> Type;

  RlCalMonTimingErrorReportData_()
    : timingFailCode(0)
    , reserved(0)  {
    }
  RlCalMonTimingErrorReportData_(const ContainerAllocator& _alloc)
    : timingFailCode(0)
    , reserved(0)  {
  (void)_alloc;
    }



   typedef uint16_t _timingFailCode_type;
  _timingFailCode_type timingFailCode;

   typedef uint16_t _reserved_type;
  _reserved_type reserved;





  typedef boost::shared_ptr< ::radar_msgs::RlCalMonTimingErrorReportData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::radar_msgs::RlCalMonTimingErrorReportData_<ContainerAllocator> const> ConstPtr;

}; // struct RlCalMonTimingErrorReportData_

typedef ::radar_msgs::RlCalMonTimingErrorReportData_<std::allocator<void> > RlCalMonTimingErrorReportData;

typedef boost::shared_ptr< ::radar_msgs::RlCalMonTimingErrorReportData > RlCalMonTimingErrorReportDataPtr;
typedef boost::shared_ptr< ::radar_msgs::RlCalMonTimingErrorReportData const> RlCalMonTimingErrorReportDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::radar_msgs::RlCalMonTimingErrorReportData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::radar_msgs::RlCalMonTimingErrorReportData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::radar_msgs::RlCalMonTimingErrorReportData_<ContainerAllocator1> & lhs, const ::radar_msgs::RlCalMonTimingErrorReportData_<ContainerAllocator2> & rhs)
{
  return lhs.timingFailCode == rhs.timingFailCode &&
    lhs.reserved == rhs.reserved;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::radar_msgs::RlCalMonTimingErrorReportData_<ContainerAllocator1> & lhs, const ::radar_msgs::RlCalMonTimingErrorReportData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace radar_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::radar_msgs::RlCalMonTimingErrorReportData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::radar_msgs::RlCalMonTimingErrorReportData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::radar_msgs::RlCalMonTimingErrorReportData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::radar_msgs::RlCalMonTimingErrorReportData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::radar_msgs::RlCalMonTimingErrorReportData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::radar_msgs::RlCalMonTimingErrorReportData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::radar_msgs::RlCalMonTimingErrorReportData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ba804855ea66876247a3184393cfedc9";
  }

  static const char* value(const ::radar_msgs::RlCalMonTimingErrorReportData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xba804855ea668762ULL;
  static const uint64_t static_value2 = 0x47a3184393cfedc9ULL;
};

template<class ContainerAllocator>
struct DataType< ::radar_msgs::RlCalMonTimingErrorReportData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "radar_msgs/RlCalMonTimingErrorReportData";
  }

  static const char* value(const ::radar_msgs::RlCalMonTimingErrorReportData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::radar_msgs::RlCalMonTimingErrorReportData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 timingFailCode\n"
"uint16 reserved\n"
;
  }

  static const char* value(const ::radar_msgs::RlCalMonTimingErrorReportData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::radar_msgs::RlCalMonTimingErrorReportData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timingFailCode);
      stream.next(m.reserved);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RlCalMonTimingErrorReportData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::radar_msgs::RlCalMonTimingErrorReportData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::radar_msgs::RlCalMonTimingErrorReportData_<ContainerAllocator>& v)
  {
    s << indent << "timingFailCode: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.timingFailCode);
    s << indent << "reserved: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.reserved);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RADAR_MSGS_MESSAGE_RLCALMONTIMINGERRORREPORTDATA_H
