// Generated by gencpp from file radar_msgs/RlGpAdcData.msg
// DO NOT EDIT!


#ifndef RADAR_MSGS_MESSAGE_RLGPADCDATA_H
#define RADAR_MSGS_MESSAGE_RLGPADCDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace radar_msgs
{
template <class ContainerAllocator>
struct RlGpAdcData_
{
  typedef RlGpAdcData_<ContainerAllocator> Type;

  RlGpAdcData_()
    : min(0)
    , max(0)
    , avg(0)  {
    }
  RlGpAdcData_(const ContainerAllocator& _alloc)
    : min(0)
    , max(0)
    , avg(0)  {
  (void)_alloc;
    }



   typedef uint16_t _min_type;
  _min_type min;

   typedef uint16_t _max_type;
  _max_type max;

   typedef uint16_t _avg_type;
  _avg_type avg;





  typedef boost::shared_ptr< ::radar_msgs::RlGpAdcData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::radar_msgs::RlGpAdcData_<ContainerAllocator> const> ConstPtr;

}; // struct RlGpAdcData_

typedef ::radar_msgs::RlGpAdcData_<std::allocator<void> > RlGpAdcData;

typedef boost::shared_ptr< ::radar_msgs::RlGpAdcData > RlGpAdcDataPtr;
typedef boost::shared_ptr< ::radar_msgs::RlGpAdcData const> RlGpAdcDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::radar_msgs::RlGpAdcData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::radar_msgs::RlGpAdcData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::radar_msgs::RlGpAdcData_<ContainerAllocator1> & lhs, const ::radar_msgs::RlGpAdcData_<ContainerAllocator2> & rhs)
{
  return lhs.min == rhs.min &&
    lhs.max == rhs.max &&
    lhs.avg == rhs.avg;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::radar_msgs::RlGpAdcData_<ContainerAllocator1> & lhs, const ::radar_msgs::RlGpAdcData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace radar_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::radar_msgs::RlGpAdcData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::radar_msgs::RlGpAdcData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::radar_msgs::RlGpAdcData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::radar_msgs::RlGpAdcData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::radar_msgs::RlGpAdcData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::radar_msgs::RlGpAdcData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::radar_msgs::RlGpAdcData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2d3fd228e22a7d51e758f16247dffdea";
  }

  static const char* value(const ::radar_msgs::RlGpAdcData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2d3fd228e22a7d51ULL;
  static const uint64_t static_value2 = 0xe758f16247dffdeaULL;
};

template<class ContainerAllocator>
struct DataType< ::radar_msgs::RlGpAdcData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "radar_msgs/RlGpAdcData";
  }

  static const char* value(const ::radar_msgs::RlGpAdcData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::radar_msgs::RlGpAdcData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 min\n"
"uint16 max\n"
"uint16 avg\n"
;
  }

  static const char* value(const ::radar_msgs::RlGpAdcData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::radar_msgs::RlGpAdcData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.min);
      stream.next(m.max);
      stream.next(m.avg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RlGpAdcData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::radar_msgs::RlGpAdcData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::radar_msgs::RlGpAdcData_<ContainerAllocator>& v)
  {
    s << indent << "min: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.min);
    s << indent << "max: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.max);
    s << indent << "avg: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.avg);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RADAR_MSGS_MESSAGE_RLGPADCDATA_H
