// Generated by gencpp from file radar_msgs/RlMonTxBallBreakRep.msg
// DO NOT EDIT!


#ifndef RADAR_MSGS_MESSAGE_RLMONTXBALLBREAKREP_H
#define RADAR_MSGS_MESSAGE_RLMONTXBALLBREAKREP_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace radar_msgs
{
template <class ContainerAllocator>
struct RlMonTxBallBreakRep_
{
  typedef RlMonTxBallBreakRep_<ContainerAllocator> Type;

  RlMonTxBallBreakRep_()
    : statusFlags(0)
    , errorCode(0)
    , txReflCoefVal(0)
    , reserved0(0)
    , reserved1(0)
    , timeStamp(0)  {
    }
  RlMonTxBallBreakRep_(const ContainerAllocator& _alloc)
    : statusFlags(0)
    , errorCode(0)
    , txReflCoefVal(0)
    , reserved0(0)
    , reserved1(0)
    , timeStamp(0)  {
  (void)_alloc;
    }



   typedef uint16_t _statusFlags_type;
  _statusFlags_type statusFlags;

   typedef uint16_t _errorCode_type;
  _errorCode_type errorCode;

   typedef int16_t _txReflCoefVal_type;
  _txReflCoefVal_type txReflCoefVal;

   typedef uint16_t _reserved0_type;
  _reserved0_type reserved0;

   typedef uint32_t _reserved1_type;
  _reserved1_type reserved1;

   typedef uint32_t _timeStamp_type;
  _timeStamp_type timeStamp;





  typedef boost::shared_ptr< ::radar_msgs::RlMonTxBallBreakRep_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::radar_msgs::RlMonTxBallBreakRep_<ContainerAllocator> const> ConstPtr;

}; // struct RlMonTxBallBreakRep_

typedef ::radar_msgs::RlMonTxBallBreakRep_<std::allocator<void> > RlMonTxBallBreakRep;

typedef boost::shared_ptr< ::radar_msgs::RlMonTxBallBreakRep > RlMonTxBallBreakRepPtr;
typedef boost::shared_ptr< ::radar_msgs::RlMonTxBallBreakRep const> RlMonTxBallBreakRepConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::radar_msgs::RlMonTxBallBreakRep_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::radar_msgs::RlMonTxBallBreakRep_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::radar_msgs::RlMonTxBallBreakRep_<ContainerAllocator1> & lhs, const ::radar_msgs::RlMonTxBallBreakRep_<ContainerAllocator2> & rhs)
{
  return lhs.statusFlags == rhs.statusFlags &&
    lhs.errorCode == rhs.errorCode &&
    lhs.txReflCoefVal == rhs.txReflCoefVal &&
    lhs.reserved0 == rhs.reserved0 &&
    lhs.reserved1 == rhs.reserved1 &&
    lhs.timeStamp == rhs.timeStamp;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::radar_msgs::RlMonTxBallBreakRep_<ContainerAllocator1> & lhs, const ::radar_msgs::RlMonTxBallBreakRep_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace radar_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::radar_msgs::RlMonTxBallBreakRep_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::radar_msgs::RlMonTxBallBreakRep_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::radar_msgs::RlMonTxBallBreakRep_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::radar_msgs::RlMonTxBallBreakRep_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::radar_msgs::RlMonTxBallBreakRep_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::radar_msgs::RlMonTxBallBreakRep_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::radar_msgs::RlMonTxBallBreakRep_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7fdb45f1877e63d7b9ad34c244554856";
  }

  static const char* value(const ::radar_msgs::RlMonTxBallBreakRep_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7fdb45f1877e63d7ULL;
  static const uint64_t static_value2 = 0xb9ad34c244554856ULL;
};

template<class ContainerAllocator>
struct DataType< ::radar_msgs::RlMonTxBallBreakRep_<ContainerAllocator> >
{
  static const char* value()
  {
    return "radar_msgs/RlMonTxBallBreakRep";
  }

  static const char* value(const ::radar_msgs::RlMonTxBallBreakRep_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::radar_msgs::RlMonTxBallBreakRep_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 statusFlags\n"
"uint16 errorCode\n"
"int16 txReflCoefVal\n"
"uint16 reserved0\n"
"uint32 reserved1\n"
"uint32 timeStamp\n"
;
  }

  static const char* value(const ::radar_msgs::RlMonTxBallBreakRep_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::radar_msgs::RlMonTxBallBreakRep_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.statusFlags);
      stream.next(m.errorCode);
      stream.next(m.txReflCoefVal);
      stream.next(m.reserved0);
      stream.next(m.reserved1);
      stream.next(m.timeStamp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RlMonTxBallBreakRep_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::radar_msgs::RlMonTxBallBreakRep_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::radar_msgs::RlMonTxBallBreakRep_<ContainerAllocator>& v)
  {
    s << indent << "statusFlags: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.statusFlags);
    s << indent << "errorCode: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.errorCode);
    s << indent << "txReflCoefVal: ";
    Printer<int16_t>::stream(s, indent + "  ", v.txReflCoefVal);
    s << indent << "reserved0: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.reserved0);
    s << indent << "reserved1: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.reserved1);
    s << indent << "timeStamp: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.timeStamp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RADAR_MSGS_MESSAGE_RLMONTXBALLBREAKREP_H
