// Generated by gencpp from file radar_msgs/RlMonReportHdrData.msg
// DO NOT EDIT!


#ifndef RADAR_MSGS_MESSAGE_RLMONREPORTHDRDATA_H
#define RADAR_MSGS_MESSAGE_RLMONREPORTHDRDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace radar_msgs
{
template <class ContainerAllocator>
struct RlMonReportHdrData_
{
  typedef RlMonReportHdrData_<ContainerAllocator> Type;

  RlMonReportHdrData_()
    : fttiCount(0)
    , avgTemp(0)
    , reserved0(0)
    , reserved1(0)  {
    }
  RlMonReportHdrData_(const ContainerAllocator& _alloc)
    : fttiCount(0)
    , avgTemp(0)
    , reserved0(0)
    , reserved1(0)  {
  (void)_alloc;
    }



   typedef uint32_t _fttiCount_type;
  _fttiCount_type fttiCount;

   typedef uint16_t _avgTemp_type;
  _avgTemp_type avgTemp;

   typedef uint16_t _reserved0_type;
  _reserved0_type reserved0;

   typedef uint32_t _reserved1_type;
  _reserved1_type reserved1;





  typedef boost::shared_ptr< ::radar_msgs::RlMonReportHdrData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::radar_msgs::RlMonReportHdrData_<ContainerAllocator> const> ConstPtr;

}; // struct RlMonReportHdrData_

typedef ::radar_msgs::RlMonReportHdrData_<std::allocator<void> > RlMonReportHdrData;

typedef boost::shared_ptr< ::radar_msgs::RlMonReportHdrData > RlMonReportHdrDataPtr;
typedef boost::shared_ptr< ::radar_msgs::RlMonReportHdrData const> RlMonReportHdrDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::radar_msgs::RlMonReportHdrData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::radar_msgs::RlMonReportHdrData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::radar_msgs::RlMonReportHdrData_<ContainerAllocator1> & lhs, const ::radar_msgs::RlMonReportHdrData_<ContainerAllocator2> & rhs)
{
  return lhs.fttiCount == rhs.fttiCount &&
    lhs.avgTemp == rhs.avgTemp &&
    lhs.reserved0 == rhs.reserved0 &&
    lhs.reserved1 == rhs.reserved1;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::radar_msgs::RlMonReportHdrData_<ContainerAllocator1> & lhs, const ::radar_msgs::RlMonReportHdrData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace radar_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::radar_msgs::RlMonReportHdrData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::radar_msgs::RlMonReportHdrData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::radar_msgs::RlMonReportHdrData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::radar_msgs::RlMonReportHdrData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::radar_msgs::RlMonReportHdrData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::radar_msgs::RlMonReportHdrData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::radar_msgs::RlMonReportHdrData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "98626e73845bccc896ca0d734491f4f9";
  }

  static const char* value(const ::radar_msgs::RlMonReportHdrData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x98626e73845bccc8ULL;
  static const uint64_t static_value2 = 0x96ca0d734491f4f9ULL;
};

template<class ContainerAllocator>
struct DataType< ::radar_msgs::RlMonReportHdrData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "radar_msgs/RlMonReportHdrData";
  }

  static const char* value(const ::radar_msgs::RlMonReportHdrData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::radar_msgs::RlMonReportHdrData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32  fttiCount\n"
"uint16  avgTemp\n"
"uint16  reserved0\n"
"uint32  reserved1\n"
;
  }

  static const char* value(const ::radar_msgs::RlMonReportHdrData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::radar_msgs::RlMonReportHdrData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.fttiCount);
      stream.next(m.avgTemp);
      stream.next(m.reserved0);
      stream.next(m.reserved1);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RlMonReportHdrData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::radar_msgs::RlMonReportHdrData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::radar_msgs::RlMonReportHdrData_<ContainerAllocator>& v)
  {
    s << indent << "fttiCount: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.fttiCount);
    s << indent << "avgTemp: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.avgTemp);
    s << indent << "reserved0: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.reserved0);
    s << indent << "reserved1: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.reserved1);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RADAR_MSGS_MESSAGE_RLMONREPORTHDRDATA_H
