// Generated by gencpp from file radar_msgs/RlMonRxGainPhRep.msg
// DO NOT EDIT!


#ifndef RADAR_MSGS_MESSAGE_RLMONRXGAINPHREP_H
#define RADAR_MSGS_MESSAGE_RLMONRXGAINPHREP_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace radar_msgs
{
template <class ContainerAllocator>
struct RlMonRxGainPhRep_
{
  typedef RlMonRxGainPhRep_<ContainerAllocator> Type;

  RlMonRxGainPhRep_()
    : statusFlags(0)
    , errorCode(0)
    , profIndex(0)
    , loopbackPowerRF1(0)
    , loopbackPowerRF2(0)
    , loopbackPowerRF3(0)
    , rxGainVal()
    , rxPhaseVal()
    , rxNoisePower1(0)
    , rxNoisePower2(0)
    , timeStamp(0)  {
      rxGainVal.assign(0);

      rxPhaseVal.assign(0);
  }
  RlMonRxGainPhRep_(const ContainerAllocator& _alloc)
    : statusFlags(0)
    , errorCode(0)
    , profIndex(0)
    , loopbackPowerRF1(0)
    , loopbackPowerRF2(0)
    , loopbackPowerRF3(0)
    , rxGainVal()
    , rxPhaseVal()
    , rxNoisePower1(0)
    , rxNoisePower2(0)
    , timeStamp(0)  {
  (void)_alloc;
      rxGainVal.assign(0);

      rxPhaseVal.assign(0);
  }



   typedef uint16_t _statusFlags_type;
  _statusFlags_type statusFlags;

   typedef uint16_t _errorCode_type;
  _errorCode_type errorCode;

   typedef uint8_t _profIndex_type;
  _profIndex_type profIndex;

   typedef uint8_t _loopbackPowerRF1_type;
  _loopbackPowerRF1_type loopbackPowerRF1;

   typedef uint8_t _loopbackPowerRF2_type;
  _loopbackPowerRF2_type loopbackPowerRF2;

   typedef uint8_t _loopbackPowerRF3_type;
  _loopbackPowerRF3_type loopbackPowerRF3;

   typedef boost::array<uint16_t, 12>  _rxGainVal_type;
  _rxGainVal_type rxGainVal;

   typedef boost::array<uint16_t, 12>  _rxPhaseVal_type;
  _rxPhaseVal_type rxPhaseVal;

   typedef uint32_t _rxNoisePower1_type;
  _rxNoisePower1_type rxNoisePower1;

   typedef uint32_t _rxNoisePower2_type;
  _rxNoisePower2_type rxNoisePower2;

   typedef uint32_t _timeStamp_type;
  _timeStamp_type timeStamp;





  typedef boost::shared_ptr< ::radar_msgs::RlMonRxGainPhRep_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::radar_msgs::RlMonRxGainPhRep_<ContainerAllocator> const> ConstPtr;

}; // struct RlMonRxGainPhRep_

typedef ::radar_msgs::RlMonRxGainPhRep_<std::allocator<void> > RlMonRxGainPhRep;

typedef boost::shared_ptr< ::radar_msgs::RlMonRxGainPhRep > RlMonRxGainPhRepPtr;
typedef boost::shared_ptr< ::radar_msgs::RlMonRxGainPhRep const> RlMonRxGainPhRepConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::radar_msgs::RlMonRxGainPhRep_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::radar_msgs::RlMonRxGainPhRep_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::radar_msgs::RlMonRxGainPhRep_<ContainerAllocator1> & lhs, const ::radar_msgs::RlMonRxGainPhRep_<ContainerAllocator2> & rhs)
{
  return lhs.statusFlags == rhs.statusFlags &&
    lhs.errorCode == rhs.errorCode &&
    lhs.profIndex == rhs.profIndex &&
    lhs.loopbackPowerRF1 == rhs.loopbackPowerRF1 &&
    lhs.loopbackPowerRF2 == rhs.loopbackPowerRF2 &&
    lhs.loopbackPowerRF3 == rhs.loopbackPowerRF3 &&
    lhs.rxGainVal == rhs.rxGainVal &&
    lhs.rxPhaseVal == rhs.rxPhaseVal &&
    lhs.rxNoisePower1 == rhs.rxNoisePower1 &&
    lhs.rxNoisePower2 == rhs.rxNoisePower2 &&
    lhs.timeStamp == rhs.timeStamp;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::radar_msgs::RlMonRxGainPhRep_<ContainerAllocator1> & lhs, const ::radar_msgs::RlMonRxGainPhRep_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace radar_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::radar_msgs::RlMonRxGainPhRep_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::radar_msgs::RlMonRxGainPhRep_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::radar_msgs::RlMonRxGainPhRep_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::radar_msgs::RlMonRxGainPhRep_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::radar_msgs::RlMonRxGainPhRep_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::radar_msgs::RlMonRxGainPhRep_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::radar_msgs::RlMonRxGainPhRep_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f089091924cc998599ccbe78b8cddb04";
  }

  static const char* value(const ::radar_msgs::RlMonRxGainPhRep_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf089091924cc9985ULL;
  static const uint64_t static_value2 = 0x99ccbe78b8cddb04ULL;
};

template<class ContainerAllocator>
struct DataType< ::radar_msgs::RlMonRxGainPhRep_<ContainerAllocator> >
{
  static const char* value()
  {
    return "radar_msgs/RlMonRxGainPhRep";
  }

  static const char* value(const ::radar_msgs::RlMonRxGainPhRep_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::radar_msgs::RlMonRxGainPhRep_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16      statusFlags\n"
"uint16      errorCode\n"
"uint8       profIndex\n"
"uint8       loopbackPowerRF1\n"
"uint8       loopbackPowerRF2\n"
"uint8       loopbackPowerRF3\n"
"uint16[12]  rxGainVal\n"
"uint16[12]  rxPhaseVal\n"
"uint32      rxNoisePower1\n"
"uint32      rxNoisePower2\n"
"uint32      timeStamp\n"
;
  }

  static const char* value(const ::radar_msgs::RlMonRxGainPhRep_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::radar_msgs::RlMonRxGainPhRep_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.statusFlags);
      stream.next(m.errorCode);
      stream.next(m.profIndex);
      stream.next(m.loopbackPowerRF1);
      stream.next(m.loopbackPowerRF2);
      stream.next(m.loopbackPowerRF3);
      stream.next(m.rxGainVal);
      stream.next(m.rxPhaseVal);
      stream.next(m.rxNoisePower1);
      stream.next(m.rxNoisePower2);
      stream.next(m.timeStamp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RlMonRxGainPhRep_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::radar_msgs::RlMonRxGainPhRep_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::radar_msgs::RlMonRxGainPhRep_<ContainerAllocator>& v)
  {
    s << indent << "statusFlags: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.statusFlags);
    s << indent << "errorCode: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.errorCode);
    s << indent << "profIndex: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.profIndex);
    s << indent << "loopbackPowerRF1: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.loopbackPowerRF1);
    s << indent << "loopbackPowerRF2: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.loopbackPowerRF2);
    s << indent << "loopbackPowerRF3: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.loopbackPowerRF3);
    s << indent << "rxGainVal[]" << std::endl;
    for (size_t i = 0; i < v.rxGainVal.size(); ++i)
    {
      s << indent << "  rxGainVal[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.rxGainVal[i]);
    }
    s << indent << "rxPhaseVal[]" << std::endl;
    for (size_t i = 0; i < v.rxPhaseVal.size(); ++i)
    {
      s << indent << "  rxPhaseVal[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.rxPhaseVal[i]);
    }
    s << indent << "rxNoisePower1: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.rxNoisePower1);
    s << indent << "rxNoisePower2: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.rxNoisePower2);
    s << indent << "timeStamp: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.timeStamp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RADAR_MSGS_MESSAGE_RLMONRXGAINPHREP_H
