// Generated by gencpp from file radar_msgs/RlMonTxIntAnaSigRep.msg
// DO NOT EDIT!


#ifndef RADAR_MSGS_MESSAGE_RLMONTXINTANASIGREP_H
#define RADAR_MSGS_MESSAGE_RLMONTXINTANASIGREP_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace radar_msgs
{
template <class ContainerAllocator>
struct RlMonTxIntAnaSigRep_
{
  typedef RlMonTxIntAnaSigRep_<ContainerAllocator> Type;

  RlMonTxIntAnaSigRep_()
    : statusFlags(0)
    , errorCode(0)
    , profIndex(0)
    , reserved0(0)
    , phShiftDacIdeltaMin(0)
    , phShiftDacQdeltaMin(0)
    , timeStamp(0)  {
    }
  RlMonTxIntAnaSigRep_(const ContainerAllocator& _alloc)
    : statusFlags(0)
    , errorCode(0)
    , profIndex(0)
    , reserved0(0)
    , phShiftDacIdeltaMin(0)
    , phShiftDacQdeltaMin(0)
    , timeStamp(0)  {
  (void)_alloc;
    }



   typedef uint16_t _statusFlags_type;
  _statusFlags_type statusFlags;

   typedef uint16_t _errorCode_type;
  _errorCode_type errorCode;

   typedef uint8_t _profIndex_type;
  _profIndex_type profIndex;

   typedef uint8_t _reserved0_type;
  _reserved0_type reserved0;

   typedef uint8_t _phShiftDacIdeltaMin_type;
  _phShiftDacIdeltaMin_type phShiftDacIdeltaMin;

   typedef uint8_t _phShiftDacQdeltaMin_type;
  _phShiftDacQdeltaMin_type phShiftDacQdeltaMin;

   typedef uint32_t _timeStamp_type;
  _timeStamp_type timeStamp;





  typedef boost::shared_ptr< ::radar_msgs::RlMonTxIntAnaSigRep_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::radar_msgs::RlMonTxIntAnaSigRep_<ContainerAllocator> const> ConstPtr;

}; // struct RlMonTxIntAnaSigRep_

typedef ::radar_msgs::RlMonTxIntAnaSigRep_<std::allocator<void> > RlMonTxIntAnaSigRep;

typedef boost::shared_ptr< ::radar_msgs::RlMonTxIntAnaSigRep > RlMonTxIntAnaSigRepPtr;
typedef boost::shared_ptr< ::radar_msgs::RlMonTxIntAnaSigRep const> RlMonTxIntAnaSigRepConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::radar_msgs::RlMonTxIntAnaSigRep_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::radar_msgs::RlMonTxIntAnaSigRep_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::radar_msgs::RlMonTxIntAnaSigRep_<ContainerAllocator1> & lhs, const ::radar_msgs::RlMonTxIntAnaSigRep_<ContainerAllocator2> & rhs)
{
  return lhs.statusFlags == rhs.statusFlags &&
    lhs.errorCode == rhs.errorCode &&
    lhs.profIndex == rhs.profIndex &&
    lhs.reserved0 == rhs.reserved0 &&
    lhs.phShiftDacIdeltaMin == rhs.phShiftDacIdeltaMin &&
    lhs.phShiftDacQdeltaMin == rhs.phShiftDacQdeltaMin &&
    lhs.timeStamp == rhs.timeStamp;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::radar_msgs::RlMonTxIntAnaSigRep_<ContainerAllocator1> & lhs, const ::radar_msgs::RlMonTxIntAnaSigRep_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace radar_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::radar_msgs::RlMonTxIntAnaSigRep_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::radar_msgs::RlMonTxIntAnaSigRep_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::radar_msgs::RlMonTxIntAnaSigRep_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::radar_msgs::RlMonTxIntAnaSigRep_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::radar_msgs::RlMonTxIntAnaSigRep_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::radar_msgs::RlMonTxIntAnaSigRep_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::radar_msgs::RlMonTxIntAnaSigRep_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9475d3a28bdcb35b92a3be2cb7462b1d";
  }

  static const char* value(const ::radar_msgs::RlMonTxIntAnaSigRep_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9475d3a28bdcb35bULL;
  static const uint64_t static_value2 = 0x92a3be2cb7462b1dULL;
};

template<class ContainerAllocator>
struct DataType< ::radar_msgs::RlMonTxIntAnaSigRep_<ContainerAllocator> >
{
  static const char* value()
  {
    return "radar_msgs/RlMonTxIntAnaSigRep";
  }

  static const char* value(const ::radar_msgs::RlMonTxIntAnaSigRep_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::radar_msgs::RlMonTxIntAnaSigRep_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 statusFlags\n"
"uint16 errorCode\n"
"uint8 profIndex\n"
"uint8 reserved0\n"
"uint8 phShiftDacIdeltaMin\n"
"uint8 phShiftDacQdeltaMin\n"
"uint32 timeStamp\n"
;
  }

  static const char* value(const ::radar_msgs::RlMonTxIntAnaSigRep_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::radar_msgs::RlMonTxIntAnaSigRep_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.statusFlags);
      stream.next(m.errorCode);
      stream.next(m.profIndex);
      stream.next(m.reserved0);
      stream.next(m.phShiftDacIdeltaMin);
      stream.next(m.phShiftDacQdeltaMin);
      stream.next(m.timeStamp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RlMonTxIntAnaSigRep_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::radar_msgs::RlMonTxIntAnaSigRep_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::radar_msgs::RlMonTxIntAnaSigRep_<ContainerAllocator>& v)
  {
    s << indent << "statusFlags: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.statusFlags);
    s << indent << "errorCode: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.errorCode);
    s << indent << "profIndex: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.profIndex);
    s << indent << "reserved0: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.reserved0);
    s << indent << "phShiftDacIdeltaMin: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.phShiftDacIdeltaMin);
    s << indent << "phShiftDacQdeltaMin: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.phShiftDacQdeltaMin);
    s << indent << "timeStamp: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.timeStamp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RADAR_MSGS_MESSAGE_RLMONTXINTANASIGREP_H
