// Generated by gencpp from file radar_msgs/RlMonSynthFreqRep.msg
// DO NOT EDIT!


#ifndef RADAR_MSGS_MESSAGE_RLMONSYNTHFREQREP_H
#define RADAR_MSGS_MESSAGE_RLMONSYNTHFREQREP_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace radar_msgs
{
template <class ContainerAllocator>
struct RlMonSynthFreqRep_
{
  typedef RlMonSynthFreqRep_<ContainerAllocator> Type;

  RlMonSynthFreqRep_()
    : statusFlags(0)
    , errorCode(0)
    , profIndex(0)
    , reserved0(0)
    , reserved1(0)
    , maxFreqErVal(0)
    , freqFailCnt(0)
    , reserved2(0)
    , reserved3(0)
    , timeStamp(0)  {
    }
  RlMonSynthFreqRep_(const ContainerAllocator& _alloc)
    : statusFlags(0)
    , errorCode(0)
    , profIndex(0)
    , reserved0(0)
    , reserved1(0)
    , maxFreqErVal(0)
    , freqFailCnt(0)
    , reserved2(0)
    , reserved3(0)
    , timeStamp(0)  {
  (void)_alloc;
    }



   typedef uint16_t _statusFlags_type;
  _statusFlags_type statusFlags;

   typedef uint16_t _errorCode_type;
  _errorCode_type errorCode;

   typedef uint8_t _profIndex_type;
  _profIndex_type profIndex;

   typedef uint8_t _reserved0_type;
  _reserved0_type reserved0;

   typedef uint16_t _reserved1_type;
  _reserved1_type reserved1;

   typedef int32_t _maxFreqErVal_type;
  _maxFreqErVal_type maxFreqErVal;

   typedef uint32_t _freqFailCnt_type;
  _freqFailCnt_type freqFailCnt;

   typedef uint32_t _reserved2_type;
  _reserved2_type reserved2;

   typedef uint32_t _reserved3_type;
  _reserved3_type reserved3;

   typedef uint32_t _timeStamp_type;
  _timeStamp_type timeStamp;





  typedef boost::shared_ptr< ::radar_msgs::RlMonSynthFreqRep_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::radar_msgs::RlMonSynthFreqRep_<ContainerAllocator> const> ConstPtr;

}; // struct RlMonSynthFreqRep_

typedef ::radar_msgs::RlMonSynthFreqRep_<std::allocator<void> > RlMonSynthFreqRep;

typedef boost::shared_ptr< ::radar_msgs::RlMonSynthFreqRep > RlMonSynthFreqRepPtr;
typedef boost::shared_ptr< ::radar_msgs::RlMonSynthFreqRep const> RlMonSynthFreqRepConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::radar_msgs::RlMonSynthFreqRep_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::radar_msgs::RlMonSynthFreqRep_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::radar_msgs::RlMonSynthFreqRep_<ContainerAllocator1> & lhs, const ::radar_msgs::RlMonSynthFreqRep_<ContainerAllocator2> & rhs)
{
  return lhs.statusFlags == rhs.statusFlags &&
    lhs.errorCode == rhs.errorCode &&
    lhs.profIndex == rhs.profIndex &&
    lhs.reserved0 == rhs.reserved0 &&
    lhs.reserved1 == rhs.reserved1 &&
    lhs.maxFreqErVal == rhs.maxFreqErVal &&
    lhs.freqFailCnt == rhs.freqFailCnt &&
    lhs.reserved2 == rhs.reserved2 &&
    lhs.reserved3 == rhs.reserved3 &&
    lhs.timeStamp == rhs.timeStamp;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::radar_msgs::RlMonSynthFreqRep_<ContainerAllocator1> & lhs, const ::radar_msgs::RlMonSynthFreqRep_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace radar_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::radar_msgs::RlMonSynthFreqRep_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::radar_msgs::RlMonSynthFreqRep_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::radar_msgs::RlMonSynthFreqRep_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::radar_msgs::RlMonSynthFreqRep_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::radar_msgs::RlMonSynthFreqRep_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::radar_msgs::RlMonSynthFreqRep_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::radar_msgs::RlMonSynthFreqRep_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beaba851e1822aee0650a3be6cc60286";
  }

  static const char* value(const ::radar_msgs::RlMonSynthFreqRep_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbeaba851e1822aeeULL;
  static const uint64_t static_value2 = 0x0650a3be6cc60286ULL;
};

template<class ContainerAllocator>
struct DataType< ::radar_msgs::RlMonSynthFreqRep_<ContainerAllocator> >
{
  static const char* value()
  {
    return "radar_msgs/RlMonSynthFreqRep";
  }

  static const char* value(const ::radar_msgs::RlMonSynthFreqRep_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::radar_msgs::RlMonSynthFreqRep_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 statusFlags\n"
"uint16 errorCode\n"
"uint8 profIndex\n"
"uint8 reserved0\n"
"uint16 reserved1\n"
"int32 maxFreqErVal\n"
"uint32 freqFailCnt\n"
"uint32 reserved2\n"
"uint32 reserved3\n"
"uint32 timeStamp\n"
;
  }

  static const char* value(const ::radar_msgs::RlMonSynthFreqRep_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::radar_msgs::RlMonSynthFreqRep_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.statusFlags);
      stream.next(m.errorCode);
      stream.next(m.profIndex);
      stream.next(m.reserved0);
      stream.next(m.reserved1);
      stream.next(m.maxFreqErVal);
      stream.next(m.freqFailCnt);
      stream.next(m.reserved2);
      stream.next(m.reserved3);
      stream.next(m.timeStamp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RlMonSynthFreqRep_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::radar_msgs::RlMonSynthFreqRep_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::radar_msgs::RlMonSynthFreqRep_<ContainerAllocator>& v)
  {
    s << indent << "statusFlags: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.statusFlags);
    s << indent << "errorCode: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.errorCode);
    s << indent << "profIndex: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.profIndex);
    s << indent << "reserved0: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.reserved0);
    s << indent << "reserved1: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.reserved1);
    s << indent << "maxFreqErVal: ";
    Printer<int32_t>::stream(s, indent + "  ", v.maxFreqErVal);
    s << indent << "freqFailCnt: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.freqFailCnt);
    s << indent << "reserved2: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.reserved2);
    s << indent << "reserved3: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.reserved3);
    s << indent << "timeStamp: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.timeStamp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RADAR_MSGS_MESSAGE_RLMONSYNTHFREQREP_H
