// Generated by gencpp from file radar_msgs/RlMonDccClkFreqRep.msg
// DO NOT EDIT!


#ifndef RADAR_MSGS_MESSAGE_RLMONDCCCLKFREQREP_H
#define RADAR_MSGS_MESSAGE_RLMONDCCCLKFREQREP_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace radar_msgs
{
template <class ContainerAllocator>
struct RlMonDccClkFreqRep_
{
  typedef RlMonDccClkFreqRep_<ContainerAllocator> Type;

  RlMonDccClkFreqRep_()
    : statusFlags(0)
    , errorCode(0)
    , freqMeasVal()
    , reserved(0)
    , timeStamp(0)  {
      freqMeasVal.assign(0);
  }
  RlMonDccClkFreqRep_(const ContainerAllocator& _alloc)
    : statusFlags(0)
    , errorCode(0)
    , freqMeasVal()
    , reserved(0)
    , timeStamp(0)  {
  (void)_alloc;
      freqMeasVal.assign(0);
  }



   typedef uint16_t _statusFlags_type;
  _statusFlags_type statusFlags;

   typedef uint16_t _errorCode_type;
  _errorCode_type errorCode;

   typedef boost::array<uint16_t, 8>  _freqMeasVal_type;
  _freqMeasVal_type freqMeasVal;

   typedef uint32_t _reserved_type;
  _reserved_type reserved;

   typedef uint32_t _timeStamp_type;
  _timeStamp_type timeStamp;





  typedef boost::shared_ptr< ::radar_msgs::RlMonDccClkFreqRep_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::radar_msgs::RlMonDccClkFreqRep_<ContainerAllocator> const> ConstPtr;

}; // struct RlMonDccClkFreqRep_

typedef ::radar_msgs::RlMonDccClkFreqRep_<std::allocator<void> > RlMonDccClkFreqRep;

typedef boost::shared_ptr< ::radar_msgs::RlMonDccClkFreqRep > RlMonDccClkFreqRepPtr;
typedef boost::shared_ptr< ::radar_msgs::RlMonDccClkFreqRep const> RlMonDccClkFreqRepConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::radar_msgs::RlMonDccClkFreqRep_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::radar_msgs::RlMonDccClkFreqRep_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::radar_msgs::RlMonDccClkFreqRep_<ContainerAllocator1> & lhs, const ::radar_msgs::RlMonDccClkFreqRep_<ContainerAllocator2> & rhs)
{
  return lhs.statusFlags == rhs.statusFlags &&
    lhs.errorCode == rhs.errorCode &&
    lhs.freqMeasVal == rhs.freqMeasVal &&
    lhs.reserved == rhs.reserved &&
    lhs.timeStamp == rhs.timeStamp;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::radar_msgs::RlMonDccClkFreqRep_<ContainerAllocator1> & lhs, const ::radar_msgs::RlMonDccClkFreqRep_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace radar_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::radar_msgs::RlMonDccClkFreqRep_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::radar_msgs::RlMonDccClkFreqRep_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::radar_msgs::RlMonDccClkFreqRep_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::radar_msgs::RlMonDccClkFreqRep_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::radar_msgs::RlMonDccClkFreqRep_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::radar_msgs::RlMonDccClkFreqRep_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::radar_msgs::RlMonDccClkFreqRep_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c8d68e78d1b1bd39b7cf6ab5fdeb43e2";
  }

  static const char* value(const ::radar_msgs::RlMonDccClkFreqRep_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc8d68e78d1b1bd39ULL;
  static const uint64_t static_value2 = 0xb7cf6ab5fdeb43e2ULL;
};

template<class ContainerAllocator>
struct DataType< ::radar_msgs::RlMonDccClkFreqRep_<ContainerAllocator> >
{
  static const char* value()
  {
    return "radar_msgs/RlMonDccClkFreqRep";
  }

  static const char* value(const ::radar_msgs::RlMonDccClkFreqRep_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::radar_msgs::RlMonDccClkFreqRep_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16      statusFlags\n"
"uint16      errorCode\n"
"uint16[8]   freqMeasVal\n"
"uint32      reserved\n"
"uint32      timeStamp\n"
;
  }

  static const char* value(const ::radar_msgs::RlMonDccClkFreqRep_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::radar_msgs::RlMonDccClkFreqRep_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.statusFlags);
      stream.next(m.errorCode);
      stream.next(m.freqMeasVal);
      stream.next(m.reserved);
      stream.next(m.timeStamp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RlMonDccClkFreqRep_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::radar_msgs::RlMonDccClkFreqRep_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::radar_msgs::RlMonDccClkFreqRep_<ContainerAllocator>& v)
  {
    s << indent << "statusFlags: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.statusFlags);
    s << indent << "errorCode: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.errorCode);
    s << indent << "freqMeasVal[]" << std::endl;
    for (size_t i = 0; i < v.freqMeasVal.size(); ++i)
    {
      s << indent << "  freqMeasVal[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.freqMeasVal[i]);
    }
    s << indent << "reserved: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.reserved);
    s << indent << "timeStamp: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.timeStamp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RADAR_MSGS_MESSAGE_RLMONDCCCLKFREQREP_H
