// Generated by gencpp from file radar_msgs/SystemInfo.msg
// DO NOT EDIT!


#ifndef RADAR_MSGS_MESSAGE_SYSTEMINFO_H
#define RADAR_MSGS_MESSAGE_SYSTEMINFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace radar_msgs
{
template <class ContainerAllocator>
struct SystemInfo_
{
  typedef SystemInfo_<ContainerAllocator> Type;

  SystemInfo_()
    : header()
    , productCode()
    , productVersion()
    , compileDate()
    , compileTime()
    , reserve()  {
      productCode.assign(0);

      productVersion.assign(0);

      compileDate.assign(0);

      compileTime.assign(0);

      reserve.assign(0);
  }
  SystemInfo_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , productCode()
    , productVersion()
    , compileDate()
    , compileTime()
    , reserve()  {
  (void)_alloc;
      productCode.assign(0);

      productVersion.assign(0);

      compileDate.assign(0);

      compileTime.assign(0);

      reserve.assign(0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef boost::array<uint8_t, 16>  _productCode_type;
  _productCode_type productCode;

   typedef boost::array<uint8_t, 16>  _productVersion_type;
  _productVersion_type productVersion;

   typedef boost::array<uint8_t, 12>  _compileDate_type;
  _compileDate_type compileDate;

   typedef boost::array<uint8_t, 16>  _compileTime_type;
  _compileTime_type compileTime;

   typedef boost::array<uint8_t, 32>  _reserve_type;
  _reserve_type reserve;





  typedef boost::shared_ptr< ::radar_msgs::SystemInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::radar_msgs::SystemInfo_<ContainerAllocator> const> ConstPtr;

}; // struct SystemInfo_

typedef ::radar_msgs::SystemInfo_<std::allocator<void> > SystemInfo;

typedef boost::shared_ptr< ::radar_msgs::SystemInfo > SystemInfoPtr;
typedef boost::shared_ptr< ::radar_msgs::SystemInfo const> SystemInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::radar_msgs::SystemInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::radar_msgs::SystemInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::radar_msgs::SystemInfo_<ContainerAllocator1> & lhs, const ::radar_msgs::SystemInfo_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.productCode == rhs.productCode &&
    lhs.productVersion == rhs.productVersion &&
    lhs.compileDate == rhs.compileDate &&
    lhs.compileTime == rhs.compileTime &&
    lhs.reserve == rhs.reserve;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::radar_msgs::SystemInfo_<ContainerAllocator1> & lhs, const ::radar_msgs::SystemInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace radar_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::radar_msgs::SystemInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::radar_msgs::SystemInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::radar_msgs::SystemInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::radar_msgs::SystemInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::radar_msgs::SystemInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::radar_msgs::SystemInfo_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::radar_msgs::SystemInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2bef89192e7f73b8458e893ef8d30db1";
  }

  static const char* value(const ::radar_msgs::SystemInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2bef89192e7f73b8ULL;
  static const uint64_t static_value2 = 0x458e893ef8d30db1ULL;
};

template<class ContainerAllocator>
struct DataType< ::radar_msgs::SystemInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "radar_msgs/SystemInfo";
  }

  static const char* value(const ::radar_msgs::SystemInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::radar_msgs::SystemInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header               # Includes measurement timestamp and coordinate frame.\n"
"char[16] productCode            # productCode\n"
"char[16] productVersion         # productVersion\n"
"char[12] compileDate            # compileDate\n"
"char[16] compileTime            # compileTime\n"
"char[32] reserve                # reserve   \n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::radar_msgs::SystemInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::radar_msgs::SystemInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.productCode);
      stream.next(m.productVersion);
      stream.next(m.compileDate);
      stream.next(m.compileTime);
      stream.next(m.reserve);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SystemInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::radar_msgs::SystemInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::radar_msgs::SystemInfo_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "productCode[]" << std::endl;
    for (size_t i = 0; i < v.productCode.size(); ++i)
    {
      s << indent << "  productCode[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.productCode[i]);
    }
    s << indent << "productVersion[]" << std::endl;
    for (size_t i = 0; i < v.productVersion.size(); ++i)
    {
      s << indent << "  productVersion[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.productVersion[i]);
    }
    s << indent << "compileDate[]" << std::endl;
    for (size_t i = 0; i < v.compileDate.size(); ++i)
    {
      s << indent << "  compileDate[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.compileDate[i]);
    }
    s << indent << "compileTime[]" << std::endl;
    for (size_t i = 0; i < v.compileTime.size(); ++i)
    {
      s << indent << "  compileTime[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.compileTime[i]);
    }
    s << indent << "reserve[]" << std::endl;
    for (size_t i = 0; i < v.reserve.size(); ++i)
    {
      s << indent << "  reserve[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.reserve[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // RADAR_MSGS_MESSAGE_SYSTEMINFO_H
