// Generated by gencpp from file radar_msgs/SystemStatsheap.msg
// DO NOT EDIT!


#ifndef RADAR_MSGS_MESSAGE_SYSTEMSTATSHEAP_H
#define RADAR_MSGS_MESSAGE_SYSTEMSTATSHEAP_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace radar_msgs
{
template <class ContainerAllocator>
struct SystemStatsheap_
{
  typedef SystemStatsheap_<ContainerAllocator> Type;

  SystemStatsheap_()
    : heapSize(0)
    , freeSize(0)  {
    }
  SystemStatsheap_(const ContainerAllocator& _alloc)
    : heapSize(0)
    , freeSize(0)  {
  (void)_alloc;
    }



   typedef uint32_t _heapSize_type;
  _heapSize_type heapSize;

   typedef uint32_t _freeSize_type;
  _freeSize_type freeSize;





  typedef boost::shared_ptr< ::radar_msgs::SystemStatsheap_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::radar_msgs::SystemStatsheap_<ContainerAllocator> const> ConstPtr;

}; // struct SystemStatsheap_

typedef ::radar_msgs::SystemStatsheap_<std::allocator<void> > SystemStatsheap;

typedef boost::shared_ptr< ::radar_msgs::SystemStatsheap > SystemStatsheapPtr;
typedef boost::shared_ptr< ::radar_msgs::SystemStatsheap const> SystemStatsheapConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::radar_msgs::SystemStatsheap_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::radar_msgs::SystemStatsheap_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::radar_msgs::SystemStatsheap_<ContainerAllocator1> & lhs, const ::radar_msgs::SystemStatsheap_<ContainerAllocator2> & rhs)
{
  return lhs.heapSize == rhs.heapSize &&
    lhs.freeSize == rhs.freeSize;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::radar_msgs::SystemStatsheap_<ContainerAllocator1> & lhs, const ::radar_msgs::SystemStatsheap_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace radar_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::radar_msgs::SystemStatsheap_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::radar_msgs::SystemStatsheap_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::radar_msgs::SystemStatsheap_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::radar_msgs::SystemStatsheap_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::radar_msgs::SystemStatsheap_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::radar_msgs::SystemStatsheap_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::radar_msgs::SystemStatsheap_<ContainerAllocator> >
{
  static const char* value()
  {
    return "03640949b9fee0e6971efd5dfb6ef3a2";
  }

  static const char* value(const ::radar_msgs::SystemStatsheap_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x03640949b9fee0e6ULL;
  static const uint64_t static_value2 = 0x971efd5dfb6ef3a2ULL;
};

template<class ContainerAllocator>
struct DataType< ::radar_msgs::SystemStatsheap_<ContainerAllocator> >
{
  static const char* value()
  {
    return "radar_msgs/SystemStatsheap";
  }

  static const char* value(const ::radar_msgs::SystemStatsheap_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::radar_msgs::SystemStatsheap_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Header header               # Includes measurement timestamp and coordinate frame.\n"
"uint32       heapSize\n"
"uint32       freeSize\n"
;
  }

  static const char* value(const ::radar_msgs::SystemStatsheap_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::radar_msgs::SystemStatsheap_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.heapSize);
      stream.next(m.freeSize);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SystemStatsheap_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::radar_msgs::SystemStatsheap_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::radar_msgs::SystemStatsheap_<ContainerAllocator>& v)
  {
    s << indent << "heapSize: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.heapSize);
    s << indent << "freeSize: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.freeSize);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RADAR_MSGS_MESSAGE_SYSTEMSTATSHEAP_H
