// Generated by gencpp from file radar_msgs/SystemStatsLoad.msg
// DO NOT EDIT!


#ifndef RADAR_MSGS_MESSAGE_SYSTEMSTATSLOAD_H
#define RADAR_MSGS_MESSAGE_SYSTEMSTATSLOAD_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace radar_msgs
{
template <class ContainerAllocator>
struct SystemStatsLoad_
{
  typedef SystemStatsLoad_<ContainerAllocator> Type;

  SystemStatsLoad_()
    : loadValue(0.0)  {
    }
  SystemStatsLoad_(const ContainerAllocator& _alloc)
    : loadValue(0.0)  {
  (void)_alloc;
    }



   typedef float _loadValue_type;
  _loadValue_type loadValue;





  typedef boost::shared_ptr< ::radar_msgs::SystemStatsLoad_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::radar_msgs::SystemStatsLoad_<ContainerAllocator> const> ConstPtr;

}; // struct SystemStatsLoad_

typedef ::radar_msgs::SystemStatsLoad_<std::allocator<void> > SystemStatsLoad;

typedef boost::shared_ptr< ::radar_msgs::SystemStatsLoad > SystemStatsLoadPtr;
typedef boost::shared_ptr< ::radar_msgs::SystemStatsLoad const> SystemStatsLoadConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::radar_msgs::SystemStatsLoad_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::radar_msgs::SystemStatsLoad_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::radar_msgs::SystemStatsLoad_<ContainerAllocator1> & lhs, const ::radar_msgs::SystemStatsLoad_<ContainerAllocator2> & rhs)
{
  return lhs.loadValue == rhs.loadValue;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::radar_msgs::SystemStatsLoad_<ContainerAllocator1> & lhs, const ::radar_msgs::SystemStatsLoad_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace radar_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::radar_msgs::SystemStatsLoad_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::radar_msgs::SystemStatsLoad_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::radar_msgs::SystemStatsLoad_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::radar_msgs::SystemStatsLoad_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::radar_msgs::SystemStatsLoad_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::radar_msgs::SystemStatsLoad_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::radar_msgs::SystemStatsLoad_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fd202161f3eaed8a4375480b6f4d9bb3";
  }

  static const char* value(const ::radar_msgs::SystemStatsLoad_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfd202161f3eaed8aULL;
  static const uint64_t static_value2 = 0x4375480b6f4d9bb3ULL;
};

template<class ContainerAllocator>
struct DataType< ::radar_msgs::SystemStatsLoad_<ContainerAllocator> >
{
  static const char* value()
  {
    return "radar_msgs/SystemStatsLoad";
  }

  static const char* value(const ::radar_msgs::SystemStatsLoad_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::radar_msgs::SystemStatsLoad_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Header header               # Includes measurement timestamp and coordinate frame.\n"
"# uint32      integerValue\n"
"# uint32      fractionalValue\n"
"float32     loadValue\n"
;
  }

  static const char* value(const ::radar_msgs::SystemStatsLoad_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::radar_msgs::SystemStatsLoad_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.loadValue);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SystemStatsLoad_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::radar_msgs::SystemStatsLoad_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::radar_msgs::SystemStatsLoad_<ContainerAllocator>& v)
  {
    s << indent << "loadValue: ";
    Printer<float>::stream(s, indent + "  ", v.loadValue);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RADAR_MSGS_MESSAGE_SYSTEMSTATSLOAD_H
