// Generated by gencpp from file radar_msgs/SystemStateTemp.msg
// DO NOT EDIT!


#ifndef RADAR_MSGS_MESSAGE_SYSTEMSTATETEMP_H
#define RADAR_MSGS_MESSAGE_SYSTEMSTATETEMP_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace radar_msgs
{
template <class ContainerAllocator>
struct SystemStateTemp_
{
  typedef SystemStateTemp_<ContainerAllocator> Type;

  SystemStateTemp_()
    : minTemp(0.0)
    , maxTemp(0.0)  {
    }
  SystemStateTemp_(const ContainerAllocator& _alloc)
    : minTemp(0.0)
    , maxTemp(0.0)  {
  (void)_alloc;
    }



   typedef float _minTemp_type;
  _minTemp_type minTemp;

   typedef float _maxTemp_type;
  _maxTemp_type maxTemp;





  typedef boost::shared_ptr< ::radar_msgs::SystemStateTemp_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::radar_msgs::SystemStateTemp_<ContainerAllocator> const> ConstPtr;

}; // struct SystemStateTemp_

typedef ::radar_msgs::SystemStateTemp_<std::allocator<void> > SystemStateTemp;

typedef boost::shared_ptr< ::radar_msgs::SystemStateTemp > SystemStateTempPtr;
typedef boost::shared_ptr< ::radar_msgs::SystemStateTemp const> SystemStateTempConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::radar_msgs::SystemStateTemp_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::radar_msgs::SystemStateTemp_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::radar_msgs::SystemStateTemp_<ContainerAllocator1> & lhs, const ::radar_msgs::SystemStateTemp_<ContainerAllocator2> & rhs)
{
  return lhs.minTemp == rhs.minTemp &&
    lhs.maxTemp == rhs.maxTemp;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::radar_msgs::SystemStateTemp_<ContainerAllocator1> & lhs, const ::radar_msgs::SystemStateTemp_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace radar_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::radar_msgs::SystemStateTemp_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::radar_msgs::SystemStateTemp_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::radar_msgs::SystemStateTemp_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::radar_msgs::SystemStateTemp_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::radar_msgs::SystemStateTemp_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::radar_msgs::SystemStateTemp_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::radar_msgs::SystemStateTemp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "84095672e2b3817830f10d33f98fc691";
  }

  static const char* value(const ::radar_msgs::SystemStateTemp_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x84095672e2b38178ULL;
  static const uint64_t static_value2 = 0x30f10d33f98fc691ULL;
};

template<class ContainerAllocator>
struct DataType< ::radar_msgs::SystemStateTemp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "radar_msgs/SystemStateTemp";
  }

  static const char* value(const ::radar_msgs::SystemStateTemp_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::radar_msgs::SystemStateTemp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Header header               # Includes measurement timestamp and coordinate frame.\n"
"float32       minTemp\n"
"float32       maxTemp\n"
;
  }

  static const char* value(const ::radar_msgs::SystemStateTemp_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::radar_msgs::SystemStateTemp_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.minTemp);
      stream.next(m.maxTemp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SystemStateTemp_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::radar_msgs::SystemStateTemp_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::radar_msgs::SystemStateTemp_<ContainerAllocator>& v)
  {
    s << indent << "minTemp: ";
    Printer<float>::stream(s, indent + "  ", v.minTemp);
    s << indent << "maxTemp: ";
    Printer<float>::stream(s, indent + "  ", v.maxTemp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RADAR_MSGS_MESSAGE_SYSTEMSTATETEMP_H
