// Generated by gencpp from file radar_msgs/SystemStateWoPtp.msg
// DO NOT EDIT!


#ifndef RADAR_MSGS_MESSAGE_SYSTEMSTATEWOPTP_H
#define RADAR_MSGS_MESSAGE_SYSTEMSTATEWOPTP_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <radar_msgs/SystemStateTemp.h>
#include <radar_msgs/SystemStatsLoad.h>
#include <radar_msgs/SystemStatsheap.h>
#include <radar_msgs/SystemStatsheapArr.h>

namespace radar_msgs
{
template <class ContainerAllocator>
struct SystemStateWoPtp_
{
  typedef SystemStateWoPtp_<ContainerAllocator> Type;

  SystemStateWoPtp_()
    : header()
    , temp()
    , voltage()
    , freq()
    , load()
    , primaryHeap()
    , heapArr()  {
      voltage.assign(0.0);

      freq.assign(0);
  }
  SystemStateWoPtp_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , temp()
    , voltage()
    , freq()
    , load()
    , primaryHeap()
    , heapArr()  {
  (void)_alloc;
      temp.assign( ::radar_msgs::SystemStateTemp_<ContainerAllocator> (_alloc));

      voltage.assign(0.0);

      freq.assign(0);

      load.assign( ::radar_msgs::SystemStatsLoad_<ContainerAllocator> (_alloc));

      primaryHeap.assign( ::radar_msgs::SystemStatsheap_<ContainerAllocator> (_alloc));

      heapArr.assign( ::radar_msgs::SystemStatsheapArr_<ContainerAllocator> (_alloc));
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef boost::array< ::radar_msgs::SystemStateTemp_<ContainerAllocator> , 5>  _temp_type;
  _temp_type temp;

   typedef boost::array<float, 5>  _voltage_type;
  _voltage_type voltage;

   typedef boost::array<uint32_t, 10>  _freq_type;
  _freq_type freq;

   typedef boost::array< ::radar_msgs::SystemStatsLoad_<ContainerAllocator> , 10>  _load_type;
  _load_type load;

   typedef boost::array< ::radar_msgs::SystemStatsheap_<ContainerAllocator> , 4>  _primaryHeap_type;
  _primaryHeap_type primaryHeap;

   typedef boost::array< ::radar_msgs::SystemStatsheapArr_<ContainerAllocator> , 9>  _heapArr_type;
  _heapArr_type heapArr;





  typedef boost::shared_ptr< ::radar_msgs::SystemStateWoPtp_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::radar_msgs::SystemStateWoPtp_<ContainerAllocator> const> ConstPtr;

}; // struct SystemStateWoPtp_

typedef ::radar_msgs::SystemStateWoPtp_<std::allocator<void> > SystemStateWoPtp;

typedef boost::shared_ptr< ::radar_msgs::SystemStateWoPtp > SystemStateWoPtpPtr;
typedef boost::shared_ptr< ::radar_msgs::SystemStateWoPtp const> SystemStateWoPtpConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::radar_msgs::SystemStateWoPtp_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::radar_msgs::SystemStateWoPtp_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::radar_msgs::SystemStateWoPtp_<ContainerAllocator1> & lhs, const ::radar_msgs::SystemStateWoPtp_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.temp == rhs.temp &&
    lhs.voltage == rhs.voltage &&
    lhs.freq == rhs.freq &&
    lhs.load == rhs.load &&
    lhs.primaryHeap == rhs.primaryHeap &&
    lhs.heapArr == rhs.heapArr;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::radar_msgs::SystemStateWoPtp_<ContainerAllocator1> & lhs, const ::radar_msgs::SystemStateWoPtp_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace radar_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::radar_msgs::SystemStateWoPtp_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::radar_msgs::SystemStateWoPtp_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::radar_msgs::SystemStateWoPtp_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::radar_msgs::SystemStateWoPtp_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::radar_msgs::SystemStateWoPtp_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::radar_msgs::SystemStateWoPtp_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::radar_msgs::SystemStateWoPtp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d2347aeac5c0a8642643083e21097b3a";
  }

  static const char* value(const ::radar_msgs::SystemStateWoPtp_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd2347aeac5c0a864ULL;
  static const uint64_t static_value2 = 0x2643083e21097b3aULL;
};

template<class ContainerAllocator>
struct DataType< ::radar_msgs::SystemStateWoPtp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "radar_msgs/SystemStateWoPtp";
  }

  static const char* value(const ::radar_msgs::SystemStateWoPtp_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::radar_msgs::SystemStateWoPtp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header                      header  # Includes measurement timestamp and coordinate frame.\n"
"SystemStateTemp[5]          temp\n"
"float32[5]                  voltage\n"
"uint32[10]                  freq\n"
"SystemStatsLoad[10]         load\n"
"SystemStatsheap[4]          primaryHeap\n"
"SystemStatsheapArr[9]       heapArr\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: radar_msgs/SystemStateTemp\n"
"# Header header               # Includes measurement timestamp and coordinate frame.\n"
"float32       minTemp\n"
"float32       maxTemp\n"
"================================================================================\n"
"MSG: radar_msgs/SystemStatsLoad\n"
"# Header header               # Includes measurement timestamp and coordinate frame.\n"
"# uint32      integerValue\n"
"# uint32      fractionalValue\n"
"float32     loadValue\n"
"================================================================================\n"
"MSG: radar_msgs/SystemStatsheap\n"
"# Header header               # Includes measurement timestamp and coordinate frame.\n"
"uint32       heapSize\n"
"uint32       freeSize\n"
"================================================================================\n"
"MSG: radar_msgs/SystemStatsheapArr\n"
"# Header header           # Includes measurement timestamp and coordinate frame.\n"
"SystemStatsheap[2]     heap\n"
;
  }

  static const char* value(const ::radar_msgs::SystemStateWoPtp_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::radar_msgs::SystemStateWoPtp_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.temp);
      stream.next(m.voltage);
      stream.next(m.freq);
      stream.next(m.load);
      stream.next(m.primaryHeap);
      stream.next(m.heapArr);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SystemStateWoPtp_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::radar_msgs::SystemStateWoPtp_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::radar_msgs::SystemStateWoPtp_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "temp[]" << std::endl;
    for (size_t i = 0; i < v.temp.size(); ++i)
    {
      s << indent << "  temp[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::radar_msgs::SystemStateTemp_<ContainerAllocator> >::stream(s, indent + "    ", v.temp[i]);
    }
    s << indent << "voltage[]" << std::endl;
    for (size_t i = 0; i < v.voltage.size(); ++i)
    {
      s << indent << "  voltage[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.voltage[i]);
    }
    s << indent << "freq[]" << std::endl;
    for (size_t i = 0; i < v.freq.size(); ++i)
    {
      s << indent << "  freq[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.freq[i]);
    }
    s << indent << "load[]" << std::endl;
    for (size_t i = 0; i < v.load.size(); ++i)
    {
      s << indent << "  load[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::radar_msgs::SystemStatsLoad_<ContainerAllocator> >::stream(s, indent + "    ", v.load[i]);
    }
    s << indent << "primaryHeap[]" << std::endl;
    for (size_t i = 0; i < v.primaryHeap.size(); ++i)
    {
      s << indent << "  primaryHeap[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::radar_msgs::SystemStatsheap_<ContainerAllocator> >::stream(s, indent + "    ", v.primaryHeap[i]);
    }
    s << indent << "heapArr[]" << std::endl;
    for (size_t i = 0; i < v.heapArr.size(); ++i)
    {
      s << indent << "  heapArr[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::radar_msgs::SystemStatsheapArr_<ContainerAllocator> >::stream(s, indent + "    ", v.heapArr[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // RADAR_MSGS_MESSAGE_SYSTEMSTATEWOPTP_H
