// Generated by gencpp from file radar_msgs/TrackingObj.msg
// DO NOT EDIT!


#ifndef RADAR_MSGS_MESSAGE_TRACKINGOBJ_H
#define RADAR_MSGS_MESSAGE_TRACKINGOBJ_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace radar_msgs
{
template <class ContainerAllocator>
struct TrackingObj_
{
  typedef TrackingObj_<ContainerAllocator> Type;

  TrackingObj_()
    : header()
    , radarID(0)
    , frameCnt(0)
    , objNum(0)
    , object_ID()
    , age()
    , measurement_status()
    , motion_state()
    , existance_confidence()
    , position_x()
    , position_y()
    , position_z()
    , velocity_x()
    , velocity_y()
    , velocity_z()
    , acceleration_x()
    , acceleration_y()
    , acceleration_z()
    , v2ground_x()
    , v2ground_y()
    , v2ground_z()
    , orientation()
    , type()
    , car_confidence()
    , bike_confidence()
    , ped_confidence()
    , truck_confidence()
    , signboard_confidence()
    , ground_confidence()
    , obstacle_confidence()
    , length()
    , width()
    , height()
    , od_process_time()
    , Reserved_B()
    , Reserved_C()
    , Reserved_D()  {
    }
  TrackingObj_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , radarID(0)
    , frameCnt(0)
    , objNum(0)
    , object_ID(_alloc)
    , age(_alloc)
    , measurement_status(_alloc)
    , motion_state(_alloc)
    , existance_confidence(_alloc)
    , position_x(_alloc)
    , position_y(_alloc)
    , position_z(_alloc)
    , velocity_x(_alloc)
    , velocity_y(_alloc)
    , velocity_z(_alloc)
    , acceleration_x(_alloc)
    , acceleration_y(_alloc)
    , acceleration_z(_alloc)
    , v2ground_x(_alloc)
    , v2ground_y(_alloc)
    , v2ground_z(_alloc)
    , orientation(_alloc)
    , type(_alloc)
    , car_confidence(_alloc)
    , bike_confidence(_alloc)
    , ped_confidence(_alloc)
    , truck_confidence(_alloc)
    , signboard_confidence(_alloc)
    , ground_confidence(_alloc)
    , obstacle_confidence(_alloc)
    , length(_alloc)
    , width(_alloc)
    , height(_alloc)
    , od_process_time(_alloc)
    , Reserved_B(_alloc)
    , Reserved_C(_alloc)
    , Reserved_D(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _radarID_type;
  _radarID_type radarID;

   typedef uint32_t _frameCnt_type;
  _frameCnt_type frameCnt;

   typedef uint32_t _objNum_type;
  _objNum_type objNum;

   typedef std::vector<uint32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint32_t>> _object_ID_type;
  _object_ID_type object_ID;

   typedef std::vector<uint16_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint16_t>> _age_type;
  _age_type age;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _measurement_status_type;
  _measurement_status_type measurement_status;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _motion_state_type;
  _motion_state_type motion_state;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _existance_confidence_type;
  _existance_confidence_type existance_confidence;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _position_x_type;
  _position_x_type position_x;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _position_y_type;
  _position_y_type position_y;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _position_z_type;
  _position_z_type position_z;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _velocity_x_type;
  _velocity_x_type velocity_x;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _velocity_y_type;
  _velocity_y_type velocity_y;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _velocity_z_type;
  _velocity_z_type velocity_z;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _acceleration_x_type;
  _acceleration_x_type acceleration_x;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _acceleration_y_type;
  _acceleration_y_type acceleration_y;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _acceleration_z_type;
  _acceleration_z_type acceleration_z;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _v2ground_x_type;
  _v2ground_x_type v2ground_x;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _v2ground_y_type;
  _v2ground_y_type v2ground_y;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _v2ground_z_type;
  _v2ground_z_type v2ground_z;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _orientation_type;
  _orientation_type orientation;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _type_type;
  _type_type type;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _car_confidence_type;
  _car_confidence_type car_confidence;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _bike_confidence_type;
  _bike_confidence_type bike_confidence;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _ped_confidence_type;
  _ped_confidence_type ped_confidence;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _truck_confidence_type;
  _truck_confidence_type truck_confidence;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _signboard_confidence_type;
  _signboard_confidence_type signboard_confidence;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _ground_confidence_type;
  _ground_confidence_type ground_confidence;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _obstacle_confidence_type;
  _obstacle_confidence_type obstacle_confidence;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _length_type;
  _length_type length;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _width_type;
  _width_type width;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _height_type;
  _height_type height;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _od_process_time_type;
  _od_process_time_type od_process_time;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _Reserved_B_type;
  _Reserved_B_type Reserved_B;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _Reserved_C_type;
  _Reserved_C_type Reserved_C;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _Reserved_D_type;
  _Reserved_D_type Reserved_D;





  typedef boost::shared_ptr< ::radar_msgs::TrackingObj_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::radar_msgs::TrackingObj_<ContainerAllocator> const> ConstPtr;

}; // struct TrackingObj_

typedef ::radar_msgs::TrackingObj_<std::allocator<void> > TrackingObj;

typedef boost::shared_ptr< ::radar_msgs::TrackingObj > TrackingObjPtr;
typedef boost::shared_ptr< ::radar_msgs::TrackingObj const> TrackingObjConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::radar_msgs::TrackingObj_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::radar_msgs::TrackingObj_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::radar_msgs::TrackingObj_<ContainerAllocator1> & lhs, const ::radar_msgs::TrackingObj_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.radarID == rhs.radarID &&
    lhs.frameCnt == rhs.frameCnt &&
    lhs.objNum == rhs.objNum &&
    lhs.object_ID == rhs.object_ID &&
    lhs.age == rhs.age &&
    lhs.measurement_status == rhs.measurement_status &&
    lhs.motion_state == rhs.motion_state &&
    lhs.existance_confidence == rhs.existance_confidence &&
    lhs.position_x == rhs.position_x &&
    lhs.position_y == rhs.position_y &&
    lhs.position_z == rhs.position_z &&
    lhs.velocity_x == rhs.velocity_x &&
    lhs.velocity_y == rhs.velocity_y &&
    lhs.velocity_z == rhs.velocity_z &&
    lhs.acceleration_x == rhs.acceleration_x &&
    lhs.acceleration_y == rhs.acceleration_y &&
    lhs.acceleration_z == rhs.acceleration_z &&
    lhs.v2ground_x == rhs.v2ground_x &&
    lhs.v2ground_y == rhs.v2ground_y &&
    lhs.v2ground_z == rhs.v2ground_z &&
    lhs.orientation == rhs.orientation &&
    lhs.type == rhs.type &&
    lhs.car_confidence == rhs.car_confidence &&
    lhs.bike_confidence == rhs.bike_confidence &&
    lhs.ped_confidence == rhs.ped_confidence &&
    lhs.truck_confidence == rhs.truck_confidence &&
    lhs.signboard_confidence == rhs.signboard_confidence &&
    lhs.ground_confidence == rhs.ground_confidence &&
    lhs.obstacle_confidence == rhs.obstacle_confidence &&
    lhs.length == rhs.length &&
    lhs.width == rhs.width &&
    lhs.height == rhs.height &&
    lhs.od_process_time == rhs.od_process_time &&
    lhs.Reserved_B == rhs.Reserved_B &&
    lhs.Reserved_C == rhs.Reserved_C &&
    lhs.Reserved_D == rhs.Reserved_D;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::radar_msgs::TrackingObj_<ContainerAllocator1> & lhs, const ::radar_msgs::TrackingObj_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace radar_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::radar_msgs::TrackingObj_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::radar_msgs::TrackingObj_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::radar_msgs::TrackingObj_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::radar_msgs::TrackingObj_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::radar_msgs::TrackingObj_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::radar_msgs::TrackingObj_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::radar_msgs::TrackingObj_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4472a3692f65b382d654abf0488be272";
  }

  static const char* value(const ::radar_msgs::TrackingObj_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4472a3692f65b382ULL;
  static const uint64_t static_value2 = 0xd654abf0488be272ULL;
};

template<class ContainerAllocator>
struct DataType< ::radar_msgs::TrackingObj_<ContainerAllocator> >
{
  static const char* value()
  {
    return "radar_msgs/TrackingObj";
  }

  static const char* value(const ::radar_msgs::TrackingObj_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::radar_msgs::TrackingObj_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header    header               # Includes measurement timestamp and coordinate frame.\n"
"uint32    radarID              # radar ID\n"
"uint32    frameCnt             # frame cnt in radar\n"
"uint32    objNum               # object number of this frame\n"
"uint32[]  object_ID            # object ID\n"
"uint16[]  age                  # total frames from the object occurs\n"
"uint8[]   measurement_status   # track status (0: measured; 1: new; 2: predicted)\n"
"uint8[]   motion_state         # movement state ( 0: static; 1: dynamic)\n"
"uint8[]   existance_confidence # existance confidence\n"
"float32[] position_x           # x value of central point\n"
"float32[] position_y           # y value of central point\n"
"float32[] position_z           # z value of central point\n"
"float32[] velocity_x           # relative velocity of x orientation\n"
"float32[] velocity_y           # relative velocity of y orientation\n"
"float32[] velocity_z           # relative velocity of z orientation\n"
"float32[] acceleration_x       # relative acceleration of x orientation\n"
"float32[] acceleration_y       # relative acceleration of y orientation\n"
"float32[] acceleration_z       # relative acceleration of z orientation\n"
"float32[] v2ground_x           # velocity towards ground of x orientation\n"
"float32[] v2ground_y           # velocity towards ground of y orientation\n"
"float32[] v2ground_z           # velocity towards ground of z orientation\n"
"float32[] orientation          # yaw, unit: degree\n"
"uint8[]   type                 # object type (（0: car 小型汽车; 1: bike 两轮车; 2: pedestrian 行人; 3: truck 大车; 4: signboard 高空物; 5: ground 地面; 6: obstacle 静态障碍物)\n"
"uint8[]  car_confidence       # car confidence\n"
"uint8[]   bike_confidence      # bike confidence\n"
"uint8[]   ped_confidence       # pedestrian confidence\n"
"uint8[]   truck_confidence     # truck confidence\n"
"uint8[]   signboard_confidence # signboard confidence\n"
"uint8[]   ground_confidence    # ground confidence\n"
"uint8[]   obstacle_confidence  # obstacle confidence\n"
"float32[] length               # length\n"
"float32[] width                # width\n"
"float32[] height               # height\n"
"float32[] od_process_time      # EnrollPtsNum\n"
"float32[] Reserved_B           # NearestPtsX\n"
"float32[] Reserved_C           # NearestPtsY\n"
"float32[] Reserved_D           # NearestPtsZ\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::radar_msgs::TrackingObj_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::radar_msgs::TrackingObj_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.radarID);
      stream.next(m.frameCnt);
      stream.next(m.objNum);
      stream.next(m.object_ID);
      stream.next(m.age);
      stream.next(m.measurement_status);
      stream.next(m.motion_state);
      stream.next(m.existance_confidence);
      stream.next(m.position_x);
      stream.next(m.position_y);
      stream.next(m.position_z);
      stream.next(m.velocity_x);
      stream.next(m.velocity_y);
      stream.next(m.velocity_z);
      stream.next(m.acceleration_x);
      stream.next(m.acceleration_y);
      stream.next(m.acceleration_z);
      stream.next(m.v2ground_x);
      stream.next(m.v2ground_y);
      stream.next(m.v2ground_z);
      stream.next(m.orientation);
      stream.next(m.type);
      stream.next(m.car_confidence);
      stream.next(m.bike_confidence);
      stream.next(m.ped_confidence);
      stream.next(m.truck_confidence);
      stream.next(m.signboard_confidence);
      stream.next(m.ground_confidence);
      stream.next(m.obstacle_confidence);
      stream.next(m.length);
      stream.next(m.width);
      stream.next(m.height);
      stream.next(m.od_process_time);
      stream.next(m.Reserved_B);
      stream.next(m.Reserved_C);
      stream.next(m.Reserved_D);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TrackingObj_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::radar_msgs::TrackingObj_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::radar_msgs::TrackingObj_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "radarID: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.radarID);
    s << indent << "frameCnt: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.frameCnt);
    s << indent << "objNum: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.objNum);
    s << indent << "object_ID[]" << std::endl;
    for (size_t i = 0; i < v.object_ID.size(); ++i)
    {
      s << indent << "  object_ID[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.object_ID[i]);
    }
    s << indent << "age[]" << std::endl;
    for (size_t i = 0; i < v.age.size(); ++i)
    {
      s << indent << "  age[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.age[i]);
    }
    s << indent << "measurement_status[]" << std::endl;
    for (size_t i = 0; i < v.measurement_status.size(); ++i)
    {
      s << indent << "  measurement_status[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.measurement_status[i]);
    }
    s << indent << "motion_state[]" << std::endl;
    for (size_t i = 0; i < v.motion_state.size(); ++i)
    {
      s << indent << "  motion_state[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.motion_state[i]);
    }
    s << indent << "existance_confidence[]" << std::endl;
    for (size_t i = 0; i < v.existance_confidence.size(); ++i)
    {
      s << indent << "  existance_confidence[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.existance_confidence[i]);
    }
    s << indent << "position_x[]" << std::endl;
    for (size_t i = 0; i < v.position_x.size(); ++i)
    {
      s << indent << "  position_x[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.position_x[i]);
    }
    s << indent << "position_y[]" << std::endl;
    for (size_t i = 0; i < v.position_y.size(); ++i)
    {
      s << indent << "  position_y[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.position_y[i]);
    }
    s << indent << "position_z[]" << std::endl;
    for (size_t i = 0; i < v.position_z.size(); ++i)
    {
      s << indent << "  position_z[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.position_z[i]);
    }
    s << indent << "velocity_x[]" << std::endl;
    for (size_t i = 0; i < v.velocity_x.size(); ++i)
    {
      s << indent << "  velocity_x[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.velocity_x[i]);
    }
    s << indent << "velocity_y[]" << std::endl;
    for (size_t i = 0; i < v.velocity_y.size(); ++i)
    {
      s << indent << "  velocity_y[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.velocity_y[i]);
    }
    s << indent << "velocity_z[]" << std::endl;
    for (size_t i = 0; i < v.velocity_z.size(); ++i)
    {
      s << indent << "  velocity_z[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.velocity_z[i]);
    }
    s << indent << "acceleration_x[]" << std::endl;
    for (size_t i = 0; i < v.acceleration_x.size(); ++i)
    {
      s << indent << "  acceleration_x[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.acceleration_x[i]);
    }
    s << indent << "acceleration_y[]" << std::endl;
    for (size_t i = 0; i < v.acceleration_y.size(); ++i)
    {
      s << indent << "  acceleration_y[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.acceleration_y[i]);
    }
    s << indent << "acceleration_z[]" << std::endl;
    for (size_t i = 0; i < v.acceleration_z.size(); ++i)
    {
      s << indent << "  acceleration_z[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.acceleration_z[i]);
    }
    s << indent << "v2ground_x[]" << std::endl;
    for (size_t i = 0; i < v.v2ground_x.size(); ++i)
    {
      s << indent << "  v2ground_x[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.v2ground_x[i]);
    }
    s << indent << "v2ground_y[]" << std::endl;
    for (size_t i = 0; i < v.v2ground_y.size(); ++i)
    {
      s << indent << "  v2ground_y[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.v2ground_y[i]);
    }
    s << indent << "v2ground_z[]" << std::endl;
    for (size_t i = 0; i < v.v2ground_z.size(); ++i)
    {
      s << indent << "  v2ground_z[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.v2ground_z[i]);
    }
    s << indent << "orientation[]" << std::endl;
    for (size_t i = 0; i < v.orientation.size(); ++i)
    {
      s << indent << "  orientation[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.orientation[i]);
    }
    s << indent << "type[]" << std::endl;
    for (size_t i = 0; i < v.type.size(); ++i)
    {
      s << indent << "  type[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.type[i]);
    }
    s << indent << "car_confidence[]" << std::endl;
    for (size_t i = 0; i < v.car_confidence.size(); ++i)
    {
      s << indent << "  car_confidence[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.car_confidence[i]);
    }
    s << indent << "bike_confidence[]" << std::endl;
    for (size_t i = 0; i < v.bike_confidence.size(); ++i)
    {
      s << indent << "  bike_confidence[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.bike_confidence[i]);
    }
    s << indent << "ped_confidence[]" << std::endl;
    for (size_t i = 0; i < v.ped_confidence.size(); ++i)
    {
      s << indent << "  ped_confidence[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.ped_confidence[i]);
    }
    s << indent << "truck_confidence[]" << std::endl;
    for (size_t i = 0; i < v.truck_confidence.size(); ++i)
    {
      s << indent << "  truck_confidence[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.truck_confidence[i]);
    }
    s << indent << "signboard_confidence[]" << std::endl;
    for (size_t i = 0; i < v.signboard_confidence.size(); ++i)
    {
      s << indent << "  signboard_confidence[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.signboard_confidence[i]);
    }
    s << indent << "ground_confidence[]" << std::endl;
    for (size_t i = 0; i < v.ground_confidence.size(); ++i)
    {
      s << indent << "  ground_confidence[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.ground_confidence[i]);
    }
    s << indent << "obstacle_confidence[]" << std::endl;
    for (size_t i = 0; i < v.obstacle_confidence.size(); ++i)
    {
      s << indent << "  obstacle_confidence[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.obstacle_confidence[i]);
    }
    s << indent << "length[]" << std::endl;
    for (size_t i = 0; i < v.length.size(); ++i)
    {
      s << indent << "  length[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.length[i]);
    }
    s << indent << "width[]" << std::endl;
    for (size_t i = 0; i < v.width.size(); ++i)
    {
      s << indent << "  width[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.width[i]);
    }
    s << indent << "height[]" << std::endl;
    for (size_t i = 0; i < v.height.size(); ++i)
    {
      s << indent << "  height[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.height[i]);
    }
    s << indent << "od_process_time[]" << std::endl;
    for (size_t i = 0; i < v.od_process_time.size(); ++i)
    {
      s << indent << "  od_process_time[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.od_process_time[i]);
    }
    s << indent << "Reserved_B[]" << std::endl;
    for (size_t i = 0; i < v.Reserved_B.size(); ++i)
    {
      s << indent << "  Reserved_B[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.Reserved_B[i]);
    }
    s << indent << "Reserved_C[]" << std::endl;
    for (size_t i = 0; i < v.Reserved_C.size(); ++i)
    {
      s << indent << "  Reserved_C[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.Reserved_C[i]);
    }
    s << indent << "Reserved_D[]" << std::endl;
    for (size_t i = 0; i < v.Reserved_D.size(); ++i)
    {
      s << indent << "  Reserved_D[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.Reserved_D[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // RADAR_MSGS_MESSAGE_TRACKINGOBJ_H
