# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from radar_msgs/InstallInfo.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class InstallInfo(genpy.Message):
  _md5sum = "0c93964ac0c3cc3e143adcb42d14164d"
  _type = "radar_msgs/InstallInfo"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header  header                   # Includes measurement timestamp and coordinate frame.
uint32  radarID                  # radar ID
uint32  frameCnt                 # frame cnt in radar
uint16  sensorPositionInvalidFlags
float32 sensorXPosition             #unit: m
float32 sensorYPosition             #unit: m
float32 sensorZPosition             #unit: m
float32 sensorRollAngle             #unit: degree
float32 sensorPitchAngle            #unit: degree
float32 sensorYawAngle              #unit: degree
float32 azimuthCorrection           #unit: degree
float32 elevationCorrection         #unit: degree
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','radarID','frameCnt','sensorPositionInvalidFlags','sensorXPosition','sensorYPosition','sensorZPosition','sensorRollAngle','sensorPitchAngle','sensorYawAngle','azimuthCorrection','elevationCorrection']
  _slot_types = ['std_msgs/Header','uint32','uint32','uint16','float32','float32','float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,radarID,frameCnt,sensorPositionInvalidFlags,sensorXPosition,sensorYPosition,sensorZPosition,sensorRollAngle,sensorPitchAngle,sensorYawAngle,azimuthCorrection,elevationCorrection

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(InstallInfo, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.radarID is None:
        self.radarID = 0
      if self.frameCnt is None:
        self.frameCnt = 0
      if self.sensorPositionInvalidFlags is None:
        self.sensorPositionInvalidFlags = 0
      if self.sensorXPosition is None:
        self.sensorXPosition = 0.
      if self.sensorYPosition is None:
        self.sensorYPosition = 0.
      if self.sensorZPosition is None:
        self.sensorZPosition = 0.
      if self.sensorRollAngle is None:
        self.sensorRollAngle = 0.
      if self.sensorPitchAngle is None:
        self.sensorPitchAngle = 0.
      if self.sensorYawAngle is None:
        self.sensorYawAngle = 0.
      if self.azimuthCorrection is None:
        self.azimuthCorrection = 0.
      if self.elevationCorrection is None:
        self.elevationCorrection = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.radarID = 0
      self.frameCnt = 0
      self.sensorPositionInvalidFlags = 0
      self.sensorXPosition = 0.
      self.sensorYPosition = 0.
      self.sensorZPosition = 0.
      self.sensorRollAngle = 0.
      self.sensorPitchAngle = 0.
      self.sensorYawAngle = 0.
      self.azimuthCorrection = 0.
      self.elevationCorrection = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2IH8f().pack(_x.radarID, _x.frameCnt, _x.sensorPositionInvalidFlags, _x.sensorXPosition, _x.sensorYPosition, _x.sensorZPosition, _x.sensorRollAngle, _x.sensorPitchAngle, _x.sensorYawAngle, _x.azimuthCorrection, _x.elevationCorrection))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 42
      (_x.radarID, _x.frameCnt, _x.sensorPositionInvalidFlags, _x.sensorXPosition, _x.sensorYPosition, _x.sensorZPosition, _x.sensorRollAngle, _x.sensorPitchAngle, _x.sensorYawAngle, _x.azimuthCorrection, _x.elevationCorrection,) = _get_struct_2IH8f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2IH8f().pack(_x.radarID, _x.frameCnt, _x.sensorPositionInvalidFlags, _x.sensorXPosition, _x.sensorYPosition, _x.sensorZPosition, _x.sensorRollAngle, _x.sensorPitchAngle, _x.sensorYawAngle, _x.azimuthCorrection, _x.elevationCorrection))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 42
      (_x.radarID, _x.frameCnt, _x.sensorPositionInvalidFlags, _x.sensorXPosition, _x.sensorYPosition, _x.sensorZPosition, _x.sensorRollAngle, _x.sensorPitchAngle, _x.sensorYawAngle, _x.azimuthCorrection, _x.elevationCorrection,) = _get_struct_2IH8f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2IH8f = None
def _get_struct_2IH8f():
    global _struct_2IH8f
    if _struct_2IH8f is None:
        _struct_2IH8f = struct.Struct("<2IH8f")
    return _struct_2IH8f
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
