# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from radar_msgs/Od.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class Od(genpy.Message):
  _md5sum = "8abbf365d0b04a773bf2e6d9a6dd7b7b"
  _type = "radar_msgs/Od"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# Header    header               # Includes measurement timestamp and coordinate frame.
uint32    object_ID            # object ID
uint16    age                  # total frames from the object occurs
uint8     measurement_status   # track status (0: measured; 1: new; 2: predicted)
uint8     motion_state         # movement state ( 0: static; 1: dynamic)
uint8     existance_confidence # existance confidence
geometry_msgs/Pose              pose #central position x, y, z; roll=0, pitch=0, yaw to quaternion
geometry_msgs/Vector3           dimensions #length, width, height
geometry_msgs/Twist             velocity
geometry_msgs/Twist             acceleration
geometry_msgs/Twist             v2ground #velocity towards ground of x, y, z orientation
geometry_msgs/Pose              pose_nearest #NearestPts x, y, z
uint8     type                 # object type (（0: car 小型汽车; 1: bike 两轮车; 2: pedestrian 行人; 3: truck 大车; 4: signboard 高空物; 5: ground 地面; 6: obstacle 静态障碍物)
uint8     car_confidence       # car confidence
uint8     bike_confidence      # bike confidence
uint8     ped_confidence       # pedestrian confidence
uint8     truck_confidence     # truck confidence
uint8     signboard_confidence # signboard confidence
uint8     ground_confidence    # ground confidence
uint8     obstacle_confidence  # obstacle confidence
float32   EnrollPtsNum         # EnrollPtsNum
float32   NearestPtsX          # NearestPtsX           
float32   NearestPtsY          # NearestPtsY
float32   NearestPtsZ          # NearestPtsZ
float32   Reserved_D  
uint32    Reserved_E          
uint32    Reserved_F           
int32     Reserved_G           
int32     Reserved_H    
uint16    Reserved_I   
uint16    Reserved_J    
int16     Reserved_K   
int16     Reserved_L 
uint8     Reserved_M  
uint8     Reserved_N    
string    Reserved_O
string    Reserved_P

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z
================================================================================
MSG: geometry_msgs/Twist
# This expresses velocity in free space broken into its linear and angular parts.
Vector3  linear
Vector3  angular
"""
  __slots__ = ['object_ID','age','measurement_status','motion_state','existance_confidence','pose','dimensions','velocity','acceleration','v2ground','pose_nearest','type','car_confidence','bike_confidence','ped_confidence','truck_confidence','signboard_confidence','ground_confidence','obstacle_confidence','EnrollPtsNum','NearestPtsX','NearestPtsY','NearestPtsZ','Reserved_D','Reserved_E','Reserved_F','Reserved_G','Reserved_H','Reserved_I','Reserved_J','Reserved_K','Reserved_L','Reserved_M','Reserved_N','Reserved_O','Reserved_P']
  _slot_types = ['uint32','uint16','uint8','uint8','uint8','geometry_msgs/Pose','geometry_msgs/Vector3','geometry_msgs/Twist','geometry_msgs/Twist','geometry_msgs/Twist','geometry_msgs/Pose','uint8','uint8','uint8','uint8','uint8','uint8','uint8','uint8','float32','float32','float32','float32','float32','uint32','uint32','int32','int32','uint16','uint16','int16','int16','uint8','uint8','string','string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       object_ID,age,measurement_status,motion_state,existance_confidence,pose,dimensions,velocity,acceleration,v2ground,pose_nearest,type,car_confidence,bike_confidence,ped_confidence,truck_confidence,signboard_confidence,ground_confidence,obstacle_confidence,EnrollPtsNum,NearestPtsX,NearestPtsY,NearestPtsZ,Reserved_D,Reserved_E,Reserved_F,Reserved_G,Reserved_H,Reserved_I,Reserved_J,Reserved_K,Reserved_L,Reserved_M,Reserved_N,Reserved_O,Reserved_P

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Od, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.object_ID is None:
        self.object_ID = 0
      if self.age is None:
        self.age = 0
      if self.measurement_status is None:
        self.measurement_status = 0
      if self.motion_state is None:
        self.motion_state = 0
      if self.existance_confidence is None:
        self.existance_confidence = 0
      if self.pose is None:
        self.pose = geometry_msgs.msg.Pose()
      if self.dimensions is None:
        self.dimensions = geometry_msgs.msg.Vector3()
      if self.velocity is None:
        self.velocity = geometry_msgs.msg.Twist()
      if self.acceleration is None:
        self.acceleration = geometry_msgs.msg.Twist()
      if self.v2ground is None:
        self.v2ground = geometry_msgs.msg.Twist()
      if self.pose_nearest is None:
        self.pose_nearest = geometry_msgs.msg.Pose()
      if self.type is None:
        self.type = 0
      if self.car_confidence is None:
        self.car_confidence = 0
      if self.bike_confidence is None:
        self.bike_confidence = 0
      if self.ped_confidence is None:
        self.ped_confidence = 0
      if self.truck_confidence is None:
        self.truck_confidence = 0
      if self.signboard_confidence is None:
        self.signboard_confidence = 0
      if self.ground_confidence is None:
        self.ground_confidence = 0
      if self.obstacle_confidence is None:
        self.obstacle_confidence = 0
      if self.EnrollPtsNum is None:
        self.EnrollPtsNum = 0.
      if self.NearestPtsX is None:
        self.NearestPtsX = 0.
      if self.NearestPtsY is None:
        self.NearestPtsY = 0.
      if self.NearestPtsZ is None:
        self.NearestPtsZ = 0.
      if self.Reserved_D is None:
        self.Reserved_D = 0.
      if self.Reserved_E is None:
        self.Reserved_E = 0
      if self.Reserved_F is None:
        self.Reserved_F = 0
      if self.Reserved_G is None:
        self.Reserved_G = 0
      if self.Reserved_H is None:
        self.Reserved_H = 0
      if self.Reserved_I is None:
        self.Reserved_I = 0
      if self.Reserved_J is None:
        self.Reserved_J = 0
      if self.Reserved_K is None:
        self.Reserved_K = 0
      if self.Reserved_L is None:
        self.Reserved_L = 0
      if self.Reserved_M is None:
        self.Reserved_M = 0
      if self.Reserved_N is None:
        self.Reserved_N = 0
      if self.Reserved_O is None:
        self.Reserved_O = ''
      if self.Reserved_P is None:
        self.Reserved_P = ''
    else:
      self.object_ID = 0
      self.age = 0
      self.measurement_status = 0
      self.motion_state = 0
      self.existance_confidence = 0
      self.pose = geometry_msgs.msg.Pose()
      self.dimensions = geometry_msgs.msg.Vector3()
      self.velocity = geometry_msgs.msg.Twist()
      self.acceleration = geometry_msgs.msg.Twist()
      self.v2ground = geometry_msgs.msg.Twist()
      self.pose_nearest = geometry_msgs.msg.Pose()
      self.type = 0
      self.car_confidence = 0
      self.bike_confidence = 0
      self.ped_confidence = 0
      self.truck_confidence = 0
      self.signboard_confidence = 0
      self.ground_confidence = 0
      self.obstacle_confidence = 0
      self.EnrollPtsNum = 0.
      self.NearestPtsX = 0.
      self.NearestPtsY = 0.
      self.NearestPtsZ = 0.
      self.Reserved_D = 0.
      self.Reserved_E = 0
      self.Reserved_F = 0
      self.Reserved_G = 0
      self.Reserved_H = 0
      self.Reserved_I = 0
      self.Reserved_J = 0
      self.Reserved_K = 0
      self.Reserved_L = 0
      self.Reserved_M = 0
      self.Reserved_N = 0
      self.Reserved_O = ''
      self.Reserved_P = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_IH3B35d8B5f2I2i2H2h2B().pack(_x.object_ID, _x.age, _x.measurement_status, _x.motion_state, _x.existance_confidence, _x.pose.position.x, _x.pose.position.y, _x.pose.position.z, _x.pose.orientation.x, _x.pose.orientation.y, _x.pose.orientation.z, _x.pose.orientation.w, _x.dimensions.x, _x.dimensions.y, _x.dimensions.z, _x.velocity.linear.x, _x.velocity.linear.y, _x.velocity.linear.z, _x.velocity.angular.x, _x.velocity.angular.y, _x.velocity.angular.z, _x.acceleration.linear.x, _x.acceleration.linear.y, _x.acceleration.linear.z, _x.acceleration.angular.x, _x.acceleration.angular.y, _x.acceleration.angular.z, _x.v2ground.linear.x, _x.v2ground.linear.y, _x.v2ground.linear.z, _x.v2ground.angular.x, _x.v2ground.angular.y, _x.v2ground.angular.z, _x.pose_nearest.position.x, _x.pose_nearest.position.y, _x.pose_nearest.position.z, _x.pose_nearest.orientation.x, _x.pose_nearest.orientation.y, _x.pose_nearest.orientation.z, _x.pose_nearest.orientation.w, _x.type, _x.car_confidence, _x.bike_confidence, _x.ped_confidence, _x.truck_confidence, _x.signboard_confidence, _x.ground_confidence, _x.obstacle_confidence, _x.EnrollPtsNum, _x.NearestPtsX, _x.NearestPtsY, _x.NearestPtsZ, _x.Reserved_D, _x.Reserved_E, _x.Reserved_F, _x.Reserved_G, _x.Reserved_H, _x.Reserved_I, _x.Reserved_J, _x.Reserved_K, _x.Reserved_L, _x.Reserved_M, _x.Reserved_N))
      _x = self.Reserved_O
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.Reserved_P
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.pose is None:
        self.pose = geometry_msgs.msg.Pose()
      if self.dimensions is None:
        self.dimensions = geometry_msgs.msg.Vector3()
      if self.velocity is None:
        self.velocity = geometry_msgs.msg.Twist()
      if self.acceleration is None:
        self.acceleration = geometry_msgs.msg.Twist()
      if self.v2ground is None:
        self.v2ground = geometry_msgs.msg.Twist()
      if self.pose_nearest is None:
        self.pose_nearest = geometry_msgs.msg.Pose()
      end = 0
      _x = self
      start = end
      end += 343
      (_x.object_ID, _x.age, _x.measurement_status, _x.motion_state, _x.existance_confidence, _x.pose.position.x, _x.pose.position.y, _x.pose.position.z, _x.pose.orientation.x, _x.pose.orientation.y, _x.pose.orientation.z, _x.pose.orientation.w, _x.dimensions.x, _x.dimensions.y, _x.dimensions.z, _x.velocity.linear.x, _x.velocity.linear.y, _x.velocity.linear.z, _x.velocity.angular.x, _x.velocity.angular.y, _x.velocity.angular.z, _x.acceleration.linear.x, _x.acceleration.linear.y, _x.acceleration.linear.z, _x.acceleration.angular.x, _x.acceleration.angular.y, _x.acceleration.angular.z, _x.v2ground.linear.x, _x.v2ground.linear.y, _x.v2ground.linear.z, _x.v2ground.angular.x, _x.v2ground.angular.y, _x.v2ground.angular.z, _x.pose_nearest.position.x, _x.pose_nearest.position.y, _x.pose_nearest.position.z, _x.pose_nearest.orientation.x, _x.pose_nearest.orientation.y, _x.pose_nearest.orientation.z, _x.pose_nearest.orientation.w, _x.type, _x.car_confidence, _x.bike_confidence, _x.ped_confidence, _x.truck_confidence, _x.signboard_confidence, _x.ground_confidence, _x.obstacle_confidence, _x.EnrollPtsNum, _x.NearestPtsX, _x.NearestPtsY, _x.NearestPtsZ, _x.Reserved_D, _x.Reserved_E, _x.Reserved_F, _x.Reserved_G, _x.Reserved_H, _x.Reserved_I, _x.Reserved_J, _x.Reserved_K, _x.Reserved_L, _x.Reserved_M, _x.Reserved_N,) = _get_struct_IH3B35d8B5f2I2i2H2h2B().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.Reserved_O = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.Reserved_O = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.Reserved_P = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.Reserved_P = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_IH3B35d8B5f2I2i2H2h2B().pack(_x.object_ID, _x.age, _x.measurement_status, _x.motion_state, _x.existance_confidence, _x.pose.position.x, _x.pose.position.y, _x.pose.position.z, _x.pose.orientation.x, _x.pose.orientation.y, _x.pose.orientation.z, _x.pose.orientation.w, _x.dimensions.x, _x.dimensions.y, _x.dimensions.z, _x.velocity.linear.x, _x.velocity.linear.y, _x.velocity.linear.z, _x.velocity.angular.x, _x.velocity.angular.y, _x.velocity.angular.z, _x.acceleration.linear.x, _x.acceleration.linear.y, _x.acceleration.linear.z, _x.acceleration.angular.x, _x.acceleration.angular.y, _x.acceleration.angular.z, _x.v2ground.linear.x, _x.v2ground.linear.y, _x.v2ground.linear.z, _x.v2ground.angular.x, _x.v2ground.angular.y, _x.v2ground.angular.z, _x.pose_nearest.position.x, _x.pose_nearest.position.y, _x.pose_nearest.position.z, _x.pose_nearest.orientation.x, _x.pose_nearest.orientation.y, _x.pose_nearest.orientation.z, _x.pose_nearest.orientation.w, _x.type, _x.car_confidence, _x.bike_confidence, _x.ped_confidence, _x.truck_confidence, _x.signboard_confidence, _x.ground_confidence, _x.obstacle_confidence, _x.EnrollPtsNum, _x.NearestPtsX, _x.NearestPtsY, _x.NearestPtsZ, _x.Reserved_D, _x.Reserved_E, _x.Reserved_F, _x.Reserved_G, _x.Reserved_H, _x.Reserved_I, _x.Reserved_J, _x.Reserved_K, _x.Reserved_L, _x.Reserved_M, _x.Reserved_N))
      _x = self.Reserved_O
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.Reserved_P
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.pose is None:
        self.pose = geometry_msgs.msg.Pose()
      if self.dimensions is None:
        self.dimensions = geometry_msgs.msg.Vector3()
      if self.velocity is None:
        self.velocity = geometry_msgs.msg.Twist()
      if self.acceleration is None:
        self.acceleration = geometry_msgs.msg.Twist()
      if self.v2ground is None:
        self.v2ground = geometry_msgs.msg.Twist()
      if self.pose_nearest is None:
        self.pose_nearest = geometry_msgs.msg.Pose()
      end = 0
      _x = self
      start = end
      end += 343
      (_x.object_ID, _x.age, _x.measurement_status, _x.motion_state, _x.existance_confidence, _x.pose.position.x, _x.pose.position.y, _x.pose.position.z, _x.pose.orientation.x, _x.pose.orientation.y, _x.pose.orientation.z, _x.pose.orientation.w, _x.dimensions.x, _x.dimensions.y, _x.dimensions.z, _x.velocity.linear.x, _x.velocity.linear.y, _x.velocity.linear.z, _x.velocity.angular.x, _x.velocity.angular.y, _x.velocity.angular.z, _x.acceleration.linear.x, _x.acceleration.linear.y, _x.acceleration.linear.z, _x.acceleration.angular.x, _x.acceleration.angular.y, _x.acceleration.angular.z, _x.v2ground.linear.x, _x.v2ground.linear.y, _x.v2ground.linear.z, _x.v2ground.angular.x, _x.v2ground.angular.y, _x.v2ground.angular.z, _x.pose_nearest.position.x, _x.pose_nearest.position.y, _x.pose_nearest.position.z, _x.pose_nearest.orientation.x, _x.pose_nearest.orientation.y, _x.pose_nearest.orientation.z, _x.pose_nearest.orientation.w, _x.type, _x.car_confidence, _x.bike_confidence, _x.ped_confidence, _x.truck_confidence, _x.signboard_confidence, _x.ground_confidence, _x.obstacle_confidence, _x.EnrollPtsNum, _x.NearestPtsX, _x.NearestPtsY, _x.NearestPtsZ, _x.Reserved_D, _x.Reserved_E, _x.Reserved_F, _x.Reserved_G, _x.Reserved_H, _x.Reserved_I, _x.Reserved_J, _x.Reserved_K, _x.Reserved_L, _x.Reserved_M, _x.Reserved_N,) = _get_struct_IH3B35d8B5f2I2i2H2h2B().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.Reserved_O = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.Reserved_O = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.Reserved_P = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.Reserved_P = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_IH3B35d8B5f2I2i2H2h2B = None
def _get_struct_IH3B35d8B5f2I2i2H2h2B():
    global _struct_IH3B35d8B5f2I2i2H2h2B
    if _struct_IH3B35d8B5f2I2i2H2h2B is None:
        _struct_IH3B35d8B5f2I2i2H2h2B = struct.Struct("<IH3B35d8B5f2I2i2H2h2B")
    return _struct_IH3B35d8B5f2I2i2H2h2B
