# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from radar_msgs/OdArray.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import radar_msgs.msg
import std_msgs.msg

class OdArray(genpy.Message):
  _md5sum = "efbe1652c996ab4b9be091c4010e6a53"
  _type = "radar_msgs/OdArray"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header    header               # Includes measurement timestamp and coordinate frame.
uint32    radarID              # radar ID
uint32    frameCnt             # frame cnt in radar
uint32    objNum               # object number of this frame
Od[]      odArray              # array of tracking objects

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: radar_msgs/Od
# Header    header               # Includes measurement timestamp and coordinate frame.
uint32    object_ID            # object ID
uint16    age                  # total frames from the object occurs
uint8     measurement_status   # track status (0: measured; 1: new; 2: predicted)
uint8     motion_state         # movement state ( 0: static; 1: dynamic)
uint8     existance_confidence # existance confidence
geometry_msgs/Pose              pose #central position x, y, z; roll=0, pitch=0, yaw to quaternion
geometry_msgs/Vector3           dimensions #length, width, height
geometry_msgs/Twist             velocity
geometry_msgs/Twist             acceleration
geometry_msgs/Twist             v2ground #velocity towards ground of x, y, z orientation
geometry_msgs/Pose              pose_nearest #NearestPts x, y, z
uint8     type                 # object type (（0: car 小型汽车; 1: bike 两轮车; 2: pedestrian 行人; 3: truck 大车; 4: signboard 高空物; 5: ground 地面; 6: obstacle 静态障碍物)
uint8     car_confidence       # car confidence
uint8     bike_confidence      # bike confidence
uint8     ped_confidence       # pedestrian confidence
uint8     truck_confidence     # truck confidence
uint8     signboard_confidence # signboard confidence
uint8     ground_confidence    # ground confidence
uint8     obstacle_confidence  # obstacle confidence
float32   EnrollPtsNum         # EnrollPtsNum
float32   NearestPtsX          # NearestPtsX           
float32   NearestPtsY          # NearestPtsY
float32   NearestPtsZ          # NearestPtsZ
float32   Reserved_D  
uint32    Reserved_E          
uint32    Reserved_F           
int32     Reserved_G           
int32     Reserved_H    
uint16    Reserved_I   
uint16    Reserved_J    
int16     Reserved_K   
int16     Reserved_L 
uint8     Reserved_M  
uint8     Reserved_N    
string    Reserved_O
string    Reserved_P

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z
================================================================================
MSG: geometry_msgs/Twist
# This expresses velocity in free space broken into its linear and angular parts.
Vector3  linear
Vector3  angular
"""
  __slots__ = ['header','radarID','frameCnt','objNum','odArray']
  _slot_types = ['std_msgs/Header','uint32','uint32','uint32','radar_msgs/Od[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,radarID,frameCnt,objNum,odArray

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(OdArray, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.radarID is None:
        self.radarID = 0
      if self.frameCnt is None:
        self.frameCnt = 0
      if self.objNum is None:
        self.objNum = 0
      if self.odArray is None:
        self.odArray = []
    else:
      self.header = std_msgs.msg.Header()
      self.radarID = 0
      self.frameCnt = 0
      self.objNum = 0
      self.odArray = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.radarID, _x.frameCnt, _x.objNum))
      length = len(self.odArray)
      buff.write(_struct_I.pack(length))
      for val1 in self.odArray:
        _x = val1
        buff.write(_get_struct_IH3B().pack(_x.object_ID, _x.age, _x.measurement_status, _x.motion_state, _x.existance_confidence))
        _v1 = val1.pose
        _v2 = _v1.position
        _x = _v2
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v3 = _v1.orientation
        _x = _v3
        buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
        _v4 = val1.dimensions
        _x = _v4
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v5 = val1.velocity
        _v6 = _v5.linear
        _x = _v6
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v7 = _v5.angular
        _x = _v7
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v8 = val1.acceleration
        _v9 = _v8.linear
        _x = _v9
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v10 = _v8.angular
        _x = _v10
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v11 = val1.v2ground
        _v12 = _v11.linear
        _x = _v12
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v13 = _v11.angular
        _x = _v13
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v14 = val1.pose_nearest
        _v15 = _v14.position
        _x = _v15
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v16 = _v14.orientation
        _x = _v16
        buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
        _x = val1
        buff.write(_get_struct_8B5f2I2i2H2h2B().pack(_x.type, _x.car_confidence, _x.bike_confidence, _x.ped_confidence, _x.truck_confidence, _x.signboard_confidence, _x.ground_confidence, _x.obstacle_confidence, _x.EnrollPtsNum, _x.NearestPtsX, _x.NearestPtsY, _x.NearestPtsZ, _x.Reserved_D, _x.Reserved_E, _x.Reserved_F, _x.Reserved_G, _x.Reserved_H, _x.Reserved_I, _x.Reserved_J, _x.Reserved_K, _x.Reserved_L, _x.Reserved_M, _x.Reserved_N))
        _x = val1.Reserved_O
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1.Reserved_P
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.odArray is None:
        self.odArray = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.radarID, _x.frameCnt, _x.objNum,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.odArray = []
      for i in range(0, length):
        val1 = radar_msgs.msg.Od()
        _x = val1
        start = end
        end += 9
        (_x.object_ID, _x.age, _x.measurement_status, _x.motion_state, _x.existance_confidence,) = _get_struct_IH3B().unpack(str[start:end])
        _v17 = val1.pose
        _v18 = _v17.position
        _x = _v18
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v19 = _v17.orientation
        _x = _v19
        start = end
        end += 32
        (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4d().unpack(str[start:end])
        _v20 = val1.dimensions
        _x = _v20
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v21 = val1.velocity
        _v22 = _v21.linear
        _x = _v22
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v23 = _v21.angular
        _x = _v23
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v24 = val1.acceleration
        _v25 = _v24.linear
        _x = _v25
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v26 = _v24.angular
        _x = _v26
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v27 = val1.v2ground
        _v28 = _v27.linear
        _x = _v28
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v29 = _v27.angular
        _x = _v29
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v30 = val1.pose_nearest
        _v31 = _v30.position
        _x = _v31
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v32 = _v30.orientation
        _x = _v32
        start = end
        end += 32
        (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4d().unpack(str[start:end])
        _x = val1
        start = end
        end += 54
        (_x.type, _x.car_confidence, _x.bike_confidence, _x.ped_confidence, _x.truck_confidence, _x.signboard_confidence, _x.ground_confidence, _x.obstacle_confidence, _x.EnrollPtsNum, _x.NearestPtsX, _x.NearestPtsY, _x.NearestPtsZ, _x.Reserved_D, _x.Reserved_E, _x.Reserved_F, _x.Reserved_G, _x.Reserved_H, _x.Reserved_I, _x.Reserved_J, _x.Reserved_K, _x.Reserved_L, _x.Reserved_M, _x.Reserved_N,) = _get_struct_8B5f2I2i2H2h2B().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.Reserved_O = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.Reserved_O = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.Reserved_P = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.Reserved_P = str[start:end]
        self.odArray.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.radarID, _x.frameCnt, _x.objNum))
      length = len(self.odArray)
      buff.write(_struct_I.pack(length))
      for val1 in self.odArray:
        _x = val1
        buff.write(_get_struct_IH3B().pack(_x.object_ID, _x.age, _x.measurement_status, _x.motion_state, _x.existance_confidence))
        _v33 = val1.pose
        _v34 = _v33.position
        _x = _v34
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v35 = _v33.orientation
        _x = _v35
        buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
        _v36 = val1.dimensions
        _x = _v36
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v37 = val1.velocity
        _v38 = _v37.linear
        _x = _v38
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v39 = _v37.angular
        _x = _v39
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v40 = val1.acceleration
        _v41 = _v40.linear
        _x = _v41
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v42 = _v40.angular
        _x = _v42
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v43 = val1.v2ground
        _v44 = _v43.linear
        _x = _v44
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v45 = _v43.angular
        _x = _v45
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v46 = val1.pose_nearest
        _v47 = _v46.position
        _x = _v47
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v48 = _v46.orientation
        _x = _v48
        buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
        _x = val1
        buff.write(_get_struct_8B5f2I2i2H2h2B().pack(_x.type, _x.car_confidence, _x.bike_confidence, _x.ped_confidence, _x.truck_confidence, _x.signboard_confidence, _x.ground_confidence, _x.obstacle_confidence, _x.EnrollPtsNum, _x.NearestPtsX, _x.NearestPtsY, _x.NearestPtsZ, _x.Reserved_D, _x.Reserved_E, _x.Reserved_F, _x.Reserved_G, _x.Reserved_H, _x.Reserved_I, _x.Reserved_J, _x.Reserved_K, _x.Reserved_L, _x.Reserved_M, _x.Reserved_N))
        _x = val1.Reserved_O
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1.Reserved_P
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.odArray is None:
        self.odArray = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.radarID, _x.frameCnt, _x.objNum,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.odArray = []
      for i in range(0, length):
        val1 = radar_msgs.msg.Od()
        _x = val1
        start = end
        end += 9
        (_x.object_ID, _x.age, _x.measurement_status, _x.motion_state, _x.existance_confidence,) = _get_struct_IH3B().unpack(str[start:end])
        _v49 = val1.pose
        _v50 = _v49.position
        _x = _v50
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v51 = _v49.orientation
        _x = _v51
        start = end
        end += 32
        (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4d().unpack(str[start:end])
        _v52 = val1.dimensions
        _x = _v52
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v53 = val1.velocity
        _v54 = _v53.linear
        _x = _v54
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v55 = _v53.angular
        _x = _v55
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v56 = val1.acceleration
        _v57 = _v56.linear
        _x = _v57
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v58 = _v56.angular
        _x = _v58
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v59 = val1.v2ground
        _v60 = _v59.linear
        _x = _v60
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v61 = _v59.angular
        _x = _v61
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v62 = val1.pose_nearest
        _v63 = _v62.position
        _x = _v63
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v64 = _v62.orientation
        _x = _v64
        start = end
        end += 32
        (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4d().unpack(str[start:end])
        _x = val1
        start = end
        end += 54
        (_x.type, _x.car_confidence, _x.bike_confidence, _x.ped_confidence, _x.truck_confidence, _x.signboard_confidence, _x.ground_confidence, _x.obstacle_confidence, _x.EnrollPtsNum, _x.NearestPtsX, _x.NearestPtsY, _x.NearestPtsZ, _x.Reserved_D, _x.Reserved_E, _x.Reserved_F, _x.Reserved_G, _x.Reserved_H, _x.Reserved_I, _x.Reserved_J, _x.Reserved_K, _x.Reserved_L, _x.Reserved_M, _x.Reserved_N,) = _get_struct_8B5f2I2i2H2h2B().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.Reserved_O = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.Reserved_O = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.Reserved_P = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.Reserved_P = str[start:end]
        self.odArray.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
_struct_4d = None
def _get_struct_4d():
    global _struct_4d
    if _struct_4d is None:
        _struct_4d = struct.Struct("<4d")
    return _struct_4d
_struct_8B5f2I2i2H2h2B = None
def _get_struct_8B5f2I2i2H2h2B():
    global _struct_8B5f2I2i2H2h2B
    if _struct_8B5f2I2i2H2h2B is None:
        _struct_8B5f2I2i2H2h2B = struct.Struct("<8B5f2I2i2H2h2B")
    return _struct_8B5f2I2i2H2h2B
_struct_IH3B = None
def _get_struct_IH3B():
    global _struct_IH3B
    if _struct_IH3B is None:
        _struct_IH3B = struct.Struct("<IH3B")
    return _struct_IH3B
