# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from radar_msgs/ProcessStatus.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class ProcessStatus(genpy.Message):
  _md5sum = "3b68402e7d30a9e6144470a4717d74aa"
  _type = "radar_msgs/ProcessStatus"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header                   # Includes measurement timestamp and coordinate frame.
uint32 radarID                  # radar ID
uint32 frameCnt                 # frame cnt in radar
float32 captureTime              # LSB=ms
uint32 frameLostCnt             
uint32 adcErrCnt       
uint32 reserved_a
uint32 reserved_b
float32 time1DFFT                # LSB=ms
uint32 reserved_c
uint32 reserved_d
uint32 reserved_e
uint32 reserved_f
float32 time2DFFT                # LSB=ms
uint32 reserved_g
uint32 reserved_h
uint32 reserved_i
uint32 reserved_j
float32 timeRDMap                # LSB=ms
uint32 reserved_k
uint32 reserved_l
uint32 reserved_m
uint32 reserved_n
float32 timeCfar                 # LSB=ms
uint32 reserved_o
uint32 reserved_p
uint32 reserved_q
uint32 reserved_r
float32 timeDOA                  # LSB=ms
uint32 reserved_s
uint32 reserved_t
uint32 reserved_u
uint32 reserved_v
float32 timePCL                  # LSB=ms
uint32 reserved_w                # velocity Estimated
uint32 reserved_x                # ground K
uint32 reserved_y                # ground B
uint32 reserved_z                # pcl delay time, LSB = 0.1ms
float32 timeOD                   # LSB=ms
uint32 odTimeoutCnt             
int32  selfCaliStatus           # 0: cali fails; 1: pre-cali; 1~99: calibrating(in process); 100: cali success
uint32 reserved_aa              # od delay time, LSB = 0.1ms
uint32 reserved_ab
uint32 reserved_ac
uint32 reserved_ad

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','radarID','frameCnt','captureTime','frameLostCnt','adcErrCnt','reserved_a','reserved_b','time1DFFT','reserved_c','reserved_d','reserved_e','reserved_f','time2DFFT','reserved_g','reserved_h','reserved_i','reserved_j','timeRDMap','reserved_k','reserved_l','reserved_m','reserved_n','timeCfar','reserved_o','reserved_p','reserved_q','reserved_r','timeDOA','reserved_s','reserved_t','reserved_u','reserved_v','timePCL','reserved_w','reserved_x','reserved_y','reserved_z','timeOD','odTimeoutCnt','selfCaliStatus','reserved_aa','reserved_ab','reserved_ac','reserved_ad']
  _slot_types = ['std_msgs/Header','uint32','uint32','float32','uint32','uint32','uint32','uint32','float32','uint32','uint32','uint32','uint32','float32','uint32','uint32','uint32','uint32','float32','uint32','uint32','uint32','uint32','float32','uint32','uint32','uint32','uint32','float32','uint32','uint32','uint32','uint32','float32','uint32','uint32','uint32','uint32','float32','uint32','int32','uint32','uint32','uint32','uint32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,radarID,frameCnt,captureTime,frameLostCnt,adcErrCnt,reserved_a,reserved_b,time1DFFT,reserved_c,reserved_d,reserved_e,reserved_f,time2DFFT,reserved_g,reserved_h,reserved_i,reserved_j,timeRDMap,reserved_k,reserved_l,reserved_m,reserved_n,timeCfar,reserved_o,reserved_p,reserved_q,reserved_r,timeDOA,reserved_s,reserved_t,reserved_u,reserved_v,timePCL,reserved_w,reserved_x,reserved_y,reserved_z,timeOD,odTimeoutCnt,selfCaliStatus,reserved_aa,reserved_ab,reserved_ac,reserved_ad

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ProcessStatus, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.radarID is None:
        self.radarID = 0
      if self.frameCnt is None:
        self.frameCnt = 0
      if self.captureTime is None:
        self.captureTime = 0.
      if self.frameLostCnt is None:
        self.frameLostCnt = 0
      if self.adcErrCnt is None:
        self.adcErrCnt = 0
      if self.reserved_a is None:
        self.reserved_a = 0
      if self.reserved_b is None:
        self.reserved_b = 0
      if self.time1DFFT is None:
        self.time1DFFT = 0.
      if self.reserved_c is None:
        self.reserved_c = 0
      if self.reserved_d is None:
        self.reserved_d = 0
      if self.reserved_e is None:
        self.reserved_e = 0
      if self.reserved_f is None:
        self.reserved_f = 0
      if self.time2DFFT is None:
        self.time2DFFT = 0.
      if self.reserved_g is None:
        self.reserved_g = 0
      if self.reserved_h is None:
        self.reserved_h = 0
      if self.reserved_i is None:
        self.reserved_i = 0
      if self.reserved_j is None:
        self.reserved_j = 0
      if self.timeRDMap is None:
        self.timeRDMap = 0.
      if self.reserved_k is None:
        self.reserved_k = 0
      if self.reserved_l is None:
        self.reserved_l = 0
      if self.reserved_m is None:
        self.reserved_m = 0
      if self.reserved_n is None:
        self.reserved_n = 0
      if self.timeCfar is None:
        self.timeCfar = 0.
      if self.reserved_o is None:
        self.reserved_o = 0
      if self.reserved_p is None:
        self.reserved_p = 0
      if self.reserved_q is None:
        self.reserved_q = 0
      if self.reserved_r is None:
        self.reserved_r = 0
      if self.timeDOA is None:
        self.timeDOA = 0.
      if self.reserved_s is None:
        self.reserved_s = 0
      if self.reserved_t is None:
        self.reserved_t = 0
      if self.reserved_u is None:
        self.reserved_u = 0
      if self.reserved_v is None:
        self.reserved_v = 0
      if self.timePCL is None:
        self.timePCL = 0.
      if self.reserved_w is None:
        self.reserved_w = 0
      if self.reserved_x is None:
        self.reserved_x = 0
      if self.reserved_y is None:
        self.reserved_y = 0
      if self.reserved_z is None:
        self.reserved_z = 0
      if self.timeOD is None:
        self.timeOD = 0.
      if self.odTimeoutCnt is None:
        self.odTimeoutCnt = 0
      if self.selfCaliStatus is None:
        self.selfCaliStatus = 0
      if self.reserved_aa is None:
        self.reserved_aa = 0
      if self.reserved_ab is None:
        self.reserved_ab = 0
      if self.reserved_ac is None:
        self.reserved_ac = 0
      if self.reserved_ad is None:
        self.reserved_ad = 0
    else:
      self.header = std_msgs.msg.Header()
      self.radarID = 0
      self.frameCnt = 0
      self.captureTime = 0.
      self.frameLostCnt = 0
      self.adcErrCnt = 0
      self.reserved_a = 0
      self.reserved_b = 0
      self.time1DFFT = 0.
      self.reserved_c = 0
      self.reserved_d = 0
      self.reserved_e = 0
      self.reserved_f = 0
      self.time2DFFT = 0.
      self.reserved_g = 0
      self.reserved_h = 0
      self.reserved_i = 0
      self.reserved_j = 0
      self.timeRDMap = 0.
      self.reserved_k = 0
      self.reserved_l = 0
      self.reserved_m = 0
      self.reserved_n = 0
      self.timeCfar = 0.
      self.reserved_o = 0
      self.reserved_p = 0
      self.reserved_q = 0
      self.reserved_r = 0
      self.timeDOA = 0.
      self.reserved_s = 0
      self.reserved_t = 0
      self.reserved_u = 0
      self.reserved_v = 0
      self.timePCL = 0.
      self.reserved_w = 0
      self.reserved_x = 0
      self.reserved_y = 0
      self.reserved_z = 0
      self.timeOD = 0.
      self.odTimeoutCnt = 0
      self.selfCaliStatus = 0
      self.reserved_aa = 0
      self.reserved_ab = 0
      self.reserved_ac = 0
      self.reserved_ad = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2If4If4If4If4If4If4If4IfIi4I().pack(_x.radarID, _x.frameCnt, _x.captureTime, _x.frameLostCnt, _x.adcErrCnt, _x.reserved_a, _x.reserved_b, _x.time1DFFT, _x.reserved_c, _x.reserved_d, _x.reserved_e, _x.reserved_f, _x.time2DFFT, _x.reserved_g, _x.reserved_h, _x.reserved_i, _x.reserved_j, _x.timeRDMap, _x.reserved_k, _x.reserved_l, _x.reserved_m, _x.reserved_n, _x.timeCfar, _x.reserved_o, _x.reserved_p, _x.reserved_q, _x.reserved_r, _x.timeDOA, _x.reserved_s, _x.reserved_t, _x.reserved_u, _x.reserved_v, _x.timePCL, _x.reserved_w, _x.reserved_x, _x.reserved_y, _x.reserved_z, _x.timeOD, _x.odTimeoutCnt, _x.selfCaliStatus, _x.reserved_aa, _x.reserved_ab, _x.reserved_ac, _x.reserved_ad))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 176
      (_x.radarID, _x.frameCnt, _x.captureTime, _x.frameLostCnt, _x.adcErrCnt, _x.reserved_a, _x.reserved_b, _x.time1DFFT, _x.reserved_c, _x.reserved_d, _x.reserved_e, _x.reserved_f, _x.time2DFFT, _x.reserved_g, _x.reserved_h, _x.reserved_i, _x.reserved_j, _x.timeRDMap, _x.reserved_k, _x.reserved_l, _x.reserved_m, _x.reserved_n, _x.timeCfar, _x.reserved_o, _x.reserved_p, _x.reserved_q, _x.reserved_r, _x.timeDOA, _x.reserved_s, _x.reserved_t, _x.reserved_u, _x.reserved_v, _x.timePCL, _x.reserved_w, _x.reserved_x, _x.reserved_y, _x.reserved_z, _x.timeOD, _x.odTimeoutCnt, _x.selfCaliStatus, _x.reserved_aa, _x.reserved_ab, _x.reserved_ac, _x.reserved_ad,) = _get_struct_2If4If4If4If4If4If4If4IfIi4I().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2If4If4If4If4If4If4If4IfIi4I().pack(_x.radarID, _x.frameCnt, _x.captureTime, _x.frameLostCnt, _x.adcErrCnt, _x.reserved_a, _x.reserved_b, _x.time1DFFT, _x.reserved_c, _x.reserved_d, _x.reserved_e, _x.reserved_f, _x.time2DFFT, _x.reserved_g, _x.reserved_h, _x.reserved_i, _x.reserved_j, _x.timeRDMap, _x.reserved_k, _x.reserved_l, _x.reserved_m, _x.reserved_n, _x.timeCfar, _x.reserved_o, _x.reserved_p, _x.reserved_q, _x.reserved_r, _x.timeDOA, _x.reserved_s, _x.reserved_t, _x.reserved_u, _x.reserved_v, _x.timePCL, _x.reserved_w, _x.reserved_x, _x.reserved_y, _x.reserved_z, _x.timeOD, _x.odTimeoutCnt, _x.selfCaliStatus, _x.reserved_aa, _x.reserved_ab, _x.reserved_ac, _x.reserved_ad))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 176
      (_x.radarID, _x.frameCnt, _x.captureTime, _x.frameLostCnt, _x.adcErrCnt, _x.reserved_a, _x.reserved_b, _x.time1DFFT, _x.reserved_c, _x.reserved_d, _x.reserved_e, _x.reserved_f, _x.time2DFFT, _x.reserved_g, _x.reserved_h, _x.reserved_i, _x.reserved_j, _x.timeRDMap, _x.reserved_k, _x.reserved_l, _x.reserved_m, _x.reserved_n, _x.timeCfar, _x.reserved_o, _x.reserved_p, _x.reserved_q, _x.reserved_r, _x.timeDOA, _x.reserved_s, _x.reserved_t, _x.reserved_u, _x.reserved_v, _x.timePCL, _x.reserved_w, _x.reserved_x, _x.reserved_y, _x.reserved_z, _x.timeOD, _x.odTimeoutCnt, _x.selfCaliStatus, _x.reserved_aa, _x.reserved_ab, _x.reserved_ac, _x.reserved_ad,) = _get_struct_2If4If4If4If4If4If4If4IfIi4I().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2If4If4If4If4If4If4If4IfIi4I = None
def _get_struct_2If4If4If4If4If4If4If4IfIi4I():
    global _struct_2If4If4If4If4If4If4If4IfIi4I
    if _struct_2If4If4If4If4If4If4If4IfIi4I is None:
        _struct_2If4If4If4If4If4If4If4IfIi4I = struct.Struct("<2If4If4If4If4If4If4If4IfIi4I")
    return _struct_2If4If4If4If4If4If4If4IfIi4I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
