# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from radar_msgs/RdInfo.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class RdInfo(genpy.Message):
  _md5sum = "990a952bd164911e0965074cc0babe8d"
  _type = "radar_msgs/RdInfo"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header  header              # Includes measurement timestamp and coordinate frame.
uint32  frameID
uint32  cfarCount           # cfar count
uint32  targetNum           # targets Num
int16   resetcnt            # reset count
uint32  objNum              # object number of this frame
float32 carSpeed            # ego car speed
float32 carYawRate          # ego car yaw rate
uint16  gearState           # ego car gear state
int16   odTimeoutCnt
uint16  comProtV_I
uint16  comProtV_II
uint16  frameLostCnt        # frame lost count checked by ROS sw
uint16  beforeAdcErrCnt
uint16  afterAdcErrCnt
uint32  udpFrameLostCnt     # counter of lost frames
float32 udpFreq             # frames frequency in Hz
uint16  timeSyncStatus      # status of time synchronization
float32 velEstimate         # estimated car speed, m/s
float32 gndK
float32 gndB
float32 pcl_time            # duration of od process (ms)
float32 od_time             # duration of od process (ms)
uint32  RdFrameLostCnt      # frame lost count in radar
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','frameID','cfarCount','targetNum','resetcnt','objNum','carSpeed','carYawRate','gearState','odTimeoutCnt','comProtV_I','comProtV_II','frameLostCnt','beforeAdcErrCnt','afterAdcErrCnt','udpFrameLostCnt','udpFreq','timeSyncStatus','velEstimate','gndK','gndB','pcl_time','od_time','RdFrameLostCnt']
  _slot_types = ['std_msgs/Header','uint32','uint32','uint32','int16','uint32','float32','float32','uint16','int16','uint16','uint16','uint16','uint16','uint16','uint32','float32','uint16','float32','float32','float32','float32','float32','uint32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,frameID,cfarCount,targetNum,resetcnt,objNum,carSpeed,carYawRate,gearState,odTimeoutCnt,comProtV_I,comProtV_II,frameLostCnt,beforeAdcErrCnt,afterAdcErrCnt,udpFrameLostCnt,udpFreq,timeSyncStatus,velEstimate,gndK,gndB,pcl_time,od_time,RdFrameLostCnt

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RdInfo, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.frameID is None:
        self.frameID = 0
      if self.cfarCount is None:
        self.cfarCount = 0
      if self.targetNum is None:
        self.targetNum = 0
      if self.resetcnt is None:
        self.resetcnt = 0
      if self.objNum is None:
        self.objNum = 0
      if self.carSpeed is None:
        self.carSpeed = 0.
      if self.carYawRate is None:
        self.carYawRate = 0.
      if self.gearState is None:
        self.gearState = 0
      if self.odTimeoutCnt is None:
        self.odTimeoutCnt = 0
      if self.comProtV_I is None:
        self.comProtV_I = 0
      if self.comProtV_II is None:
        self.comProtV_II = 0
      if self.frameLostCnt is None:
        self.frameLostCnt = 0
      if self.beforeAdcErrCnt is None:
        self.beforeAdcErrCnt = 0
      if self.afterAdcErrCnt is None:
        self.afterAdcErrCnt = 0
      if self.udpFrameLostCnt is None:
        self.udpFrameLostCnt = 0
      if self.udpFreq is None:
        self.udpFreq = 0.
      if self.timeSyncStatus is None:
        self.timeSyncStatus = 0
      if self.velEstimate is None:
        self.velEstimate = 0.
      if self.gndK is None:
        self.gndK = 0.
      if self.gndB is None:
        self.gndB = 0.
      if self.pcl_time is None:
        self.pcl_time = 0.
      if self.od_time is None:
        self.od_time = 0.
      if self.RdFrameLostCnt is None:
        self.RdFrameLostCnt = 0
    else:
      self.header = std_msgs.msg.Header()
      self.frameID = 0
      self.cfarCount = 0
      self.targetNum = 0
      self.resetcnt = 0
      self.objNum = 0
      self.carSpeed = 0.
      self.carYawRate = 0.
      self.gearState = 0
      self.odTimeoutCnt = 0
      self.comProtV_I = 0
      self.comProtV_II = 0
      self.frameLostCnt = 0
      self.beforeAdcErrCnt = 0
      self.afterAdcErrCnt = 0
      self.udpFrameLostCnt = 0
      self.udpFreq = 0.
      self.timeSyncStatus = 0
      self.velEstimate = 0.
      self.gndK = 0.
      self.gndB = 0.
      self.pcl_time = 0.
      self.od_time = 0.
      self.RdFrameLostCnt = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3IhI2fHh5HIfH5fI().pack(_x.frameID, _x.cfarCount, _x.targetNum, _x.resetcnt, _x.objNum, _x.carSpeed, _x.carYawRate, _x.gearState, _x.odTimeoutCnt, _x.comProtV_I, _x.comProtV_II, _x.frameLostCnt, _x.beforeAdcErrCnt, _x.afterAdcErrCnt, _x.udpFrameLostCnt, _x.udpFreq, _x.timeSyncStatus, _x.velEstimate, _x.gndK, _x.gndB, _x.pcl_time, _x.od_time, _x.RdFrameLostCnt))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 74
      (_x.frameID, _x.cfarCount, _x.targetNum, _x.resetcnt, _x.objNum, _x.carSpeed, _x.carYawRate, _x.gearState, _x.odTimeoutCnt, _x.comProtV_I, _x.comProtV_II, _x.frameLostCnt, _x.beforeAdcErrCnt, _x.afterAdcErrCnt, _x.udpFrameLostCnt, _x.udpFreq, _x.timeSyncStatus, _x.velEstimate, _x.gndK, _x.gndB, _x.pcl_time, _x.od_time, _x.RdFrameLostCnt,) = _get_struct_3IhI2fHh5HIfH5fI().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3IhI2fHh5HIfH5fI().pack(_x.frameID, _x.cfarCount, _x.targetNum, _x.resetcnt, _x.objNum, _x.carSpeed, _x.carYawRate, _x.gearState, _x.odTimeoutCnt, _x.comProtV_I, _x.comProtV_II, _x.frameLostCnt, _x.beforeAdcErrCnt, _x.afterAdcErrCnt, _x.udpFrameLostCnt, _x.udpFreq, _x.timeSyncStatus, _x.velEstimate, _x.gndK, _x.gndB, _x.pcl_time, _x.od_time, _x.RdFrameLostCnt))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 74
      (_x.frameID, _x.cfarCount, _x.targetNum, _x.resetcnt, _x.objNum, _x.carSpeed, _x.carYawRate, _x.gearState, _x.odTimeoutCnt, _x.comProtV_I, _x.comProtV_II, _x.frameLostCnt, _x.beforeAdcErrCnt, _x.afterAdcErrCnt, _x.udpFrameLostCnt, _x.udpFreq, _x.timeSyncStatus, _x.velEstimate, _x.gndK, _x.gndB, _x.pcl_time, _x.od_time, _x.RdFrameLostCnt,) = _get_struct_3IhI2fHh5HIfH5fI().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_3IhI2fHh5HIfH5fI = None
def _get_struct_3IhI2fHh5HIfH5fI():
    global _struct_3IhI2fHh5HIfH5fI
    if _struct_3IhI2fHh5HIfH5fI is None:
        _struct_3IhI2fHh5HIfH5fI = struct.Struct("<3IhI2fHh5HIfH5fI")
    return _struct_3IhI2fHh5HIfH5fI
