# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from radar_msgs/RlMonPmclkloIntAnaSigRep.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class RlMonPmclkloIntAnaSigRep(genpy.Message):
  _md5sum = "c312c17cf1d0d5133fcf19c9462adfaa"
  _type = "radar_msgs/RlMonPmclkloIntAnaSigRep"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint16 statusFlags
uint16 errorCode
uint8 profIndex
int8 sync20GPower
uint16 reserved
uint32 timeStamp"""
  __slots__ = ['statusFlags','errorCode','profIndex','sync20GPower','reserved','timeStamp']
  _slot_types = ['uint16','uint16','uint8','int8','uint16','uint32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       statusFlags,errorCode,profIndex,sync20GPower,reserved,timeStamp

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RlMonPmclkloIntAnaSigRep, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.statusFlags is None:
        self.statusFlags = 0
      if self.errorCode is None:
        self.errorCode = 0
      if self.profIndex is None:
        self.profIndex = 0
      if self.sync20GPower is None:
        self.sync20GPower = 0
      if self.reserved is None:
        self.reserved = 0
      if self.timeStamp is None:
        self.timeStamp = 0
    else:
      self.statusFlags = 0
      self.errorCode = 0
      self.profIndex = 0
      self.sync20GPower = 0
      self.reserved = 0
      self.timeStamp = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2HBbHI().pack(_x.statusFlags, _x.errorCode, _x.profIndex, _x.sync20GPower, _x.reserved, _x.timeStamp))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 12
      (_x.statusFlags, _x.errorCode, _x.profIndex, _x.sync20GPower, _x.reserved, _x.timeStamp,) = _get_struct_2HBbHI().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2HBbHI().pack(_x.statusFlags, _x.errorCode, _x.profIndex, _x.sync20GPower, _x.reserved, _x.timeStamp))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 12
      (_x.statusFlags, _x.errorCode, _x.profIndex, _x.sync20GPower, _x.reserved, _x.timeStamp,) = _get_struct_2HBbHI().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2HBbHI = None
def _get_struct_2HBbHI():
    global _struct_2HBbHI
    if _struct_2HBbHI is None:
        _struct_2HBbHI = struct.Struct("<2HBbHI")
    return _struct_2HBbHI
