# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from radar_msgs/RlMonSynthFreqNonLiveRep.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class RlMonSynthFreqNonLiveRep(genpy.Message):
  _md5sum = "d0edbc23d8d4e3fb8b9ba98fa67b4c6d"
  _type = "radar_msgs/RlMonSynthFreqNonLiveRep"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint16 statusFlags
uint16 errorCode
uint8 profIndex0
uint8 reserved0
uint16 reserved1
int32 maxFreqErVal0
uint32 freqFailCnt0
uint32 maxFreqFailTime0
uint32 reserved2
uint8 profIndex1
uint8 reserved3
uint16 reserved4
int32 maxFreqErVal1
uint32 freqFailCnt1
uint32 maxFreqFailTime1
uint32 reserved5
uint32 timeStamp"""
  __slots__ = ['statusFlags','errorCode','profIndex0','reserved0','reserved1','maxFreqErVal0','freqFailCnt0','maxFreqFailTime0','reserved2','profIndex1','reserved3','reserved4','maxFreqErVal1','freqFailCnt1','maxFreqFailTime1','reserved5','timeStamp']
  _slot_types = ['uint16','uint16','uint8','uint8','uint16','int32','uint32','uint32','uint32','uint8','uint8','uint16','int32','uint32','uint32','uint32','uint32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       statusFlags,errorCode,profIndex0,reserved0,reserved1,maxFreqErVal0,freqFailCnt0,maxFreqFailTime0,reserved2,profIndex1,reserved3,reserved4,maxFreqErVal1,freqFailCnt1,maxFreqFailTime1,reserved5,timeStamp

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RlMonSynthFreqNonLiveRep, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.statusFlags is None:
        self.statusFlags = 0
      if self.errorCode is None:
        self.errorCode = 0
      if self.profIndex0 is None:
        self.profIndex0 = 0
      if self.reserved0 is None:
        self.reserved0 = 0
      if self.reserved1 is None:
        self.reserved1 = 0
      if self.maxFreqErVal0 is None:
        self.maxFreqErVal0 = 0
      if self.freqFailCnt0 is None:
        self.freqFailCnt0 = 0
      if self.maxFreqFailTime0 is None:
        self.maxFreqFailTime0 = 0
      if self.reserved2 is None:
        self.reserved2 = 0
      if self.profIndex1 is None:
        self.profIndex1 = 0
      if self.reserved3 is None:
        self.reserved3 = 0
      if self.reserved4 is None:
        self.reserved4 = 0
      if self.maxFreqErVal1 is None:
        self.maxFreqErVal1 = 0
      if self.freqFailCnt1 is None:
        self.freqFailCnt1 = 0
      if self.maxFreqFailTime1 is None:
        self.maxFreqFailTime1 = 0
      if self.reserved5 is None:
        self.reserved5 = 0
      if self.timeStamp is None:
        self.timeStamp = 0
    else:
      self.statusFlags = 0
      self.errorCode = 0
      self.profIndex0 = 0
      self.reserved0 = 0
      self.reserved1 = 0
      self.maxFreqErVal0 = 0
      self.freqFailCnt0 = 0
      self.maxFreqFailTime0 = 0
      self.reserved2 = 0
      self.profIndex1 = 0
      self.reserved3 = 0
      self.reserved4 = 0
      self.maxFreqErVal1 = 0
      self.freqFailCnt1 = 0
      self.maxFreqFailTime1 = 0
      self.reserved5 = 0
      self.timeStamp = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2H2BHi3I2BHi4I().pack(_x.statusFlags, _x.errorCode, _x.profIndex0, _x.reserved0, _x.reserved1, _x.maxFreqErVal0, _x.freqFailCnt0, _x.maxFreqFailTime0, _x.reserved2, _x.profIndex1, _x.reserved3, _x.reserved4, _x.maxFreqErVal1, _x.freqFailCnt1, _x.maxFreqFailTime1, _x.reserved5, _x.timeStamp))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 48
      (_x.statusFlags, _x.errorCode, _x.profIndex0, _x.reserved0, _x.reserved1, _x.maxFreqErVal0, _x.freqFailCnt0, _x.maxFreqFailTime0, _x.reserved2, _x.profIndex1, _x.reserved3, _x.reserved4, _x.maxFreqErVal1, _x.freqFailCnt1, _x.maxFreqFailTime1, _x.reserved5, _x.timeStamp,) = _get_struct_2H2BHi3I2BHi4I().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2H2BHi3I2BHi4I().pack(_x.statusFlags, _x.errorCode, _x.profIndex0, _x.reserved0, _x.reserved1, _x.maxFreqErVal0, _x.freqFailCnt0, _x.maxFreqFailTime0, _x.reserved2, _x.profIndex1, _x.reserved3, _x.reserved4, _x.maxFreqErVal1, _x.freqFailCnt1, _x.maxFreqFailTime1, _x.reserved5, _x.timeStamp))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 48
      (_x.statusFlags, _x.errorCode, _x.profIndex0, _x.reserved0, _x.reserved1, _x.maxFreqErVal0, _x.freqFailCnt0, _x.maxFreqFailTime0, _x.reserved2, _x.profIndex1, _x.reserved3, _x.reserved4, _x.maxFreqErVal1, _x.freqFailCnt1, _x.maxFreqFailTime1, _x.reserved5, _x.timeStamp,) = _get_struct_2H2BHi3I2BHi4I().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2H2BHi3I2BHi4I = None
def _get_struct_2H2BHi3I2BHi4I():
    global _struct_2H2BHi3I2BHi4I
    if _struct_2H2BHi3I2BHi4I is None:
        _struct_2H2BHi3I2BHi4I = struct.Struct("<2H2BHi3I2BHi4I")
    return _struct_2H2BHi3I2BHi4I
