# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from radar_msgs/RlRecvdGpAdcData.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import radar_msgs.msg

class RlRecvdGpAdcData(genpy.Message):
  _md5sum = "c77259e6e9e4b7d6f098acf35b1c17dd"
  _type = "radar_msgs/RlRecvdGpAdcData"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """RlGpAdcData[6]  sensor
uint16[4]       reserved0
uint32[7]       reserved1
================================================================================
MSG: radar_msgs/RlGpAdcData
uint16 min
uint16 max
uint16 avg"""
  __slots__ = ['sensor','reserved0','reserved1']
  _slot_types = ['radar_msgs/RlGpAdcData[6]','uint16[4]','uint32[7]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       sensor,reserved0,reserved1

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RlRecvdGpAdcData, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.sensor is None:
        self.sensor = [radar_msgs.msg.RlGpAdcData() for _ in range(6)]
      if self.reserved0 is None:
        self.reserved0 = [0] * 4
      if self.reserved1 is None:
        self.reserved1 = [0] * 7
    else:
      self.sensor = [radar_msgs.msg.RlGpAdcData() for _ in range(6)]
      self.reserved0 = [0] * 4
      self.reserved1 = [0] * 7

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      if len(self.sensor) != 6:
        self._check_types(ValueError("Expecting %s items but found %s when writing '%s'" % (6, len(self.sensor), 'self.sensor')))
      for val1 in self.sensor:
        _x = val1
        buff.write(_get_struct_3H().pack(_x.min, _x.max, _x.avg))
      buff.write(_get_struct_4H().pack(*self.reserved0))
      buff.write(_get_struct_7I().pack(*self.reserved1))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.sensor is None:
        self.sensor = None
      end = 0
      self.sensor = []
      for i in range(0, 6):
        val1 = radar_msgs.msg.RlGpAdcData()
        _x = val1
        start = end
        end += 6
        (_x.min, _x.max, _x.avg,) = _get_struct_3H().unpack(str[start:end])
        self.sensor.append(val1)
      start = end
      end += 8
      self.reserved0 = _get_struct_4H().unpack(str[start:end])
      start = end
      end += 28
      self.reserved1 = _get_struct_7I().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      if len(self.sensor) != 6:
        self._check_types(ValueError("Expecting %s items but found %s when writing '%s'" % (6, len(self.sensor), 'self.sensor')))
      for val1 in self.sensor:
        _x = val1
        buff.write(_get_struct_3H().pack(_x.min, _x.max, _x.avg))
      buff.write(self.reserved0.tostring())
      buff.write(self.reserved1.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.sensor is None:
        self.sensor = None
      end = 0
      self.sensor = []
      for i in range(0, 6):
        val1 = radar_msgs.msg.RlGpAdcData()
        _x = val1
        start = end
        end += 6
        (_x.min, _x.max, _x.avg,) = _get_struct_3H().unpack(str[start:end])
        self.sensor.append(val1)
      start = end
      end += 8
      self.reserved0 = numpy.frombuffer(str[start:end], dtype=numpy.uint16, count=4)
      start = end
      end += 28
      self.reserved1 = numpy.frombuffer(str[start:end], dtype=numpy.uint32, count=7)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3H = None
def _get_struct_3H():
    global _struct_3H
    if _struct_3H is None:
        _struct_3H = struct.Struct("<3H")
    return _struct_3H
_struct_4H = None
def _get_struct_4H():
    global _struct_4H
    if _struct_4H is None:
        _struct_4H = struct.Struct("<4H")
    return _struct_4H
_struct_7I = None
def _get_struct_7I():
    global _struct_7I
    if _struct_7I is None:
        _struct_7I = struct.Struct("<7I")
    return _struct_7I
