(cl:in-package radar_msgs-msg)
(cl:export '(OBJECT_ID-VAL
          OBJECT_ID
          AGE-VAL
          AGE
          MEASUREMENT_STATUS-VAL
          MEASUREMENT_STATUS
          MOTION_STATE-VAL
          MOTION_STATE
          EXISTANCE_CONFIDENCE-VAL
          EXISTANCE_CONFIDENCE
          POSE-VAL
          POSE
          DIMENSIONS-VAL
          DIMENSIONS
          VELOCITY-VAL
          VELOCITY
          ACCELERATION-VAL
          ACCELERATION
          V2GROUND-VAL
          V2GROUND
          POSE_NEAREST-VAL
          POSE_NEAREST
          TYPE-VAL
          TYPE
          CAR_CONFIDENCE-VAL
          CAR_CONFIDENCE
          BIKE_CONFIDENCE-VAL
          BIKE_CONFIDENCE
          PED_CONFIDENCE-VAL
          PED_CONFIDENCE
          TRUCK_CONFIDENCE-VAL
          TRUCK_CONFIDENCE
          SIGNBOARD_CONFIDENCE-VAL
          SIGNBOARD_CONFIDENCE
          GROUND_CONFIDENCE-VAL
          GROUND_CONFIDENCE
          OBSTACLE_CONFIDENCE-VAL
          OBSTACLE_CONFIDENCE
          ENROLLPTSNUM-VAL
          ENROLLPTSNUM
          NEARESTPTSX-VAL
          NEARESTPTSX
          NEARESTPTSY-VAL
          NEARESTPTSY
          NEARESTPTSZ-VAL
          NEARESTPTSZ
          RESERVED_D-VAL
          RESERVED_D
          RESERVED_E-VAL
          RESERVED_E
          RESERVED_F-VAL
          RESERVED_F
          RESERVED_G-VAL
          RESERVED_G
          RESERVED_H-VAL
          RESERVED_H
          RESERVED_I-VAL
          RESERVED_I
          RESERVED_J-VAL
          RESERVED_J
          RESERVED_K-VAL
          RESERVED_K
          RESERVED_L-VAL
          RESERVED_L
          RESERVED_M-VAL
          RESERVED_M
          RESERVED_N-VAL
          RESERVED_N
          RESERVED_O-VAL
          RESERVED_O
          RESERVED_P-VAL
          RESERVED_P
))