(cl:in-package radar_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          RADARID-VAL
          RADARID
          FRAMECNT-VAL
          FRAMECNT
          TYPE-VAL
          TYPE
          TARGETNUM-VAL
          TARGETNUM
          POLARSTATE-VAL
          POLARSTATE
          X-VAL
          X
          Y-VAL
          Y
          Z-VAL
          Z
          V-VAL
          V
          AZIMUTH-VAL
          AZIMUTH
          ELEVATION-VAL
          ELEVATION
          SNR-VAL
          SNR
          POWER-VAL
          POWER
          VALID_FLG-VAL
          VALID_FLG
          EXISTANCE_PROBABILITY-VAL
          EXISTANCE_PROBABILITY
          MOTION_STATE-VAL
          MOTION_STATE
          DETECTION_CLASS-VAL
          DETECTION_CLASS
          RESET_CNT-VAL
          RESET_CNT
          ODTIMEOUTCNT-VAL
          ODTIMEOUTCNT
          RESERVED_A-VAL
          RESERVED_A
          RESERVED_B-VAL
          RESERVED_B
          RESERVED_C-VAL
          RESERVED_C
          RESERVED_D-VAL
          RESERVED_D
          RESERVED_E-VAL
          RESERVED_E
          RESERVED_F-VAL
          RESERVED_F
          RESERVED_G-VAL
          RESERVED_G
          RESERVED_H-VAL
          RESERVED_H
          RESERVED_I-VAL
          RESERVED_I
          RESERVED_J-VAL
          RESERVED_J
          RESERVED_K-VAL
          RESERVED_K
          RESERVED_L-VAL
          RESERVED_L
          RESERVED_M-VAL
          RESERVED_M
          RESERVED_N-VAL
          RESERVED_N
          RESERVED_O-VAL
          RESERVED_O
))