(cl:in-package radar_msgs-msg)
(cl:export '(STATUSFLAGS-VAL
          STATUSFLAGS
          ERRORCODE-VAL
          ERRORCODE
          PROFINDEX-VAL
          PROFINDEX
          RESERVED0-VAL
          RESERVED0
          LPFCUTOFFBANDEDGEDROOPVALRX0-VAL
          LPFCUTOFFBANDEDGEDROOPVALRX0
          HPFCUTOFFFREQER-VAL
          HPFCUTOFFFREQER
          LPFCUTOFFSTOPBANDATTEN-VAL
          LPFCUTOFFSTOPBANDATTEN
          RXIFAGAINERVAL-VAL
          RXIFAGAINERVAL
          IFGAINEXP-VAL
          IFGAINEXP
          RESERVED2-VAL
          RESERVED2
          LPFCUTOFFBANDEDGEDROOPVALRX-VAL
          LPFCUTOFFBANDEDGEDROOPVALRX
          TIMESTAMP-VAL
          TIMESTAMP
))