(cl:in-package radar_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          RADARID-VAL
          RADARID
          FRAMECNT-VAL
          FRAMECNT
          SENSORPOSITIONINVALIDFLAGS-VAL
          SENSORPOSITIONINVALIDFLAGS
          SENSORXPOSITION-VAL
          SENSORXPOSITION
          SENSORYPOSITION-VAL
          SENSORYPOSITION
          SENSORZPOSITION-VAL
          SENSORZPOSITION
          SENSORROLLANGLE-VAL
          SENSORROLLANGLE
          SENSORPITCHANGLE-VAL
          SENSORPITCHANGLE
          SENSORYAWANGLE-VAL
          SENSORYAWANGLE
          AZIMUTHCORRECTION-VAL
          AZIMUTHCORRECTION
          ELEVATIONCORRECTION-VAL
          ELEVATIONCORRECTION
))