(cl:in-package radar_msgs-msg)
(cl:export '(STATUSFLAGS-VAL
          STATUSFLAGS
          ERRORCODE-VAL
          ERRORCODE
          PROFINDEX-VAL
          PROFINDEX
          NOISEPOWER00-VAL
          NOISEPOWER00
          NOISEPOWER01-VAL
          NOISEPOWER01
          NOISEPOWER02-VAL
          NOISEPOWER02
          TXGAINVAL-VAL
          TXGAINVAL
          TXPHAVAL-VAL
          TXPHAVAL
          NOISEPOWER10-VAL
          NOISEPOWER10
          NOISEPOWER11-VAL
          NOISEPOWER11
          NOISEPOWER12-VAL
          NOISEPOWER12
          NOISEPOWER20-VAL
          NOISEPOWER20
          NOISEPOWER21-VAL
          NOISEPOWER21
          NOISEPOWER22-VAL
          NOISEPOWER22
          RESERVED0-VAL
          RESERVED0
          RESERVED1-VAL
          RESERVED1
          TIMESTAMP-VAL
          TIMESTAMP
))