(cl:in-package radar_msgs-msg)
(cl:export '(STATUSFLAGS-VAL
          STATUSFLAGS
          ERRORCODE-VAL
          ERRORCODE
          PROFINDEX0-VAL
          PROFINDEX0
          RESERVED0-VAL
          RESERVED0
          RESERVED1-VAL
          RESERVED1
          MAXFREQERVAL0-VAL
          MAXFREQERVAL0
          FREQFAILCNT0-VAL
          FREQFAILCNT0
          MAXFREQFAILTIME0-VAL
          MAXFREQFAILTIME0
          RESERVED2-VAL
          RESERVED2
          PROFINDEX1-VAL
          PROFINDEX1
          RESERVED3-VAL
          RESERVED3
          RESERVED4-VAL
          RESERVED4
          MAXFREQERVAL1-VAL
          MAXFREQERVAL1
          FREQFAILCNT1-VAL
          FREQFAILCNT1
          MAXFREQFAILTIME1-VAL
          MAXFREQFAILTIME1
          RESERVED5-VAL
          RESERVED5
          TIMESTAMP-VAL
          TIMESTAMP
))