(cl:in-package radar_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          FRAMEID-VAL
          FRAMEID
          CFARCOUNT-VAL
          CFARCOUNT
          TARGETNUM-VAL
          TARGETNUM
          RESETCNT-VAL
          RESETCNT
          OBJNUM-VAL
          OBJNUM
          CARSPEED-VAL
          CARSPEED
          CARYAWRATE-VAL
          CARYAWRATE
          GEARSTATE-VAL
          GEARSTATE
          ODTIMEOUTCNT-VAL
          ODTIMEOUTCNT
          COMPROTV_I-VAL
          COMPROTV_I
          COMPROTV_II-VAL
          COMPROTV_II
          FRAMELOSTCNT-VAL
          FRAMELOSTCNT
          BEFOREADCERRCNT-VAL
          BEFOREADCERRCNT
          AFTERADCERRCNT-VAL
          AFTERADCERRCNT
          UDPFRAMELOSTCNT-VAL
          UDPFRAMELOSTCNT
          UDPFREQ-VAL
          UDPFREQ
          TIMESYNCSTATUS-VAL
          TIMESYNCSTATUS
          VELESTIMATE-VAL
          VELESTIMATE
          GNDK-VAL
          GNDK
          GNDB-VAL
          GNDB
          PCL_TIME-VAL
          PCL_TIME
          OD_TIME-VAL
          OD_TIME
          RDFRAMELOSTCNT-VAL
          RDFRAMELOSTCNT
))