(cl:in-package radar_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          RADARID-VAL
          RADARID
          FRAMECNT-VAL
          FRAMECNT
          ALARMNUM-VAL
          ALARMNUM
          ALARMCODE01-VAL
          ALARMCODE01
          ALARMCODE02-VAL
          ALARMCODE02
          ALARMCODE03-VAL
          ALARMCODE03
          ALARMCODE04-VAL
          ALARMCODE04
          ALARMCODE05-VAL
          ALARMCODE05
          ALARMCODE06-VAL
          ALARMCODE06
          ALARMCODE07-VAL
          ALARMCODE07
          ALARMCODE08-VAL
          ALARMCODE08
          ALARMCODE09-VAL
          ALARMCODE09
          ALARMCODE10-VAL
          ALARMCODE10
          ALARMCODE11-VAL
          ALARMCODE11
          ALARMCODE12-VAL
          ALARMCODE12
          ALARMCODE13-VAL
          ALARMCODE13
          ALARMCODE14-VAL
          ALARMCODE14
          ALARMCODE15-VAL
          ALARMCODE15
          ALARMCODE16-VAL
          ALARMCODE16
          ALARMCODE17-VAL
          ALARMCODE17
          ALARMCODE18-VAL
          ALARMCODE18
          ALARMCODE19-VAL
          ALARMCODE19
          ALARMCODE20-VAL
          ALARMCODE20
))