(cl:in-package radar_msgs-msg)
(cl:export '(STATUSFLAGS-VAL
          STATUSFLAGS
          ERRORCODE-VAL
          ERRORCODE
          PROFINDEX-VAL
          PROFINDEX
          LOOPBACKPOWERRF1-VAL
          LOOPBACKPOWERRF1
          LOOPBACKPOWERRF2-VAL
          LOOPBACKPOWERRF2
          LOOPBACKPOWERRF3-VAL
          LOOPBACKPOWERRF3
          RXGAINVAL-VAL
          RXGAINVAL
          RXPHASEVAL-VAL
          RXPHASEVAL
          RXNOISEPOWER1-VAL
          RXNOISEPOWER1
          RXNOISEPOWER2-VAL
          RXNOISEPOWER2
          TIMESTAMP-VAL
          TIMESTAMP
))