(cl:in-package radar_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          RADARID-VAL
          RADARID
          FRAMECNT-VAL
          FRAMECNT
          OBJNUM-VAL
          OBJNUM
          OBJECT_ID-VAL
          OBJECT_ID
          AGE-VAL
          AGE
          MEASUREMENT_STATUS-VAL
          MEASUREMENT_STATUS
          MOTION_STATE-VAL
          MOTION_STATE
          EXISTANCE_CONFIDENCE-VAL
          EXISTANCE_CONFIDENCE
          POSITION_X-VAL
          POSITION_X
          POSITION_Y-VAL
          POSITION_Y
          POSITION_Z-VAL
          POSITION_Z
          VELOCITY_X-VAL
          VELOCITY_X
          VELOCITY_Y-VAL
          VELOCITY_Y
          VELOCITY_Z-VAL
          VELOCITY_Z
          ACCELERATION_X-VAL
          ACCELERATION_X
          ACCELERATION_Y-VAL
          ACCELERATION_Y
          ACCELERATION_Z-VAL
          ACCELERATION_Z
          V2GROUND_X-VAL
          V2GROUND_X
          V2GROUND_Y-VAL
          V2GROUND_Y
          V2GROUND_Z-VAL
          V2GROUND_Z
          ORIENTATION-VAL
          ORIENTATION
          TYPE-VAL
          TYPE
          CAR_CONFIDENCE-VAL
          CAR_CONFIDENCE
          BIKE_CONFIDENCE-VAL
          BIKE_CONFIDENCE
          PED_CONFIDENCE-VAL
          PED_CONFIDENCE
          TRUCK_CONFIDENCE-VAL
          TRUCK_CONFIDENCE
          SIGNBOARD_CONFIDENCE-VAL
          SIGNBOARD_CONFIDENCE
          GROUND_CONFIDENCE-VAL
          GROUND_CONFIDENCE
          OBSTACLE_CONFIDENCE-VAL
          OBSTACLE_CONFIDENCE
          LENGTH-VAL
          LENGTH
          WIDTH-VAL
          WIDTH
          HEIGHT-VAL
          HEIGHT
          OD_PROCESS_TIME-VAL
          OD_PROCESS_TIME
          RESERVED_B-VAL
          RESERVED_B
          RESERVED_C-VAL
          RESERVED_C
          RESERVED_D-VAL
          RESERVED_D
))