(cl:in-package radar_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          RADARID-VAL
          RADARID
          FRAMECNT-VAL
          FRAMECNT
          CAPTURETIME-VAL
          CAPTURETIME
          FRAMELOSTCNT-VAL
          FRAMELOSTCNT
          ADCERRCNT-VAL
          ADCERRCNT
          RESERVED_A-VAL
          RESERVED_A
          RESERVED_B-VAL
          RESERVED_B
          TIME1DFFT-VAL
          TIME1DFFT
          RESERVED_C-VAL
          RESERVED_C
          RESERVED_D-VAL
          RESERVED_D
          RESERVED_E-VAL
          RESERVED_E
          RESERVED_F-VAL
          RESERVED_F
          TIME2DFFT-VAL
          TIME2DFFT
          RESERVED_G-VAL
          RESERVED_G
          RESERVED_H-VAL
          RESERVED_H
          RESERVED_I-VAL
          RESERVED_I
          RESERVED_J-VAL
          RESERVED_J
          TIMERDMAP-VAL
          TIMERDMAP
          RESERVED_K-VAL
          RESERVED_K
          RESERVED_L-VAL
          RESERVED_L
          RESERVED_M-VAL
          RESERVED_M
          RESERVED_N-VAL
          RESERVED_N
          TIMECFAR-VAL
          TIMECFAR
          RESERVED_O-VAL
          RESERVED_O
          RESERVED_P-VAL
          RESERVED_P
          RESERVED_Q-VAL
          RESERVED_Q
          RESERVED_R-VAL
          RESERVED_R
          TIMEDOA-VAL
          TIMEDOA
          RESERVED_S-VAL
          RESERVED_S
          RESERVED_T-VAL
          RESERVED_T
          RESERVED_U-VAL
          RESERVED_U
          RESERVED_V-VAL
          RESERVED_V
          TIMEPCL-VAL
          TIMEPCL
          RESERVED_W-VAL
          RESERVED_W
          RESERVED_X-VAL
          RESERVED_X
          RESERVED_Y-VAL
          RESERVED_Y
          RESERVED_Z-VAL
          RESERVED_Z
          TIMEOD-VAL
          TIMEOD
          ODTIMEOUTCNT-VAL
          ODTIMEOUTCNT
          SELFCALISTATUS-VAL
          SELFCALISTATUS
          RESERVED_AA-VAL
          RESERVED_AA
          RESERVED_AB-VAL
          RESERVED_AB
          RESERVED_AC-VAL
          RESERVED_AC
          RESERVED_AD-VAL
          RESERVED_AD
))