Header header                   # Includes measurement timestamp and coordinate frame.
uint32 radarID                  # radar ID
uint32 frameCnt                 # frame cnt in radar
uint32 alarmNum                 # number of alarm
uint16 alarmCode01
uint16 alarmCode02
uint16 alarmCode03
uint16 alarmCode04
uint16 alarmCode05
uint16 alarmCode06
uint16 alarmCode07
uint16 alarmCode08
uint16 alarmCode09
uint16 alarmCode10
uint16 alarmCode11
uint16 alarmCode12
uint16 alarmCode13
uint16 alarmCode14
uint16 alarmCode15
uint16 alarmCode16
uint16 alarmCode17
uint16 alarmCode18
uint16 alarmCode19
uint16 alarmCode20