Header  header                   # Includes measurement timestamp and coordinate frame.
uint32  radarID                  # radar ID
uint32  frameCnt                 # frame cnt in radar
uint16  sensorPositionInvalidFlags
float32 sensorXPosition             #unit: m
float32 sensorYPosition             #unit: m
float32 sensorZPosition             #unit: m
float32 sensorRollAngle             #unit: degree
float32 sensorPitchAngle            #unit: degree
float32 sensorYawAngle              #unit: degree
float32 azimuthCorrection           #unit: degree
float32 elevationCorrection         #unit: degree