weights: weights/yolov5_l.pth
cfg: models/dft/cnn_swin_buchang_TwoEncoding_FLIR_aligned.yaml
data: ./data/multispectral/FLIR_aligned.yaml
hyp: data/hyp.scratch_prune.yaml
epochs: 60
batch_size: 10
img_size:
- 640
- 640
rect: false
resume: runs/train/cnn_swin_buchang_TwoEncoding_FLIR_aligned_0.845/weights/best.pt
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
image_weights: false
device: 4,2
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
workers: 8
project: runs/train
entity: null
name: exp
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
prune_rate: 0.3
imgsz: 640
dataset: FLIR
model: DDNF
compression: backbone
prunemethod: L1
pruned: false
round: 0
topk: 1.0
exp: false
initial_rate: 0.05
initial_thres: 5.0
rate_slope: 0.0
thres_slope: 0.0
world_size: 1
global_rank: -1
save_dir: runs/train/exp190
total_batch_size: 10
